### ISSUE TITLE
Encourage AI to use RPGs

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#1168]
I'm not sure this was said before but could there be a chance where we update the AGM_AI and have the ai with unguided RPGs to be able to fire them with low chances for direct hit (.5%) and a higher chance to hit roughly 100 m near you.
This also can be pretty good for having the ai shoot unguided RPGs at moving helis. While moving they have a higher chance in missing but can be very close, but as for a heli that is on the ground, they have a better chance at hitting the heli directly. This can give a good tense feeling as rockets is flying right next to you.

**Comment by commy2** [comment]
This is config work by the RPGs author. BIS ones are working fine.
