### ISSUE TITLE
Vehicle Repair Time Progress & Time

### ISSUE THREAD

**Issue by ferox113** [KoffeinFlummi/AGM#1206]
As a frequent user of AGM in a realism unit, I would like for the AGM vehicle repair function to be revised:

-If a person repairing a vehicle (Ground/Air vehicle), stops the repairing; the vehicle should be repaired some of the way, when said person (or anyone else) resumes the repairing of the vehicle.
At this moment, if somebody have to cancel the act; the possible progress of the repairing will not be saved.

-Option for multiple people to be working on a vehicle should be added.
If multiple people are working on the same vehicle, a significant change in the repair time should be implemented (here, saving time; as we now have double the amount of hands working on the same object).
The repair time should not be half the normal time with another person repairing the same vehicle; but should be of a significant coefficient.

Thanks!

**Comment by commy2** [comment]
\>\>https://github.com/KoffeinFlummi/AGM/issues/1937
