### ISSUE TITLE
Unloading Vehicle Ammo box can trap player

### ISSUE THREAD

**Issue by milliwar** [KoffeinFlummi/AGM#1242]
Arma 3 version: 1.30.127372
AGM version: 0.9.3
Additional mods: CBA_A3 1.0.9.140907 RC4
Tested on: Editor

1. Load a Vehicle Ammo box into one of the military trucks (HEMTT, Typhoon, Kamaz).
2. Stand at the back of the truck (i.e. the realistic place to unload) and unload the Vehicle Ammo box.

In my tests I got stuck between the Vehicle Ammo box and the truck more often than not. Once I took light damage to my torso. The issue is noticably less likely to occur if you're standing on the left or right side of the truck when you unload.

**Comment by commy2** [comment]
\>\>https://github.com/KoffeinFlummi/AGM/issues/1937
