### ISSUE TITLE
Optional additional configs to standardize ballistics between mods

### ISSUE THREAD

**Issue by Applejaxc** [KoffeinFlummi/AGM#1287]
In my experience, it's difficult to join random ArmA 3 COOP servers where everyone isn't in their underware and holding no weapons if you haven't downloaded every single mod on Armaholic. While I don't have a problem with diversifying the game's lackluster roster, it would be nice if AGM had optional configs that would standardize *at least* the most popular weapon mods (Massi's weapon pack, HLC AK/AR15, FHQ M4, RH M4, to name a few) so one player's 5.56 isn't doing twice the damage of another player's 5.56 on an AGM server.

**Comment by commy2** [comment]
Out of scope. See AGM_compatibility.
