### ISSUE TITLE
Action Button

### ISSUE THREAD

**Issue by Lumnuon** [KoffeinFlummi/AGM#1332]
The Action-Menu of Arma is still not very user friendly while the AGM Menu works much better although in some situations too slow for special actions (Open door, Get in Vehicle...) the concept of the Action Button Mod (http://makearmanotwar.com/entry/d6gUnQL4xX#.VEOvYBaiP7Q) seems promising. Do you think it would benefit the mod in a later state to do something similar? Probably try to cooperate with that special Mod Maker since we really dont need a new Gameplay Enhancement Mod like he wants to devolop because we already have Awesome Mods (AGM/CSE) but putting ideas together (after MANW) would benefit Arma as a whole.

**Comment by commy2** [comment]
Nope. Don't like it. Sry.
