### ISSUE TITLE
AGM_Goggles is not Zeus compatible

### ISSUE THREAD

**Issue by CorruptedHeart** [KoffeinFlummi/AGM#1363]
AGM_Goggles isn't Zeus compatible/friendly, I might have abused #defines and global variables when creating the system. I will try to cut down on direct calls to `player`, hopefully at least a portion of it can fixed.
__Tasks__
- [ ] Change `player` to `AGM_player`
- [ ] Cut back on global variable usage

**Comment by commy2** [comment]
Same as https://github.com/KoffeinFlummi/AGM/issues/327
