### ISSUE TITLE
ACRE2/TFAR continued radio transmission while unconscious

### ISSUE THREAD

**Issue by Rickyfox** [KoffeinFlummi/AGM#1529]
Using ACRE2 and AGM in combination we've experienced the following problem:

If shot during a radio transmission the transmission sometimes continues although the sender went unconscious from the wounding.

**Comment by Sniperhid** [comment]
Okay I think I have the solution for proper ACRE2 support, after studying some older scripts and see that 'acre_api_fnc_setGlobalVolume' replaces the older method of directly changing the volume variable . AFAIK from my poking this is the only way to get this to work properly.

```
//Call when going unconscious
_orgVolume = [0] call acre_api_fnc_setGlobalVolume;
player setVariable ["acre_sys_core_isDisabled", true, true];
[true] call acre_api_fnc_setSpectator;

//Call on Wakeup
player setVariable ["acre_sys_core_isDisabled", false, true];
[false] call acre_api_fnc_setSpectator;
[_orgVolume] call acre_api_fnc_setGlobalVolume;
```

Explanation: The player will not be able to hear anything but nobody will be able to hear the player either so no bugs!
```
acre_sys_core_isDisabled - If set to true will prevent local input/spectators from hearing the player locally
[true] call acre_api_fnc_setSpectator; - Prevents alive players from hearing their radios.
[0] call acre_api_fnc_setGlobalVolume; -- Prevents the player from hearing the spectator. It does seem like alternatively changing 'acre_sys_core_globalVolume' directly to a value between 0-1 would work too but I don't this is supported.
```

**Comment by jonpas** [comment]
But it has to be same as TFAR, meaning hearing others, no?

**Comment by Sniperhid** [comment]
At present it appears the only way without bypassing the ACRE2 API is the method I mentioned.

Having something that is bug free and supported by the mod authors (ACRE2) seems better than a buggy implementation? I have been playing with ACRE2 and AGM for a while and have noticed this bug several times now and it's quite annoying.

If your looking for official support in ACRE2 for having hearing others at limited volume. Then the best thing to request is that 'acre_sys_core_isDisabled' also blocks radio comms the way it blocks local chat.

**Comment by commy2** [comment]
>The player will not be able to hear anything but nobody will be able to hear the player either so no bugs!

But thats not what Flummi wanted. He wants the player to still hear the others, but unable to speak himself. The same is true for TFAR.

The only issue I have with ACRE2 is the script error. Otherwise it's working fine.

**Comment by jaynus** [comment]
http://acre.idi-systems.com/archive/acre2_2.1.0.707.zip

Can someone repro and report back RPT with this build?

**Comment by Trigger81** [comment]
Work for me with AGM 0.95.2 and ACRE² 2.1.0.707

**Comment by bux578** [comment]
Roger, so it'll work with the next ACRE update.
