### ISSUE TITLE
AGM_Interaction_fnc_addInteractionSelf broken

### ISSUE THREAD

**Issue by BaerMitUmlaut** [KoffeinFlummi/AGM#1543]
AGM_Interaction_fnc_addInteractionSelf is currently broken, probably a bug within "fn_showMenu.sqf". No script error thrown, the action just doesn't show up.

The example for "AGM_Interaction_fnc_addInteraction" in the Wiki also needs a small update (distance parameter is missing).

**Comment by Feivel69** [comment]
Is addInteractionSelf possibly broken again?

_fixVanillaDamage = ["Fix Vanilla Damage", {true}, {player setDamage 0;}, true] call AGM_Interaction_fnc_addInteractionSelf;

in my own player's init doesn't make a new action appear in the menu.

addInteraction works for me.
