### ISSUE TITLE
Drag/Carry Walking Wounded

### ISSUE THREAD

**Issue by JinougaF** [KoffeinFlummi/AGM#1592]
Sometime people in Arma3 would seriously wounded but not died,and their legs may broken and coundn't move fast.When this happened during a fire fight,you may not have enough time to treat him and he is not unconscious so that you can't use the drag/carry function to drag him,the only chance for him is to move very slow to cover.So if we could just approach him and drag/carry him back to cover would be fine.He no need to move himself slowly with his broken legs to cover.

Just like in real life we could take the wounded one to cover first.

**Comment by commy2** [comment]
Not gonna happen due to lack of animations. Sry.
