### ISSUE TITLE
Squad Command menu

### ISSUE THREAD

**Issue by IvosHcz** [KoffeinFlummi/AGM#1593]
Expansion for the object interaction menu

One suggestion for object interaction menu (command rose 2)
When player is in the proximity of the object (vehicle) current menu will show up.
When player is NOT in the proximity of the object, then will show up the alternative (command) menu.

Alternative menu will replace vanilla interaction menu (Menu in the left top corner)
It will allow you to command your squad and use fast weapons switching together.

Example 1: Basic command menu
Access to the most used commands

![menu_command_1](https://cloud.githubusercontent.com/assets/7911347/5168060/48f709e2-73fc-11e4-89d3-9d5f2ff8eb13.jpg)

Example 2: When you choose More…
Access to all commands arranged as vanilla interaction menu (Menu in the left top corner)

![menu_command_2](https://cloud.githubusercontent.com/assets/7911347/5168143/f4e58184-73fc-11e4-8ff4-cc58dddd4f5b.jpg)

P.S.: Support and Custom command could be add in to the self interaction menu.

**Comment by commy2** [comment]
Nope, sry. Out of scope.
