### ISSUE TITLE
adding an ambient life module

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#1599]
We all know that a lot of people just place down ai that is just bluefor and opfor. Nobody has time to worry about civilians and animals. I wonder if it is possible to add a module where the system will automatically add civilians and animals to the map within a set distance of set players. The module could consist of how many ambient life spawns with a simple very low, low, medium, high options. This will make all of the maps feel more alive and realistic.

**Comment by KoffeinFlummi** [comment]
Expired.
