### ISSUE TITLE
Drag and hide AI enemies' died bodies

### ISSUE THREAD

**Issue by JinougaF** [KoffeinFlummi/AGM#1607]
When an AI enemy was killed,it would be better if we could drag his died body and hide it to make others can't find.Very necessary in a stealth mission.

**Comment by nomisum** [comment]
I used ![BangaBobs dragBody - Script](http://forums.bistudio.com/showthread.php?182000-Drag-Dead-Body-Script&p=2754022&viewfull=1#post2754022) and it worked quite well. He seems to use attachTo though?

As I cant add anything to AGM-interaction-menu yet (other than interactionSelf) I cant combine this with AGM unfortunately.

**Comment by KoffeinFlummi** [comment]
If I remember correctly, when trying to work with ragdolls you had to do stuff every frame to keep the body from collapsing back into it's original state or some such nonsense. Also, your link is broken.

**Comment by nomisum** [comment]
Sorry, you are just too fast (fixed this in an instant) xD 

Yeah, seems he updates every frame, you're right.

**Comment by commy2** [comment]
That won't work reliably in MP then.

**Comment by nomisum** [comment]
Too bad, shame on BIs ragdoll policy. Thanks for the replies anyway!
