### ISSUE TITLE
Hit reaction for infantry

### ISSUE THREAD

**Issue by a567765** [KoffeinFlummi/AGM#1628]
Sure BIS won't implement it, so...

How about adding some realistic hit reaction to bodies? I mean now when you hit target - there's just "blood cloud" on its body and no animations or other reaction. If hitting was not lethal or not strong enough to make him unconscious  - soldier just can stand or run as it wasn't any hit at all. I think it's totally unrealistic, especially for calibres like 7.62 or stronger.

For example, how about to force infantry to fall down after hitting by gun fire? Mayby implement some animations for different hits - like animation in A2 ACE when you're running and enemy gunfire hits force you to fall on the ground.

**Comment by Tachii** [comment]
Maybe u can also impliment tagging? When u run and get hit you get forced to walk for a short period of time, or when you get hit by explosion/backblast?  Like in csgo:Tagging - 10/2/14: http://youtu.be/WY7vJlatMcg

**Comment by commy2** [comment]
I don't think thats necessary after the PR. You play a falling animation if you get hit, so you can't walk or run anyway.

**Comment by Tachii** [comment]
Even if you get hit by an explosion blast or from some pistol bullet in the armored vest? 

I think it would be better to split behaviour by the damage taken in a taken period of time. For example if damage( or in case of agm - pain)  value is higher then 0.5 you fall down, if its lower you get forced to walk for a period of time

**Comment by Tachii** [comment]
Btw there is some interesting feature I saw in this mod, throwing away a lancher: http://www.armaholic.com/page.php?id=25997 maybe you can use it for throwing away a weapon with keeping its attachments.

**Comment by commy2** [comment]
Laxxman deletes the attachments, which is something we won't accept as drawback.

**Comment by commy2** [comment]
\>\> https://github.com/KoffeinFlummi/AGM/pull/1738
