### ISSUE TITLE
compatibility with Alive IED module

### ISSUE THREAD

**Issue by Drezzo** [KoffeinFlummi/AGM#1727]
The AGM interaction menu doesn't give the option to disarm the IED, nor can you pick it up after disarming it eventhough you see a demo charge, probably due to the way Alive scripted them. When approaching as an explosive specialist you get a hint saying IED detected within 8 meters and you get an action in the scollmenu to disarm it.
Can it be made compatible with the agm explosives interaction menu?

Sometimes you are presented with this screen, which you can't escape until you've chosen which wire to cut:
![ied](https://cloud.githubusercontent.com/assets/6758100/5397069/858f455a-8157-11e4-9f0e-889fce602a67.jpg)

What do you think about adding something similar to agm explosives (cut the correct wire) and possibly disabling the scollwheel option and the fact that you are locked until you choose a wire?
In the agm explosives modules you could setup the skill of the specialist or the probability or encountering an unknown system. Or just give non explosive specialists a very low chance of disarming bombs with a choice to cut the correct wire.

**Comment by KoffeinFlummi** [comment]
The selection screen would be pointless, since there is no informed choice happening. Might as well just implement a random chance to blow up during disarming.

**Comment by commy2** [comment]
Nothing we can do here, sry.
