### ISSUE TITLE
agm medical player invulnerability

### ISSUE THREAD

**Issue by Drezzo** [KoffeinFlummi/AGM#1730]
agm 0941
Player becomes invulnerable after going unconscious / taking damage.
It's pretty rare but not the first time this happened.
Mission settings: 
require diagnosis
single bandage
prevent instant death
prevent death while unconscious

video:
https://mega.co.nz/#!uwcDTZJa!TSxuZVsIvlatuU17x0iMYqfmIsEREYcgfLMV8Ku0k0M

Don't know if will still be relevant with the rewrite but posting just in case.

**Comment by PabstMirror** [comment]
Made preventDamage code run only if the unit would have died.
Also makes sure they get knockedOut.

Tested working on LAN
