### ISSUE TITLE
Ensuring player height on movement when placing fortifications

### ISSUE THREAD

**Issue by hiiii5** [KoffeinFlummi/AGM#1736]
In its current state, when you move onto a surface above terrain level, any fortifications you are moving around remain on terrain level. A surefire way to fix this is something like:

`setPos` of fortification to player z height;
```sqf
_pos = get new position;
fortification setVectorUp surfaceNormal _pos;
```

If you plan on adding larger fortifications such as entire bunkers, I would recommend a major timer, as long as the original magazine packing time. Other possibilities are terrain texture checking to ensure sand or dirt for creating hesko barriers and other necessities.

**Comment by commy2** [comment]
\>\>https://github.com/KoffeinFlummi/AGM/issues/1937
