### ISSUE TITLE
Suppressors/flash hiders not reducing muzzle flash

### ISSUE THREAD

**Issue by RavenTactical** [KoffeinFlummi/AGM#1772]
As the title says, I'm looking to confirm suppressors and flash hiders are working properly.  Currently, using a suppressed weapon at night seems to generate a lot of light.  Casual inspection of the differences between suppressed and unsuppressed fire shows only marginal difference, possibly placebo effect on user.

Testing and inspection of agm_ballistics.pbo show that the visiblefire and audiblefire effects are still really reasonable; the AI still behave appropriately.

Expected: No muzzle flash/ dramatically reduced muzzle flash when firing weapons with suppressor
Results: Muzzle flash appears to be only marginally altered (if at all).
Steps to reproduce: Load AGM & CBA.  Load editor, set player as any kit with suppressed weapons at night, shoot to test, remove suppressor, shoot to test.
Recommendation: Assuming we have any control over this, reducing the suppressed muzzle flash effect by several orders of magnitude would at least give the impression of agency over the visual report of a weapon's firing.

Thanks for your time, gents.  Let me know if I can be of any help.

**Comment by commy2** [comment]
Can't do anything about this. Engine limitation.
