### ISSUE TITLE
G-Force effect maybe overdone

### ISSUE THREAD

**Issue by Crielaard** [KoffeinFlummi/AGM#1774]
To start with, the problem for me here is I can't read the G's anywhere, so I may be wrong.

It seems to me that the theoretical G-tollerence scripted in AGM is taken litterally. Whick may seem OK but when taking it to the game and compared to what one experiences in real life, is a bit exhagurated.
I'm a (Former) Airforce pilot and aerobatics pilot / Instructor so I'm talking from experience 

An avarage untrained person can potentially resist 3G's while in relaxed state. Fewer can get up to 5 G's in relaxed state without getting the grey- black-out and G-loc.
Someone untrained but still 'fighting' can extend that 0.5 to even 1G.
Someone with just 5 minutes of briefing and 'dry' practice can easily extend his G-tollerance by 2.
Not to mention what one can handle with propper training and a G-suit.

Is there any way I can get the G-Values or, better yet, get AGM's settings so I can advice a more realistic setting?

**Comment by Crielaard** [comment]
Ok srry for the delay. Here some more test results:

In version 0.95
Flying a jet with pilot class and in a pilot suit

I really still feel like Im playing someone that has never flown in his life, is totally relaxed in the aircraft and has a very low natural G tolerance.
My post with my original data still applies. It may have been tweaked allready in the higher G regions but it still kicks in far to early. Especially for a character that is a 'pilot' class and wearing a G-suit.

The cam shake is something I do like! It seems to kick in on 2G however. I'd say set it to 2,5 or 3.

**Comment by Crielaard** [comment]
Any progress here?

This graph may be interesting for you guys.https://www.dropbox.com/s/2shwtlya2qcngdw/Gtolerance.jpg?dl=0

**Comment by esteldunedain** [comment]
Not yet @Crielaard, but that graph is phenomenal. I'll try to get as close to that as possible, although the dependence on duration is a bit hard to do.

**Comment by esteldunedain** [comment]
I assume that is for people with training but wothout g-suit, right?

**Comment by Crielaard** [comment]
No! This is in fact for the Avarage Joe, without training and without a G-suit.
Do you now see why I say the G force effects are overdone? ;)

2 to 4G really aint THAT bad. Its more an overwhelming sensation you get used to rather than actaully blacking out. starting from 5 is where trouble kicks in. And 7+ physiclly hurts.
Weaker people may Gloc a 4 but some fortunate people Gloc only at 6 or more....I saw a guy doing 9 and he didnt even relise it. (Very rare case though)

Training and Gsuits basically slides the whole graph upwards, as a result of increased tollerance:
Basic training (single theoretical session and practical demo flight) +0.5 - +1.0G
500 hours experience. +3 G
Dedicated AGSM training. +1 - +2G
G-Suit +1.5 G

Endurance is a factor aswell. G forces wear you out. After a 5 minute dogfight, you feel like you've been kicking and punching a boxing ball for 5 minutes straight. So maybe you can script that in?

Negative G forces are virtually untrainable and the human body is far less resistant to it. -1G is un confortable. -2 Gives you a headach and -3 gives you a red-out in less than 10 seconds. Not to mention the popped bloodveins in your eyes...

**Comment by esteldunedain** [comment]
ok, nice rundown. I'll try to represent that as closely as I can

**Comment by esteldunedain** [comment]
I've being working an the code will get commited soon. Here is how blackouts will look in game compared to the chart provided by @Crielaard:

![image](https://cloud.githubusercontent.com/assets/7674951/5789088/d568c9e8-9e3a-11e4-8bb8-d9f8bc186d32.png)

![image](https://cloud.githubusercontent.com/assets/7674951/5789089/d9ebcef2-9e3a-11e4-93c5-9c9e898ad99e.png)

![image](https://cloud.githubusercontent.com/assets/7674951/5789092/e5aaa934-9e3a-11e4-9c11-730e527b7397.png)

So:

### For untrained people without g-suits:
- GLOC: 5G for 6 s
- RedOut: 2.5G for 6 s

### For trained jet pilots without g-suits:
- GLOC: 9G for 6 s
- RedOut: 4.5G

### For trained jet pilots with g-suits:
- GLOC: 10.5G for 6 s
- RedOut: 4.5G

**Comment by Crielaard** [comment]
Looking forward to test this! :dancers:

**Comment by esteldunedain** [comment]
:+1:?

**Comment by jonpas** [comment]
Is this something to be applied to AGM Compatibility as well, GForces for Pilot suits of mods? Or do you think most inherit properly from vanilla pilot uniforms and soldiers (is there some property that is there only for them)?

**Comment by commy2** [comment]
definitely on the list for compatibility

**Comment by jonpas** [comment]
Thought so, in that case whoever can edit first posts of issues, add it to both RHS issues and I guess IFA3 and possibly BWMod... you would know more.

**Comment by esteldunedain** [comment]
I've commited the changes I described above. Thanks again @Crielaard for the feedback.

------------

@jonpas, from a Compat POV, the only change is that I had to lower the g-force coeficient for trained pilots: https://github.com/KoffeinFlummi/AGM/commit/3218399b5788727a079423d28af0c12200d1eb2f#diff-4251f1371fe5e499253591df15b0aae6R46

If mods don't inherit from vanilla pilot is important to add these coefficient. Now there's substancially more difference between pilots and non-pilots (who easily gloc on jets), so ensuring plane pilots have the coeficient is important. Helicopter pilots are more safe, as I found very difficult to gloc on choppers (even for non-pilots) due to their much lower velocities (at least on the littlebird).

**Comment by jonpas** [comment]
That's awesome, I guess other classes connected with aerial things all inherit from those 3 pilots in vanilla? For example Helicopter Crew.

Also, can I get a line how to extract the AGM_GForceCoef of the currently controlled unit from the config?

**Comment by Crielaard** [comment]
I was just thinking today to make a G-suit as a vest. Which it is kind of, IRL.
Maybe make it part of the AGM mod and get rid of the fact wearing a certain coverall type makes you more G-tollerant?

http://i13.photobucket.com/albums/a255/MARKHITCOM/flight%20gear/G_pant_1.jpg

In the picture you can see its a pants which goes over your flightsuit.
Optionally the pilot wears a lifejacket.
Im just not sure wether a vest would work with the character's legs. Would I be wasting time on this?

**Comment by jonpas** [comment]
@esteldunedain 
> Also, can I get a line how to extract the AGM_GForceCoef of the currently controlled unit from the config? I believe it might be easier to just load in with those pilot units from mods and check if it inherits the actual property.

**Comment by esteldunedain** [comment]
Sure. 

For the coefficient related to the pilot class:
`getNumber (configFile >> "CfgVehicles" >> (typeOf AGM_player) >> "AGM_GForceCoef")`

For the coefficient related to the g suit:
`getNumber (configFile >> "CfgWeapons" >> (uniform AGM_player) >> "AGM_GForceCoef")`

**Comment by esteldunedain** [comment]
@Crielaard, I don't think you can get vests to animate correctly following the legs

**Comment by KoffeinFlummi** [comment]
> @Crielaard, I don't think you can get vests to animate correctly following the legs

You can. Although I certainly won't do the weighting. I have enough of that for a lifetime.

**Comment by esteldunedain** [comment]
Let me refrase then: 

I don't think you can get vests to animate correctly following the legs *without loosing your sanity*

**Comment by KoffeinFlummi** [comment]
![](http://puu.sh/f6Um7/6caeb2f50a.png)

I still have nightmares...

**Comment by jonpas** [comment]
Cheers, thank you! I'll do some testing with RHS and any other mods I might come across, will posts results in AGM Compatibility.

And now I am not going to do modelling in Arma... ever. :P
