### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by bux578** [KoffeinFlummi/AGM#1775]
What:
- http://en.wikipedia.org/wiki/Continuous_integration

Software (OSS License available):
- https://www.atlassian.com/software/bamboo
- https://www.jetbrains.com/teamcity/

---

Each commit:
- [ ] Update Stringtable Status
- [ ] Update Test Server

Nightly:
- [ ] Provide Nightly Builds

**Comment by diesel955** [comment]
I can also highly recommend http://jenkins-ci.org/ . It is free, open-source and if anyone could over a server instance we could configure e.g. two jobs, one for "provide nightly builds", e.g. by executing the packager script and offering the download (or uploading it again to github?), and one to "update test server". I am not sure about your definition of "update test server". I would understand there should be a server running arma3, especially an instance reserved for AGM testing and one could either connect manually to that instance and test out new stuff. What I also already did for testing a script automatically is to auto-start a server and client on a mission which has automatic execution of test cases as sqf scripts, e.g. like the following in init.sqf for ArmA2 for a script with one person interacting on the other:
```
waitUntil {time > 0}; // after briefing
if (local person1) then {
	["local person1, starting test", "init_player", [true, true, true]] call CBA_fnc_debug;
	[] spawn test_case1_person1;
};
if (local person2) then {
//	["local person2, starting test", "init_player", [true, true, true]] call CBA_fnc_debug;
	[] spawn test_case1_person2;
};
```
where "test_case1_person1" and "test_case1_person2" are functions defined to simulate the actions that one and the other persons would do. Everything can be done by script, e.g. move person1 to person2, call "interact" by script on person2, select action, observe correct result.

Also, the logfiles could be parsed for new error messages, expected test results and save in a tracing log what was executed in test runs.
