### ISSUE TITLE
AGM_Scopes Problem

### ISSUE THREAD

**Issue by scooterperpetual** [KoffeinFlummi/AGM#1810]
I am having a problem with AGM_Scopes sometimes the option to change the ranging via mils appears but sometimes it doesnt. I am not sure what is causing the problem or if only certain scopes/rifles work with the mod. Also this is more of a derp question but how do you adjust the windage.

**Comment by commy2** [comment]
Closing, see https://github.com/KoffeinFlummi/AGM/issues/1882
