### ISSUE TITLE
Fast Rope Glitch?

### ISSUE THREAD

**Issue by Backblast** [KoffeinFlummi/AGM#1811]
Can deploy and cut ropes fine. When I select fast rope my character starts the decent, starts to spaz out and falls off the rope, dying before it hits the ground. Almost like it's being affected by the downwash of the helicopter. But yeah, happens every time, dead before I hit the ground.

**Comment by bux578** [comment]
Like this: http://youtu.be/UBlJSHe7YC8 ?

**Comment by Backblast** [comment]
Yeah that's the one.

Deploying at 25 metres or less has worked, with a human pilot that is,
although a couple of times they still did the stiff body spin like they
were holding onto the rope by their ankles, which was a bit unnerving,
however we suffered no damage on the insert. The pilot later said that one
of the ropes might have been caught on something, causing the crazy decent.

**Comment by jonpas** [comment]
I can confirm the above. When ropes get stuck in something then you descent on your ankles, but I never died or got hurt because of it, as long as it was less than 35m trip.

Looks like the helper dummy object is on the ankles as well, not sure if that's possible to change, @KoffeinFlummi ?

**Comment by Backblast** [comment]
Had a new one. Again probably as a consequence of dragging the ropes over
obstacles, had a bunch of ppl fast rope down, land safely, and get stuck in
the animation. It seems unless everything is deployed perfectly things go a
bit sketchy.

**Comment by KoffeinFlummi** [comment]
Reduced the wobbling, the other stuff cannot be fixed right now due to the way the ropes work.
