### ISSUE TITLE
Merkava with BWMod classname

### ISSUE THREAD

**Issue by BaerMitUmlaut** [KoffeinFlummi/AGM#1815]
There's a third Merkava now with the classname "BWA3_Leopard2A6M_Fleck". Only using AGM 0.95 and CBA.

![2014-12-22_00002](https://cloud.githubusercontent.com/assets/9693842/5525557/3a57ff2a-89e8-11e4-9b54-bf0de8fd6f42.jpg)

**Comment by commy2** [comment]
Requires BWMod v1.2

**Comment by BaerMitUmlaut** [comment]
This was without having anything from BWMod launched?

**Comment by commy2** [comment]
Yes.

**Comment by bux578** [comment]
Probably this:
https://github.com/KoffeinFlummi/AGM/blob/1e8e1a084ed5936957cc398a20cf5b9aadd440e7/AGM_Armour/config.cpp#L205-L211

**Comment by commy2** [comment]
We made some stupid mistakes last year when we made the inheritance of the BW units. We'll change those once BW v1.2 is released.
Flummi said he's gonna remove this:
https://github.com/KoffeinFlummi/AGM/blob/1e8e1a084ed5936957cc398a20cf5b9aadd440e7/AGM_Armour/config.cpp#L205-L211
for v0.95.1
