### ISSUE TITLE
Possibility to limit number of times a vehicle can be repaired

### ISSUE THREAD

**Issue by L0rn1x** [KoffeinFlummi/AGM#1821]
In our missions we use a script that allows field repair only for a limited number of times, often only one or two. You can always repair vehicles in base.

I think this could be riproduced with AGM in three modes:

1) An option in the repair module to specify how many hard repairs are allowed (for every single part or for the total). A command to reset the counter when you repair in base.

2) Create spareparts for all hard repairs in a vehicle, so i can decide what a player can repairs and how many times. When you repair in base simply a player can choose form a box which parts put in the vehicle.

3) You can do a hard repair only if you have a Toolkit, but the Toolkit is erased when the part is repaired. So to repair an helicopter you need six Toolkits. A player can fill the vehicle with Toolkits in base like 2)

**Comment by commy2** [comment]
Nope. Don't like the idea of this.
