### ISSUE TITLE
Any medical treatment/diagnosis not available in a vehicle.

### ISSUE THREAD

**Issue by BARASOAP** [KoffeinFlummi/AGM#1824]
All options for medical when interacting when another are canceled. Regardless of medical settings.

**Comment by KoffeinFlummi** [comment]
Should be done, by some quick testing it should work, but it might require some more testing in different circumstances (people dying in vehicles, outside of vehicles etc.)

**Comment by KoffeinFlummi** [comment]
Assuming fixed.
