### ISSUE TITLE
Building "better" fortifications when there are supplies around

### ISSUE THREAD

**Issue by Przemro** [KoffeinFlummi/AGM#1841]
Idea taken from ProjectReality for BF2, in AGM you have boxes with sandbags etc. so maybe if you have like 4 boxes next to you, you could build small bunker? And if you have more boxes you can build bigger fortifications but it also take more time.

**Comment by Pakislav2** [comment]
I'd suggest giving Bobcat a use, by allowing that vehicle to build H-Barriers and bunkers using generic 'fortifications supplies'.

**Comment by commy2** [comment]
\>\>https://github.com/KoffeinFlummi/AGM/issues/1937
