### ISSUE TITLE
Fast rope bug ?

### ISSUE THREAD

**Issue by JinougaF** [KoffeinFlummi/AGM#1843]
I know the length of the rope is 35M and I made the pilot to hover at about 20M then I deploy the rope.Then I click Fast Rope in the menu,after about 10M slided with the rope then I disconnected with the rope and fell to the ground and injured

I tried several times and everytime I dropped and injured

**Comment by kripto202** [comment]
has anyone got a bug where you would be stuck in the animation of fast roping while everyone else could see you fine?

**Comment by jonpas** [comment]
>So in theory the pilot might actually be able to leave the cockpit and fastrope out of it while it is still hovering.

I tried that, got it to stable hover and all, fast-roped but the engine turned off, because Arma. If fast-rope would eject you out then it might even work.

**Comment by BaerMitUmlaut** [comment]
I actually meant that it might be possible in real life - not that it would be a particularly great idea.

**Comment by jonpas** [comment]
Yep I know and I was just saying what actually happens in Arma.

**Comment by Grubbyseismic** [comment]
While inserted into the "Patrol Maps" user-created scenario: we can't get fast rope to work at all!

**Comment by BaerMitUmlaut** [comment]
Do you mean you can't get the option to fast rope? Which helicopter were you using?

**Comment by KoffeinFlummi** [comment]
Closing in favour of #1811.
