### ISSUE TITLE
AI unconscious as gunner in offroad issue

### ISSUE THREAD

**Issue by evromalarkey** [KoffeinFlummi/AGM#1854]
AI keeps shooting as gunner in offroad even when he falls unconscious. This may happen with all vehicles with gunner positions.

**Comment by KoffeinFlummi** [comment]
Kill them when they would be falling unconscious or let them live?

**Comment by bux578** [comment]
Kill! Blood for the blood god!

**Comment by commy2** [comment]
Unconscious drivers also keep driving.

**Comment by KoffeinFlummi** [comment]
See https://github.com/KoffeinFlummi/AGM/commit/8b9cb5fc824e0428422df8e5b9e599c54ee9b49e#commitcomment-9202792
