### ISSUE TITLE
When injured in multiple places, you can bandage yourself with one bandage

### ISSUE THREAD

**Issue by evromalarkey** [KoffeinFlummi/AGM#1855]
*Version:* **0.95**

*AGM Module settings:*
Require diagnostic: **Off**
One bandage: **Off**
Prevent insta death: **On**
Prevent death while unconscious: **Off**

*Steps to repro:* Try to get injured by AI and when you have more then one injury, you should be able to bandage one and that will bandage all. Happens with normal injuries and also with heavy injuries.

Tested on dedicated server.

**Comment by l4ndl0rd** [comment]
Can confirm this as well,  plus one only seems to be able to patch a fellow player up once he has regained consciousness, otherwise all that can be done seems to be to diagnose (tested with both medic and non-medic).

**Comment by esteldunedain** [comment]
@KoffeinFlummi, the problem seems to be related to fn_checkDamage:

https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Medical/functions/fn_checkDamage.sqf#L46-L54

That is called after bandaging any body part, and typically it heals the rests automatically; is that simply supposed to be 

```
if (_damagesum <= 0.06) then {
  _unit setDamage 0;
};
```

instead of `>=` ???

**Comment by KoffeinFlummi** [comment]
Woops.

**Comment by PabstMirror** [comment]
Shot in right arm, right leg.
Diagnose says light dmg - arm, heavy in leg

CheckDmg1 is top of checkDamage, CheckDmg2 is at end

```
13:16:00 [AGM] Debug: AGM_Medical : 59543 - AGM_Debug_fnc_log : before heal right arm:[B Alpha 2-1:1], Head[0], Bod[0], R-A[0.397697] L-A[0] Hands[0] R-L[1] L-L[0] Legs[1]
13:16:12 [AGM] Debug: AGM_Medical : 61241 - AGM_Medical_fnc_checkDamage : CheckDmg1:[B Alpha 2-1:1], Head[0], Bod[0], R-A[0] L-A[0] Hands[0.199256] R-L[1] L-L[0] Legs[0.199256]
13:16:12 [AGM] Debug: AGM_Medical : 61241 - AGM_Medical_fnc_checkDamage : CheckDmg2:[B Alpha 2-1:1], Head[0], Bod[0], R-A[0] L-A[0] Hands[0] R-L[0] L-L[0] Legs[0]
```

**Comment by esteldunedain** [comment]
Confirmed working

**Comment by commy2** [comment]
:+1:

**Comment by evromalarkey** [comment]
now is this really fixed? I Just got the same issue on the server with 0.95.1

**Comment by esteldunedain** [comment]
are you using PlayWithSix?

**Comment by evromalarkey** [comment]
yeah, but I checked the version and it's 0.95.1

**Comment by esteldunedain** [comment]
Keep in mind that PWS apparently lists AGM 0.95 as AGM 0.9.5.1 (with an extra dot), causing widespread confusion. Could you please double-check what version you have installed?

**Comment by evromalarkey** [comment]
I know, but I tell them to fix that yesterday, so they have correct version now. I compared the files and it's for sure 0.95.1

**Comment by esteldunedain** [comment]
The server might have been in 0.95 though, hence the error.

Unfortunately you can connect to 0.95 servers with 0.95.1.

**Comment by evromalarkey** [comment]
will check that, but I think I updated it too

**Comment by evromalarkey** [comment]
nope, server has also 0.95.1

**Comment by evromalarkey** [comment]
Never mind it doesn't seems to be related with multiple injuries on one bandage. Related - #1971
