### ISSUE TITLE
continuous cook off sound after tabbing out

### ISSUE THREAD

**Issue by commy2** [KoffeinFlummi/AGM#1857]
`createSoundSource` is bugged. Tabbing out after `deleteVehicle` 'ing creates a sound that is attached to the player, but plays at a distance to the old position of a deleted sound source. It never ends and only tabbing out again updates the position.
~~Solution might be to teleport the sound source to -10000,-10000 before deleting it.~~

There is a ticket on the feedback tracker about this somewhere iirc.

Edit: The potential work around doesn't work... Seems like `createSoundSource` is broken for good.

**Comment by KoffeinFlummi** [comment]
Working as well as can be, considering the issue.
