### ISSUE TITLE
Unloading items on the LHD (height > 0)

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#1861]
Unloading AGM items on the LHD (probably Nimitz and similar as well) is not possible, the object will always be at height 0, underwater. Any possibility this could get changed/fixed?

v0.95

**Comment by commy2** [comment]
Needs testing.

**Comment by jonpas** [comment]
Will do when I get back home,

**Comment by jonpas** [comment]
Nope, on LHD it still unloads on the sea surface.

**Comment by BaerMitUmlaut** [comment]
I put a comment on that commit, pretty sure line 22 is the issue.

**Comment by PabstMirror** [comment]
```
_position set [2, ((getPosASL player) select 2)];
_item setPosASL _position;
```
Worked pretty good, except one time I took torso damage when unloading wheel

**Comment by commy2** [comment]
Sry, can't test right now. Does it work now?

**Comment by esteldunedain** [comment]
@PabstMirror gets the prize

**Comment by jonpas** [comment]
Good job!
