### ISSUE TITLE
None of these AGM functions seem to work. Why?

### ISSUE THREAD

**Issue by wanderrful** [KoffeinFlummi/AGM#1877]
The following code is run in the initServer.sqf file for one of my missions (so, everything below is being run by the server's machine only):

```sqf
[hostage, "HitLeftLeg", 0.8] call AGM_Medical_fnc_setHitPointDamage;
[hostage, "HitRightLeg", 0.8] call AGM_Medical_fnc_setHitPointDamage;
[
	[
		hostage,  //hostage is of course properly defined in the mission.sqm
		"wokeUp",
		{
			[hostage, (300*60)] spawn AGM_Medical_fnc_knockOut;
			hint "Usingan Epipen to the hostage is cheating.  You're supposed to carry/drag him to the extraction zone...";
		}
	],
	"AGM_Core_fnc_addCustomEventHandler",
	hostage
] spawn AGM_Core_fnc_execRemoteFnc;
```

None of this seems to actually work even though I'm 99% sure that I've followed the AGM/Wiki's syntax properly.

When I start up the mission and Diagnose the hostage, he is completely uninjured.
The most important part, though: is that the event doesn't even work!

Originally I tried running the addCustomEventHandler on its own without bothering to use the execRemoteFnc... but that also didn't work either, sadly.

There must be some simple explanation for this and it's probably my fault.  I just need someone to tell me what's wrong here.

Thanks ahead of time.

**Comment by PabstMirror** [comment]
reverted changes to wiki

code and wiki now match, neither have the `AGM_` prefix
