### ISSUE TITLE
Why {} in IFs and conditions?

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#1879]
This is totally a question, but I am really wondering why are all the IFs and conditions in AGM's code in {} after || or &&?

**Comment by esteldunedain** [comment]
Lazy evaluation:

https://community.bistudio.com/wiki/Code_Optimisation

**Comment by esteldunedain** [comment]
That was probably a lazy answer. In a nutshell, when you set a condition between {} it is only evaluated if necessary, giving a slight performance increase. If one of the earlier condition fails the lazy conditions don't need to be evaluated at all.

**Comment by jonpas** [comment]
Ah, very nice, thank you for that! Basically, if I understand that wiki page you linked where it talks about that lazy evaluation can also be slower, it's better if you set the first condition to be more likely true than false, looking at the examples given if the first condition returns false it will then need longer to process the lazy evaluation ones.

**Comment by esteldunedain** [comment]
> it's better if you set the first condition to be more likely true than false, looking at the examples given if the first condition returns false it will then need longer to process the lazy evaluation ones.

That's only true if you have a multiple `||`, but the exact opposite is the best when you have a multiple `&&` (for those it's best to have the first argument be the most likely false)

**Comment by jonpas** [comment]
Makes sense, thanks for explanation!
