### ISSUE TITLE
scripterror on passing out

### ISSUE THREAD

**Issue by Drezzo** [KoffeinFlummi/AGM#1881]
AGM dev:

When going unconscious by myself, didn't happen when I was shot and went unconscious:

Error in expression <ocal (_this select 0)) then {_this call AGM_Captives_fnc_handleKockedOut};
}] ca>
 0:11:10   Error position: <AGM_Captives_fnc_handleKockedOut};
}] ca>
 0:11:10   Error Undefined variable in expression: agm_captives_fnc_handlekockedout
 0:11:10 File AGM_Captives\functions\fn_initUnit.sqf, line 4

rpt: http://pastebin.com/VQNt5kSr

Misspell of agm_captives_fnc_handlekockedout?

**Comment by PabstMirror** [comment]
When I fixed the eventName it started using code with bad name, should be fixed now.

**Comment by esteldunedain** [comment]
Dual fix!

**Comment by PabstMirror** [comment]
I don't think anything was calling Scopes/clientInit before this.

Now I get:

```
19:05:56 Error in expression <5; cameraView == "GUNNER"};
if !(isNull AGM_Scopes_fadeScript) then {
terminate >
19:05:56   Error position: <AGM_Scopes_fadeScript) then {
terminate >
19:05:56   Error Undefined variable in expression: agm_scopes_fadescript
19:05:56 File AGM_Scopes\clientInit.sqf, line 33
```
