### ISSUE TITLE
Script AGM_SafeMode\clientInit.sqf not found

### ISSUE THREAD

**Issue by Drezzo** [KoffeinFlummi/AGM#1882]
agm dev

When not using the safemode module

**Comment by esteldunedain** [comment]
Thanks. It was an error on recent changes to AGM_Scopes to make it zeus compatible.

**Comment by PabstMirror** [comment]
I don't think anything was calling Scopes/clientInit before this.

Now I get:

```
19:05:56 Error in expression <5; cameraView == "GUNNER"};
if !(isNull AGM_Scopes_fadeScript) then {
terminate >
19:05:56   Error position: <AGM_Scopes_fadeScript) then {
terminate >
19:05:56   Error Undefined variable in expression: agm_scopes_fadescript
19:05:56 File AGM_Scopes\clientInit.sqf, line 33
```

**Comment by esteldunedain** [comment]
Yes, that was clearly overlooked because the code was not being called. I think we better tag commy to fix that,

**Comment by esteldunedain** [comment]
I think the error causing this is the deletion of this line:

https://github.com/KoffeinFlummi/AGM/commit/ee9ddc18330a4d29d59eed9980145a97a3527fda#diff-e91a9825fdc4d1ed126a90b1d89e90eeL13

**Comment by commy2** [comment]
Needs testing.

**Comment by PabstMirror** [comment]
Seems to be working fine now. Closing
