### ISSUE TITLE
Is AGM_SwitchUnits functional?

### ISSUE THREAD

**Issue by captainblaffer** [KoffeinFlummi/AGM#1883]
Is AGM_SwitchUnits functional?

The guide for mission makers is not very descriptive
https://github.com/KoffeinFlummi/AGM/wiki/For-Mission-Makers

I can't get it to work. Tried MP, SP, using AI in editor, script spawned AI, play as WEST or EAST.
my RPT did report  1:42:32 [AGM]: SwitchUnits Module Initialized.

**Comment by bux578** [comment]
https://github.com/KoffeinFlummi/AGM/wiki/For-Mission-Makers#32-agm-switchunits

How is that not very descriptive?

**Comment by captainblaffer** [comment]
Oh yes! I could not find that link somehow. I could only find the part explaining the module.
It's working perfectly now. Thank you, this is awesome!
