### ISSUE TITLE
Add a way to deactivate Team management

### ISSUE THREAD

**Issue by Komodo1** [KoffeinFlummi/AGM#1884]
I'd like to deactivate team management in certain cases (determined by my mission code), but I can't find a way to achieve it except by editing the AGM code.
Does anyone have a solution? Or is this something that should be an evolution?

**Comment by commy2** [comment]
I'll add a check for a certain mission namespace variable you can set to false to disable it.

**Comment by Komodo1** [comment]
Excellent, thanks!
I think this could be useful for any default AGM functionality in case this could help other users.

**Comment by commy2** [comment]
You can now use:

`AGM_enableTeamManagement = false;`

to deactivate the team management option

Needs testing.

**Comment by esteldunedain** [comment]
> AGM_enableTeamManagement = false;

That should be set on each client you want to disable this.

Alternatively, you can set the following on any single machine or the server:

`missionNamespace setVariable ["AGM_enableTeamManagement", false, true];`

which would disable this for everyone.

**Comment by commy2** [comment]
You could also simply put it into any objects init-line or the init.sqf

**Comment by bux578** [comment]
Could this be an option in the interaction module?

**Comment by commy2** [comment]
If you want to add it.

**Comment by bux578** [comment]
Sure, assign it to me.

**Comment by Komodo1** [comment]
I'll test that asap, thanks guys!

**Comment by Komodo1** [comment]
works like a charm! might be useful for other non separated functionalities for quite heavy modules in case someone else has similar need.
Thanks for your quick fix!

**Comment by esteldunedain** [comment]
@Komodo1, glad to hear.

But, heads up:

- When #1932 is merged (might be tommorrow), the variable name will change to `AGM_Interaction_enableTeamManagement` and will have a numeric type: e.g. `AGM_Interaction_enableTeamManagement = 0;`
- When #1933 is merged (might be tommorrow or after 0.95.1) the variable will change to boolean again: `AGM_Interaction_enableTeamManagement = false;`

Sorry for the inconvenience, but that's the danger of using cutting edge stuff.

**Comment by Komodo1** [comment]
No problem, I'm not in an immediat hurry for this one, already good to know you're putting it in the next version.
Thanks again, much appreciated!

**Comment by commy2** [comment]
Now the issues are merged. So it's definitely `AGM_Interaction_enableTeamManagement = false;`

**Comment by commy2** [comment]
Confirmed working.

**Comment by Komodo1** [comment]
Great, thanks!
