### ISSUE TITLE
Add a secondary primary weapon to the launcher slot

### ISSUE THREAD

**Issue by TheSystematicPsycho** [KoffeinFlummi/AGM#1886]
The inability to have a second primary equipped has been bugging me since left arma 2 w/ ace. If it at all possible I would love to see the ability to equip a primary to your back making it visible (Physically and Inventory) and swappable similar to ace. While it is possible it just feels really weird say pulling a standalone grenade launcher out of a backpack or even a shotgun for that matter. Hopefully it would not take witchcraft to do such a thing!

**Comment by Heavygunner96** [comment]
AFAIk not possible with Arma 3.

**Comment by commy2** [comment]
Engine limitation.

Same as https://github.com/KoffeinFlummi/AGM/issues/254
