### ISSUE TITLE
AGM Repair: Cant repair Stromper Drone rear wheels

### ISSUE THREAD

**Issue by Meiestrix** [KoffeinFlummi/AGM#1887]
You cant repair the rear wheel of the Stromper drone.
Only the front and middle wheels.
https://www.dropbox.com/s/ccwxuylcl26cxho/Stomper%20repair.jpg?dl=0

**Comment by PabstMirror** [comment]
Found AGM_Interaction_fnc_AddSelectableItem was overwriting _index, so we got crazy results:

![untitled](https://cloud.githubusercontent.com/assets/9376747/5600831/0421b1b0-92aa-11e4-87c3-788eb1ccafb9.jpg)

Should be fixed in be313317c859bd9d911f77184aaea5e8ffde4208
