### ISSUE TITLE
a new crosshair ? 

### ISSUE THREAD

**Issue by Dorak** [KoffeinFlummi/AGM#1888]
Very short request. 

I personally don't play with a crosshair, but i can see the usefulness in certain scenarios, notably if you're using a TrackIR, things like that. That being said, i dislike the actual "dynamic" crosshair, which is a bit too big, too visible, and doesn't feel like a proper "indication" of where you are aiming. 

I wonder if it would be possible to get the best of both worlds, get rid of the actual crosshair, and put a simple, static dot instead. Would feel far less intrusive.

**Comment by kripto202** [comment]
you can turn off the dynamic crosshair in your game settings

**Comment by Dorak** [comment]
I'm aware of that. Thanks.

**Comment by JinougaF** [comment]
there was already a crosshair mod in ArmaHolic which bring back the Arma2 version crosshair for Arma3.So i think this could be done in the future versions of AGM.

**Comment by KoffeinFlummi** [comment]
> and doesn't feel like a proper "indication" of where you are aiming.

How so?

> which is a bit too big, too visible

These are purely subjective (I for example think it's fine the way it is), so I don't think this would be a good idea.

**Comment by kripto202** [comment]
For me the only problem I have for the crosshair is that when the sky gets really bright, you can't see that at all. If it needs to be changed, make it where the crosshair has a black border.

**Comment by Drezzo** [comment]
I'd like to see a system which allows you to see if you're going to shoot into a rock or other object when crosshairs are disabled, dot or other icon. Which is the only good thing the vanilla crosshair brought.
#571

**Comment by Dorak** [comment]
Yes, my request was indeed purely subjective Flummi. If you don't think it's a good idea, then fair enough, on the other hand, Drezzo request is interesting.

**Comment by commy2** [comment]
Out of scope. Sry.
