### ISSUE TITLE
AI Captivity.

### ISSUE THREAD

**Issue by Pakislav2** [KoffeinFlummi/AGM#1894]
1.) Add cable ties to inventory of all units.
2.) Make AI take unconscious enemies prisoner, similar to current AI medic behavior.
3.) Make captives drop all their gear on the ground, as per bCombat mods surrender feature.
3.5) Give players the ability to take items out of unconscious/captive units inventory.

More ambitious;

3.) Make the AI escort the captive to a building within ~100m and guard him there/Escort him to a place on map specified by mission makers with a custom module.
4.) Give players an ability to free themselves, should take a looong time. Makes the units guarding him as per #3 shoot/chase after the escapee.
5.) Give players an ability to knock out someone if they get close enough. Simple action on others -> knock out.

**Comment by commy2** [comment]
Closing as dup of https://github.com/KoffeinFlummi/AGM/issues/903

I C&P'd your idea to the other issue.
