### ISSUE TITLE
Remove vehicle from AGM damage system?

### ISSUE THREAD

**Issue by Kugelschieber** [KoffeinFlummi/AGM#1895]
Can I remove a vehicle from the AGM damage system, so that it doesn't start to burn?
I'm trying to reduce and calculate damage on a tank on my own, but AGM ignores my setDamage and it starts to burn after two hits from an enemy tank.

Here is the script I'm talking about: https://github.com/DeKugelschieber/ArmA3-scripts/blob/master/src/dklib/dklib/usefulTanks.sqf

**Comment by PabstMirror** [comment]
For now this should remove all effects from AGM_Armour when placed in a vehicles init

```
nul = this spawn {
	sleep 1; 
	_this removeAllEventHandlers "HandleDamage";
};
```
