### ISSUE TITLE
Player can push themselves when placing fortifications

### ISSUE THREAD

**Issue by captainblaffer** [KoffeinFlummi/AGM#1905]
hold a razorwire, rotate camera.

https://www.youtube.com/watch?v=DuqbDtwHnHM&feature=youtu.be

**Comment by commy2** [comment]
Known. No idea how to fix though.

The bug doesn't work in first person, due to limited camera movement iirc.

**Comment by captainblaffer** [comment]
Also possible to do in first person

**Comment by jonpas** [comment]
Don't the fortifications during placing have enableSimulation false?

**Comment by commy2** [comment]
Yes they do, but it doesn't stop them from pushing the player. I'm not aware of any method that does.

**Comment by BaerMitUmlaut** [comment]
Attach them to an invisible dummy so the have no hitbox?

**Comment by commy2** [comment]
It will still collide with anything that isn't attached to the same object aswell?

**Comment by BaerMitUmlaut** [comment]
I don't think so. Was happily driving through that submarine the other day...

**Comment by commy2** [comment]
Noted. I'll try it when rewriting Logistics.

**Comment by BaerMitUmlaut** [comment]
Thinking about I might be wrong or it might depend on the object, not sure, but it's worth a try I guess.

**Comment by commy2** [comment]
\>\> https://github.com/KoffeinFlummi/AGM/issues/1937
