### ISSUE TITLE
Can not cancel building fortification

### ISSUE THREAD

**Issue by captainblaffer** [KoffeinFlummi/AGM#1906]
the HUD says press right mouse button to cancel, but when I press it only my gun/camera zooms in.

'my controls: http://pastebin.com/Xb10CJSW
rpt: http://pastebin.com/RmFhuE5Q

**Comment by commy2** [comment]
You have to actually press the "menu back" action (Closes the scroll wheel menu) instead of RMB. 
Menu back defaults to RMB, but you might have changed it.

**Comment by captainblaffer** [comment]
My back button under 'common' is bound to backspace and right mouse button. Pressing those buttons (or any other button) does not cancel the fort build

**Comment by jonpas** [comment]
Try setting the key back to RMB and try then. Then try different key combinations and see if you can figure out what combo makes it break.

**Comment by commy2** [comment]
Expired.

Works for me when using the "menuBack" action. There is no way to lock that to RMB, but it's not our fault input eh are stupid.
