### ISSUE TITLE
stuck in animation in fast roping

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#1911]
When you fast rope from a heli, you would most likely get stuck in the animation while you are fast roping and you can't move. Sometimes there will be some people where they are fine but will look like they are stuck in the animation too. I'll be posting a video up soon to show what I mean.

**Comment by kripto202** [comment]
here is the video showing what happens when we fast rope http://youtu.be/lgWs3Bdkz3w

**Comment by commy2** [comment]
Can you try to reproduce this bug with a mission where you put
`AGM_Debug = ["Anim"];`
in any init-box and then upload the RPT-files?

The capitalization is important.

**Comment by kripto202** [comment]
ya just need to get someone

**Comment by kripto202** [comment]
video is being uploaded and it will be done in an hour here is the link for it http://youtu.be/XDxft_EAUoU

**Comment by kripto202** [comment]
@commy2 I hope the video helped out on what could be the problem.

**Comment by commy2** [comment]
Nope. I need the RPT files with `AGM_Debug = ["Anim"];` set in the init line.

**Comment by kripto202** [comment]
the init line for the mission?

**Comment by commy2** [comment]
Doesn't matter. Can be in any global object.

**Comment by kripto202** [comment]
I used that init on my character and the types of animations came up as a radio call on the video

**Comment by commy2** [comment]
Missed that. It's exactly the information I need from the RPT.

**Comment by commy2** [comment]
Does it work now?

**Comment by kripto202** [comment]
Ill have to check it out tomorrow when I get back from class

**Comment by kripto202** [comment]
no it doesn't work still stuck in the same animation

**Comment by commy2** [comment]
Are you on A3 dev?

**Comment by kripto202** [comment]
no, stable

**Comment by kripto202** [comment]
hold on I think I somehow didn't move the changed file over...

**Comment by kripto202** [comment]
no it still didn't work

**Comment by commy2** [comment]
RPT with `AGM_Debug = ["Anim"];` ?

**Comment by kripto202** [comment]
![2015-01-08_00001](https://cloud.githubusercontent.com/assets/8568526/5675319/65c28ce4-9789-11e4-8541-666ba19ef5a0.jpg)

**Comment by commy2** [comment]
When you are in that animation, can you fix it by executing `player switchMove ""` via debug console?

**Comment by esteldunedain** [comment]
@kripto202, hey, just checking. Are you binarizing AGM_Core as well?

**Comment by commy2** [comment]
Yes he is. Otherwise the systemChat in the screenshot would say something else.

**Comment by kripto202** [comment]
It didn't work the only way I know to fix this problem is having the player get knocked out and use a epi pen on him.

**Comment by kripto202** [comment]
also you can shoot while in the animation

**Comment by commy2** [comment]
What happens if you execute
`player switchMove "AGM_FastRoping"; player switchMove ""; systemChat "hi"`
via debug console?

**Comment by kripto202** [comment]
![2015-01-08_00002](https://cloud.githubusercontent.com/assets/8568526/5675379/d6ad4902-978a-11e4-9f1f-abebde104e77.jpg)

**Comment by kripto202** [comment]
hope we can find something my guy here really needs to take a piss...

**Comment by commy2** [comment]
No fastropeing, just executing
`player switchMove "AGM_FastRoping"; player switchMove ""; systemChat "hi"`
when standing on the ground. What happens?

**Comment by kripto202** [comment]
does the same thing as the screenshot

**Comment by esteldunedain** [comment]
It works flawlesly for me. What's the difference?

I'm on stable too. Game cache?

**Comment by commy2** [comment]
>does the same thing as the screenshot

Then you are either on (an outdated version of) Arma dev or you broke your game.

**Comment by kripto202** [comment]
going to redownload the mod from armaholic and see if it continues

**Comment by esteldunedain** [comment]
I would check the Arma 3 game cache on steam, just in case some file got corrupted.

**Comment by commy2** [comment]
I fixed the firing in roping state.

**Comment by kripto202** [comment]
It works, also you can do a reload animation while in the fast roping animation

**Comment by commy2** [comment]
What works?

**Comment by kripto202** [comment]
going back to the normal stance

**Comment by commy2** [comment]
What did you change? Also I can't fix reloading like firing, because BIS broke the config entries.

**Comment by kripto202** [comment]
I redownloaded agm. What I think happened is if you replace the old agm files with the new (copy and replace), it causes that problem.

**Comment by kripto202** [comment]
this can be closed
