### ISSUE TITLE
Add default values for backblast

### ISSUE THREAD

**Issue by esteldunedain** [KoffeinFlummi/AGM#1915]
Currently (AFAIK) backblast is non-existent unless the launcher has all the correct parameters configured. 

But anything is probably better than nothing, so at the very least I propose addopting some default values when none are available for greater compatibility of other addons. 

A more ambitious plan would be addopt default angles but correlate the backblast distance with rocket mass and velocity.

**Comment by commy2** [comment]
Thats not true

https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Backblast/config.cpp#L39

Launcher_base_F has default values.

**Comment by esteldunedain** [comment]
And all launchers have to inherit from that?

**Comment by esteldunedain** [comment]
Can we move that to `Launchers` instead? IFA3 inherits from that skipping `Launcher_base_F`

**Comment by commy2** [comment]
We could do that. The only child of Launcher is Launcher_Base_F. Although all launchers in A3 should inherit from Launcher_Base_F, because it contains some definitions all launchers should have.
