### ISSUE TITLE
AGM Spectatormode

### ISSUE THREAD

**Issue by Trigger81** [KoffeinFlummi/AGM#1919]
Spectatormode with Support AGM- Medic- System, Name Tags, ACRE/ TFAR and so on like the Spectatormode in ArmA II ACE for example 

https://www.youtube.com/watch?v=BpG0ToakoGQ

**Comment by Tachii** [comment]
Would be rly nice

**Comment by esteldunedain** [comment]
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/1099

Sorry guys, none of us is interested on programming this at the moment. There are already a couple of good alternatives out there. Of course, if anyone codes or donates one we will consider it for inclusion.

Cheers

**Comment by Trigger81** [comment]
ohh sorry for duplicate .. shame on me
