### ISSUE TITLE
HMG/Vehicle/Static ammo

### ISSUE THREAD

**Issue by jones140** [KoffeinFlummi/AGM#1923]
i had  a bit of idea about reloading vehicles alot of the A3 vehicles use the same ammo types and same so with static weapons at the moment the arma3 rearm system is look at something get ammo and feels disjointing from AT/AA weapons getting rockets from ammo boxes reloading ect

idea of possible models seeing as a3 included these
http://i.imgur.com/P31YsN4.jpg
maybe for static agm interact "Load ammo" will load from inventory or ground 

maybe adding HMG GMG ammo to Ammo trucks Mortar rounds smoke rounds ect

anyway food for thought

**Comment by commy2** [comment]
\>\>https://github.com/KoffeinFlummi/AGM/issues/1937
