### ISSUE TITLE
Is that possible to drag a damage vehicle with a intact one?

### ISSUE THREAD

**Issue by JinougaF** [KoffeinFlummi/AGM#1928]
When a vehicle is damage and can't move(not destroyed),a intact one could drag it out of the danger in the real life.Vehicles are valuable equipments and should not easily be abandoned.And there are some situations you can't repair them during fire fight and you may need others to drag them out of the warzone and repair them later.

Thought the feature would be useful.

**Comment by PabstMirror** [comment]
Pretty much #8 - towing system

Rope physics in arma still aren't great. if you try dragging a vehicle it has tendency to flip over

**Comment by JinougaF** [comment]
Another way is to make a specific kind of vehicle to have a towing system,like the repair truck or that engineering armor(forgot its name).

**Comment by KoffeinFlummi** [comment]
Closing because duplicate.
