### ISSUE TITLE
Use setBleedingRemaining when unit is bleeding

### ISSUE THREAD

**Issue by BaerMitUmlaut** [KoffeinFlummi/AGM#1939]
You could use setBleedingRemaining as a visual indicator that somebody else is bleeding and set it to 0 once the unit is bandaged. I'm not sure if it has to be synched in MP or if that's done automatically.

Btw, is there any way to contribute directly or would I have to fork AGM?

**Comment by bux578** [comment]
> Btw, is there any way to contribute directly or would I have to fork AGM?

Fork

**Comment by BaerMitUmlaut** [comment]
kthx

**Comment by commy2** [comment]
>> https://github.com/KoffeinFlummi/AGM/pull/1940
