### ISSUE TITLE
ASR AI incompatible with AGM_Hearing

### ISSUE THREAD

**Issue by OnkelDisMaster** [KoffeinFlummi/AGM#1941]
When I use ASR:AI AGM_Hearing is getting bugged. The G36 from the BWMod is causing ear ringing, and Toadies AK´s do either. When completely disabling ASR:AI, everything works fine. I have already tried to set "gonshothearing = 0" in the userconfig of ASR, but theres no change.

**Comment by esteldunedain** [comment]
ASR:AI greatly increasese the `audibleFire` parameter of most bullets (how loud they are) to make AI hear them better. This causes ear ringing, because AGM_Hearing uses that same paramenter to calculate hearing loss effects.

Sorry, there's nothing we can do about this.

**Comment by PabstMirror** [comment]
I believe the new version of ASR only needs to be run server side (and will still effect AI on any machine) - check the new asr_ai3_settings.hpp:

`setskills = 2;                 // Override AI skills based on their unit type (faction, training etc.; 0 - disabled, 1 - server only, 2 - setskill everywhere)`

**Comment by jonpas** [comment]
It's still recommended to run it on every machine though, if you run what you posted server only than only that skill will get set everywhere, but all other features only on AI on the the dedicated, which is not feasible if you want to run Headless Client or using Zeus.

**Comment by commy2** [comment]
Why would they mess with `audibleFire`? Stupid idea and probably doesn't help them at all.

> if you want to run Headless Client

Then have the mod run on the HC aswell.

> or using Zeus.

Then ... Fucking zeus.

**Comment by esteldunedain** [comment]
Zeus units are local to Zeus? Are you sure they are not spawned on the server?

**Comment by jonpas** [comment]
Yes, commy, I know that, but read the comment above mine, the idea was to run it only server-side and then audibleFire wouldn't change for players, that's why I commented what I commented...

Yes 100% sure, Zeus acts similar to a Headless Client actually, that's why I hate it.

**Comment by commy2** [comment]
Zeus units are created via `createUnit`, so they are local to the zeus client.

**Comment by esteldunedain** [comment]
> Zeus units are created via createUnit, so they are local to the zeus client.

I didn't know that. That's baaaad for performance reasons. I guess utilities to transfer them to the server after creation, right?

**Comment by jonpas** [comment]
Well in short, no, at least I don't know of any. Doing setOwner breaks all waypoints and everything about it and event handlers for Zeus aren't sufficient I believe. If there is a way I'd like to hear it though.

**Comment by esteldunedain** [comment]
Apparently you can create units in the server and then use the addCuratorEditableObjects to make them controlable by any number of Zeuses. The fact that the same unit can be controlled by more than one curator means that they probably don't switch locality while controlling them. 

I didn't test any of this yet, but if this works it should give much better performance on dedicated servers.

**Comment by jonpas** [comment]
How can you create units on the server with Zeus interface? I know it works very very well if you just spawn all on server and then use a script to add them (we used Fett's script, Ares mod does similar with a Zeus module). But no spawning on server via Zeus interface.

**Comment by esteldunedain** [comment]
Actually the Ares guy is experimenting on ways to transfer units back to server (https://github.com/astruyk/Ares/issues/159). But I'm thinking on the possibility of adding a command in Ares to clone the selected unit on server and then delete the former one.

It could work like this:
1- You create units on zeus
2- You use that eventual ares command to:
  - Create a similar unit on the server
  - Add it to Zeus control using addCuratorEditableObjects
  - Delete the original unit
3 - Then give orders as usual.

**Comment by jonpas** [comment]
That is exactly what [AI Caching and Distribution script](http://forums.bistudio.com/showthread.php?170539-AI-Caching-and-Distribution-System) does. During mission init it removes all AI from the Dedicated Server and creates new ones on Headless Client. Sadly it doesn't work dynamically and you can't do it during the mission. I'll post this in the Ares issue as well, might help them out, that AI script we use is open-sourced on GitHub as well.

**Comment by jonpas** [comment]
That's exactly what the [AI Caching and Distribution script](http://forums.bistudio.com/showthread.php?170539-AI-Caching-and-Distribution-System) does. During mission init it removes all AI from the Dedicated Server and creates new ones on Headless Client. Sadly it doesn't work dynamically and you can't do it during the mission. I'll post this in the Ares issue as well, might help them out, that AI script we use is open-sourced on GitHub as well.

**Comment by esteldunedain** [comment]
> That is exactly what AI Caching and Distribution script does. During mission init it removes all AI from the Dedicated Server and creates new ones on Headless Client. Sadly

But transfering units from server to client is possible using setOwner! The other way around is what doesn't work

**Comment by jonpas** [comment]
Yes but using setOwner in any way will remove all the waypoints and scripts associated with the unit moved to client. So it's still a no pretty much.

**Comment by bux578** [comment]
> But transfering units from server to client is possible using setOwner! The other way around is what doesn't work

I'm using something similar to return a switched unit back to the server and it' working. The server has to call `setOwner`.
https://github.com/KoffeinFlummi/AGM/blob/master/AGM_SwitchUnits/functions/fn_switchUnit.sqf#L49

**Comment by esteldunedain** [comment]
Are you sure that works? The concensus online it's that `setOwner` can only transfer units from server to client but not the other way around (e.g. https://community.bistudio.com/wiki/setOwner).

**Comment by bux578** [comment]
The `owner` did change, when I executed it on the server.

**Comment by commy2** [comment]
>The concensus online it's that setOwner can only transfer units from server to client but not the other way around

Thats not true. The server has a client ID aswell (Most of the time 0, but supposedly not always)

It's just that this command only works when executed on the server.
