### ISSUE TITLE
Make inventory UI size toggleable in the AGM menu?

### ISSUE THREAD

**Issue by Gruntin** [KoffeinFlummi/AGM#1946]
Instead of it's own module, could it be made toggleable in the menu?

**Comment by jonpas** [comment]
No, it's config change, config changes cannot be changed after game launch.

**Comment by PabstMirror** [comment]
It might be able to be done dynamically, with a a lot of `ctrlSetPosition`
I can take a look to see if feasible (note: double check AGM_Disposable)

**Comment by commy2** [comment]
>It might be able to be done dynamically, with a a lot of ctrlSetPosition

Pls no.

Just delete the PBO. It's unfortunately based on config changes and therefore can't be toggled while the game is running. Sry.
