### ISSUE TITLE
Safemode error, stringtable exchanged

### ISSUE THREAD

**Issue by Legolasindar** [KoffeinFlummi/AGM#1947]
I think the ID "STR_AGM_SafeMode_SafeMode" and "STR_AGM_SafeMode_PutOnSafety" are exchanged "interchanged". When i put the safe mode, appear the message of "STR_AGM_SafeMode_PutOnSafety". It may be a translation error, but I think in English is the same.

I used 0.95 version, not Dev version.

**Comment by Legolasindar** [comment]
Any clarify about this? I need know if are addon error or my translation error.

**Comment by jonpas** [comment]
https://github.com/KoffeinFlummi/AGM/blob/master/AGM_SafeMode/stringtable.xml

Check here about the translation, if it's correct then it most likely displays it "interchanged".

**Comment by Legolasindar** [comment]
Thanks I know the file ;), I just need to know if the order is correct or not. In that case I will modify the translation in Spanish.

**Comment by commy2** [comment]
Fixed a week ago.
