### ISSUE TITLE
Safety for UGL does not work

### ISSUE THREAD

**Issue by bux578** [KoffeinFlummi/AGM#1949]
AGM_Dev 4b6142ba9cc5667560fe77b2587afd9e386bac56

- Be a grenadier
- Select UGL
- Put on safety (it shows the hint)
- Fire

**Comment by commy2** [comment]
You safe the weapon, not the UGL. Muzzles are not supported.

**Comment by bux578** [comment]
imho the hint should be disabled for UGL, it's utterly confusing and dangerous :)
