### ISSUE TITLE
Inventory Interface to big for resolution

### ISSUE THREAD

**Issue by AugustoHA** [KoffeinFlummi/AGM#1951]
My inventory interface be a stronger, I think is a bug.
https://imgur.com/mynd8fU

**Comment by PabstMirror** [comment]
It's a feature:

https://github.com/KoffeinFlummi/AGM/wiki#agm_inventory

if you don't like it remove AGM_Inventory.pbo

**Comment by bux578** [comment]
He probably meant that it's too big for his resolution.

**Comment by commy2** [comment]
It's not really a bug a guess. The Ui screen is made for modern screens (16:9, 16:10).

Can you still access everything, @AugustoHA ?

**Comment by jonpas** [comment]
Why not use safezone things?

**Comment by AugustoHA** [comment]
The inventory is Functional, @commy2  I think is this, my resolution is (4:3), but the not show the weight.
