### ISSUE TITLE
Mount vehicle for ai doesn’t work after healing or getting healed

### ISSUE THREAD

**Issue by EidEchse** [KoffeinFlummi/AGM#1956]
Mount vehicle for ai doesn’t work after healing or get healed

Hi,
If any ia has healed or get healed by another ia and I order them afterwards to mount a vehicle they get in but instantly getting thrown out. So they can’t mount a vehicle after a medical action.

My Medical System Properties:
Damage Coef. 1
Bleeding Speed Coef: 1
Pain Effect Coef: 1
Non-Medic Coef: 2
Max Unc. Time: 120
Allow non med. : yes
Require diagnosis: No
Prev. instant depth: Yes
Prev. death while: No
Single Bandage: No
Unc. Can chat?: Yes
Enable Overdosing: Yes
Req. MEDEVAC: No
Auto Wakeup: Yes

**Comment by commy2** [comment]
Will investigate.

**Comment by EidEchse** [comment]
I investigated it more closely.
The ai get pushed out if they have bloodloss no matter how much. If you give them blood they can board again.
But i think it's still i bug.

**Comment by jonpas** [comment]
During some short testing yesterday, I noticed when an AI is hurt and healed inside the vehicle (helicopter in my case), then when that AI is in the helicopter, Pilot will keep insisting on dropping him, not paying respect to any waypoints you give him or anything. Sometimes it goes into a loop for a few minutes going up and down, picking the other AI up and then dropping him off.

**Comment by JerryKanMan** [comment]
Can confirm it happens to me. Also units get stuck on "Wait" and won't regroup or listen to orders.

**Comment by JCae2798** [comment]
Actualy was coming here to report similar issues with AI healing themselves.  See page 210/211 on AGM thread where i bring this up.

This:
http://forums.bistudio.com/showthread.php?178253-Authentic-Gameplay-Modification&p=2858927&viewfull=1#post2858927

I was able to replicate where and why it happens.  It seems when AI unit loses blood and there is a medic with no bloodbags, both units can be affected by this where they go into a WAIT waypoint and wont follow the leader anymore.  I think medics should also carry more bloodbags by default.

Hope this helps and hope it can be addressed.  Thanks guys

**Comment by esteldunedain** [comment]
Mmm, that's an interesting explanation!

**Comment by esteldunedain** [comment]
Hey, most probably @JCae2798 was right on the money: the medics didn't check if they had bloodbags before trying to heal pacients with bloodloss.

Needs testing though.
