### ISSUE TITLE
Ready Grenade still applying addAction but no wording. 

### ISSUE THREAD

**Issue by jacojazz** [KoffeinFlummi/AGM#1959]
Allows the selector to disappear off the bottom of the list to a hidden/no text option.

**Comment by commy2** [comment]
I don't understand what you mean. Please elaborate.

**Comment by BlenderRUS** [comment]
Seems that "Ready Grenade" action isnt working again in 0.95.1.
There are empty action (no stringtable record or smth).
And nothing happenes if you choose this action in action menu (have to use CTRL+G combination).

**Comment by bux578** [comment]
Can confirm, "Ready grenade" action is missing, but there's an invisible menu action entry. When you scroll the mouse wheel the highlighted background disappears and you have to scroll one more time to get to the next action menu entry.

**Comment by bux578** [comment]
That:

http://forums.bistudio.com/showthread.php?178253-Authentic-Gameplay-Modification&p=2858155&viewfull=1#post2858155

**Comment by commy2** [comment]
Nothing I can do about it. We might remove the "you have to ready the grenades stuff" completely in future. The way it was in 0.95 is NOT reliable.
