### ISSUE TITLE
agm_armor vs RHS

### ISSUE THREAD

**Issue by xPride** [KoffeinFlummi/AGM#1962]
M1025 and GAZ Tigr in RHS with agm_armor.pbo (0.9.5.1) are almost indestructible.
I add two string in fn_handleDamage.sqf, but this thing need to be fixed.
strings:
if (_vehicle isKindOf "MRAP_01_base_F") exitWith {};
if (_vehicle isKindOf "MRAP_02_base_F") exitWith {};

also, BTR60/70/80 in RHS mod can be destroyes by cook-off if you shoot in turret. Need 25-30 bullets in turret and BTR ammo is explode.
i fix it by add string in fn_handleDamage.sqf
if (_vehicle isKindOf "Car_F") then {
....
}
if (_vehicle isKindOf "btr_base_classname") then {
    _type = "car";
};

**Comment by BlenderRUS** [comment]
Little private video describing this:
http://youtu.be/DsHTpiX2Q7U

**Comment by BlenderRUS** [comment]
The problem of RHS BTRs cook-off is default AGM_Armour_AmmoLocation value (HitTurret).
Also sidewards - low turret/wheels armor and absent turret minimalHit values in RHS configs.
Made some fix for this issue:
https://github.com/BlenderRUS/ARMA3_CompFixes/tree/master/A3RU_RHS_armor_fix

**Comment by jonpas** [comment]
@BlenderRUS Feel free to add this to https://github.com/KoffeinFlummi/AGM_Compatibility :)
