### ISSUE TITLE
Inventory auto closes after a few seconds

### ISSUE THREAD

**Issue by bux578** [KoffeinFlummi/AGM#1964]
AGM 0.95.1

Happens throughout my community. No errors in RPT.

**Comment by bux578** [comment]
Just for completeness: RPT: http://pastebin.com/91d71GTy

**Comment by commy2** [comment]
Are you sure this is related to AGM? I don't see how that is even possible.

**Comment by ACyprus** [comment]
bux578 - are you observing this on any particular missions? We have the same issue in my community when at base playing Patrol Ops but happens irrespectively of AGM being loaded or not.

**Comment by bux578** [comment]
We had this issue on Enemy Assault.
