### ISSUE TITLE
Can't cycle grenades with (default) Ctrl + G

### ISSUE THREAD

**Issue by bux578** [KoffeinFlummi/AGM#1965]
AGM 0.95.1

> So I don't know whether it is a problem with the latest version or what, but I was finding that I am now unable to switch different grenade types with ctrl+G. I can change throwing modes with Alt+G though.

http://forums.bistudio.com/showthread.php?178253-Authentic-Gameplay-Modification&p=2856912&viewfull=1#post2856912

Can confirm.

**Comment by bux578** [comment]
RPT from the client where this happens: http://pastebin.com/JJjyT6Lu

**Comment by Meiestrix** [comment]
For me it works after you change your grenades one time with the shortcut keys 6 and 7.

**Comment by gpgpgpgp** [comment]
No idea. But the infamous "magazine" synchronization error seems still there. I am going to investigate which part of AGM grenade has caused such error.

**Comment by commy2** [comment]
> the infamous "magazine" synchronization error

Care to explain what that is and how it is related to this?

**Comment by gpgpgpgp** [comment]
That stupid 6222 error that causes you not able to hear other people (human player)'s gunshots of course! Put on all .951 stuff and play with "-showScriptErrors" on a random public server for a while, and you'll get tons of them in your rpt file. Damn, what the hell is causing it! It's everywhere now. Damn, anyway, this error has nothing to do with this issue anyway. I'm just mad.

**Comment by commy2** [comment]
I doubt that has anything to do with AGM. Maybe a sound mod?

**Comment by esteldunedain** [comment]
The fact that this happens on public servers may indicate that some people are connecting with broken stuff. Maybe you could try using the core module that kick people which don't have the required addons and check if that solves the issue.

**Comment by gpgpgpgp** [comment]
Nah. It's not caused by "missing a mod". It seems certain mods or certain pbo combinations will always lead to 6222 error, while staying to vanilla (no mods at all) the 6222 never happens. Even people shooting guns you don't have won't give you a 6222.

**Comment by KoffeinFlummi** [comment]
> It seems certain mods or certain pbo combinations will always lead to 6222 error.

JSRS.
