### ISSUE TITLE
Mods adding markers messing with AGM_markers list. 

### ISSUE THREAD

**Issue by rhyswilliams999** [KoffeinFlummi/AGM#1966]
Mods that add markers to the game, change what appears on the map. The list of makers available to each stays the same, and to each, the placed markers look the same to them. Unfortunately even though both place the same list of markers (according to their list, in order) they have different markers. I guess it is to do with how AGM gets it's list of markers, counts them all into an array, not using a list of pre-determined named markers. Can AGM instead use a list of named markers instead, rather than counting the markers and possibly mis-aligning them.

Of Course one solution is to make sure everyone is using the same mod list, but would it not be more robust to use a pre-determind list that can be added to, and not a list that can be affected by outside sources.

(This is all speculation with a bit of MP testing/different mod on clients.)

**Comment by rhyswilliams999** [comment]
Not sure how to add labels. Sorry

**Comment by bux578** [comment]
@rhyswilliams999 Don't worry, you can't :smile:

**Comment by rhyswilliams999** [comment]
Ah Thanks.

**Comment by commy2** [comment]
Maybe.I have the strong believe that everyone has to have the same addons though.

**Comment by rhyswilliams999** [comment]
an easy reproduce of this: 2 players join a server with different mods (1: cba, agm. 2:cba, agm, aiaterrainpack) and player 1 puts down a dot marker, player 2 will see that as a flag as his "AGM marker list" is different. My group actually uses the markers (not full NATO etc, just the main list set) and different markers could mean life or death!!! (figuratively speaking of course)

**Comment by PabstMirror** [comment]
`_config = (configfile >> "CfgMarkers") select (_data select 0);`

Looks like we send over the index of a marker.  If people's mods don't line up the indexes won't match (or be out of bounds).

Could probably just send the marker config name, and then if the marker doesn't exist do a fallback to the dot marker.  I'll give it a try.

**Comment by PabstMirror** [comment]
Should be fixed:

Sends marker's shape and color by configName instead of index.
If they don't have the marker, it uses "MilDot" and "Default"
