### ISSUE TITLE
Leaving Unconscious Zeus unit makes you stuck

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#1968]
If you are controlling a Zeus unit and that unit falls Unconscious, and you get out of it you get stuck looking forward, not able to move, but you can shoot and similar.

AGM 0.95.1

**Comment by bux578** [comment]
kind of a duplicate #1826 
https://github.com/KoffeinFlummi/AGM/issues/1826#issuecomment-68173742

**Comment by commy2** [comment]
jonpas. Please do the following:
- Disable all mods including AGM
- Start a mission as zeus and RESPAWN in SP.
- Remote control a spawned AI
- While remote controlling press RESPAWN.
- Change back to your Respawned avatar.

I think that was the repo for the getting stuck bug. It's a bug by BI and there is nothing we can do about it unfortunately.

**Comment by jonpas** [comment]
Yep that is indeed true. However, it is NOT needed to respawn first as in your step 2.

**Comment by commy2** [comment]
: >
