### ISSUE TITLE
Epinephrine shouldn't do anything if multiple heavy injuries are present

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#1969]
In AGM 0.95.1 you can Epinephrine a unit and that unit can patch themselves up then (if they don't fall unconscious again), I think when heavy injuries are present (or more of them) Epinephrine shouldn't do anything before they are bandaged or half-bandaged.

Or make it higher probability to fall back to unconscious if heavy injuries are present when Epinephrine is administered.

**Comment by esteldunedain** [comment]
Check this out https://github.com/KoffeinFlummi/AGM/pull/1899

**Comment by jonpas** [comment]
Ahh, I was actually searching for it but couldn't find it... then automatically assumed it must have been somewhere else. Can be labeled duplicate, thank you!

**Comment by esteldunedain** [comment]
No prob
