### ISSUE TITLE
AI teammates identify unconscious enemies as threat

### ISSUE THREAD

**Issue by HerrStein** [KoffeinFlummi/AGM#1970]
If you play with an AI team and killed an enemy squad, your team will stay in combat stance, if at least one enemy is not dead, but unconscious. They will not engage the unit, but they will not return to a normal stance, if you want head to your next target the AI will have problems to follow you. Once you shoot the unconscious enemy your AI teammate behave normal again. AI may also get stuck  if they lost blood, if that's the case they tend to refuse which results in a "waiting" stance.

**Comment by commy2** [comment]
Nothing we can do about that. No API for AI in that regard. Sry.

**Comment by esteldunedain** [comment]
You can try giving your units an order to change their combat stance. If that doesn't work you may need to disable AI units from falling unconscious when playing with a AI squad.

**Comment by HerrStein** [comment]
would it be possible to make the med system distinguish between AI of different factions? would be nice if my own guys could get medical treatment and the enemies would simply die. maybe as a setting in the medical module?

**Comment by Hees** [comment]
Highly unethical, HerrStein.

**Comment by HerrStein** [comment]
what? explain yourself

**Comment by commy2** [comment]
He was joking. This was requested for the Medical rewrite, but Flummi never put it in. So no, sry.

**Comment by HerrStein** [comment]
ok, i was a bit confused. Schade
