### ISSUE TITLE
AGM Movement - walking animation

### ISSUE THREAD

**Issue by masterT00L** [KoffeinFlummi/AGM#1972]
the chosen animationset for walking with lowered weapon causes a glitchy left arm of every unit and is a true atmosphere killer (left arm holding the weapon breakes and flips, wrist bends).
Yes, Vanilla animation ain't realistic either, but at least it ain't glitchy so please:
-remove the animationset or make it optional without losing the other AGM-Movement-Features

**Comment by commy2** [comment]
No. Sry.
