### ISSUE TITLE
AGM_Interaction? future request

### ISSUE THREAD

**Issue by xPride** [KoffeinFlummi/AGM#1974]
Jerry Can explosion, like this
http://www.youtube.com/watch?v=dm0lxUwvzMg

**Comment by esteldunedain** [comment]
Sorry, no. That's not how it works IRL:

https://www.youtube.com/watch?v=50y4VqRTK84

Note: I think there's a good video of Mythbusters about this toppic but I couldn't find it only quickly enough.

**Comment by bux578** [comment]
Mythbusters Link is in there:
http://skeptics.stackexchange.com/a/12400
