### ISSUE TITLE
AGM Medical conflicts with Zeus Remote Control

### ISSUE THREAD

**Issue by Jester814** [KoffeinFlummi/AGM#1977]
When you control a unit with Zeus with the new AGM medical and the unit dies or goes unconscious, there is no way to release control of the unit and return to your player to keep control of Zeus. You have to either be brought back to consciousness by players or bleed out naturally.

**Comment by BaerMitUmlaut** [comment]
I'm pretty sure pressing Z works, have you tried that?

**Comment by Jester814** [comment]
Z is my raise/lower weapon button. Is it hard-keyed to Z or is it the control that Z is bound to by default? Z does nothing for me.

**Comment by jonpas** [comment]
It's the default keybind to Zeus in Arma (and stupid keybind as well).

**Comment by commy2** [comment]
Works for me with the zeus key.

**Comment by Jester814** [comment]
Ok with further testing I have discovered that having the zeus key bound to a single key works fine, but my Zeus key is shift+pgdown. I don't know what it is about that key combo, but it will not back me out of an unconscious AI.

**Comment by esteldunedain** [comment]
> I don't know what it is about that key combo,

Yeah, sorry Jester. The system we have to allow using Zeus when you'd normally have your input disabled (e.g. when unconscious) is a bit hackish, and doesn't work for key combinations or mouse buttons.

**Comment by commy2** [comment]
There is no better way I'm afraid.
