### ISSUE TITLE
Snipers very inaccurate 

### ISSUE THREAD

**Issue by winterborn107** [KoffeinFlummi/AGM#1980]
ive spent many hours trying to figure the new AGM ballistics out, i understand that just about everything effects ballistics now. but while in virtual reality with absolutely no weather conditions on, i still find that at 300m half the bullets i fire at a target will land very inaccurately. ive tested this with many different rifles and scopes. it is happening with everyone of them. is this some how intended? or buged?

**Comment by bux578** [comment]
Please try it with this: https://github.com/KoffeinFlummi/Arma3Spotter

Required items:
* Kestrel for windage
* Vector 21 for inclination ([using the "Azimuth & Inclination" method](https://github.com/KoffeinFlummi/AGM/wiki/Getting-Started#5-azimuth--inclination))

**Comment by winterborn107** [comment]
no change. its not constantly off in one direction. on shot will go upper right, the next dead center, the next far left. id understand a little variation of impact points, but its ranging from 3 to 12 inches off center at only 300 meters.

**Comment by KoffeinFlummi** [comment]
Are you using the APFS rounds for the Lynx? Those have additional dispersion.

**Comment by natrius** [comment]
I will try this at home too

**Comment by bux578** [comment]
I did a video:
https://www.youtube.com/watch?v=969KThG2X7U

perfectly accurate

**Comment by winterborn107** [comment]
ok, its not on your end then, thank you, just wanted to confirm that. ill find and squish what ever is causing the issue on my end
