### ISSUE TITLE
How should one use fn_checkPBOs?

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#1981]
I have this line in XEH_preInit.sqf

```[2, true, false] call fn_checkPBOs;```

But it seems like it does nothing. 

How should i execute the function, without onmap module, so it will check all the pbos?

**Comment by esteldunedain** [comment]
@tachii, its:

```
[2, true, false] call AGM_Core_fnc_checkPBOs;
```

**Comment by Tachii** [comment]
Thanks!
How should i execute it? Locally or on the server?

**Comment by esteldunedain** [comment]
Locally on each client, as far as I can tell.

**Comment by Tachii** [comment]
It gives me next error when i'm trying to execute it:

```
2015/01/20, 16:58:12 File AGM_Core\functions\fn_moduleCheckPBOs.sqf, line 19
2015/01/20, 16:58:12   Error parsenumber: Type Number, expected String
2015/01/20, 16:58:12   Error position: <parseNumber (_logic getVariable "Action">
_mode = parseNumber (_logic getVariable "Action">

if !(_activated) exitWith {};
2015/01/20, 16:58:12 Error in expression <

```

**Comment by esteldunedain** [comment]
Yeah, apparently you have to pass the first number as string:

```
["2", true, false] call AGM_Core_fnc_checkPBOs;
```

Sorry about that

**Comment by Tachii** [comment]
Now it says:
```
17:11:49 Warning: no type entry inside class RscDisplayNotFreeze/controlsBackground/CA_Vignette 
17:11:49 Warning: no type entry inside class RscDisplayMPInterrupt/controlsBackground/Vignette 
17:11:50 Error in expression < ["CheckAll", false];
_whitelist = call compile (_logic getVariable ["Whitelist">
17:11:50   Error position: <compile (_logic getVariable ["Whitelist">
17:11:50   Error compile: Type Bool, expected String
17:11:50 File AGM_Core\functions\fn_moduleCheckPBOs.sqf, line 21

```

I've tried : ["2", "true", false] call AGM_Core_fnc_checkPBOs;
result:
```
17:12:37 Error in expression < ["CheckAll", false];
_whitelist = call compile (_logic getVariable ["Whitelist">
17:12:37   Error position: <compile (_logic getVariable ["Whitelist">
17:12:37   Error compile: Type Bool, expected String
17:12:37 File AGM_Core\functions\fn_moduleCheckPBOs.sqf, line 21
```

I've tried:  ["2", "true", "false"] call AGM_Core_fnc_checkPBOs;

```
17:13:49 Warning: no type entry inside class RscDisplayNotFreeze/controlsBackground/CA_Vignette 
17:13:49 Warning: no type entry inside class RscDisplayMPInterrupt/controlsBackground/Vignette 
17:13:50 Error in expression <y set [_forEachIndex, _x call _code];
} forEach _array;
_array
>
17:13:50   Error position: <forEach _array;
_array
>
17:13:50   Error foreach: Type Bool, expected Array
17:13:50 File AGM_Core\functions\fn_map.sqf, line 29
17:13:50 Error in expression <y set [_forEachIndex, _x call _code];
} forEach _array;
_array
>
17:13:50   Error position: <forEach _array;
_array
>
17:13:50   Error Generic error in expression
17:13:50 File AGM_Core\functions\fn_map.sqf, line 29

```

I'm kinda confused

**Comment by Tachii** [comment]
Also i've tried to run globally: ["2", "true", "false"] call AGM_Core_fnc_checkPBOs;

```
17:15:17 Error in expression <y set [_forEachIndex, _x call _code];
} forEach _array;
_array
>
17:15:17   Error position: <forEach _array;
_array
>
17:15:17   Error foreach: Type Bool, expected Array
17:15:17 File AGM_Core\functions\fn_map.sqf, line 29
```

**Comment by bux578** [comment]
The third param should be the whitelist.

```sqf
["2", "true", "[]"] call AGM_Core_fnc_checkPBOs
```

**Comment by esteldunedain** [comment]
No @tachii. Apparently `AGM_Core_fnc_checkPBOs` comments about it's parameters are very wrong.

Try this out please:

`["2", true, "[]"] call AGM_Core_fnc_checkPBOs;`

**Comment by Tachii** [comment]
Thanks, it looks like it doesn't give me any errors, but still it doesn't work

If i understood correctly, it must kick me if i'm missing any pbos that are required by the server?
I've deleted few pbos inside of my @addon folder, but i can still join and play on the server.

**Comment by commy2** [comment]
I as the creator of the checkPBO module can only say, don't call the function yourself. Use the module instead.

**Comment by Tachii** [comment]
Why not?
Is there a way, to do it without manually placing the module in the editor every time i create a mission?

Why i'm asking, it's because in our community we are using a custom mission framework, and i want this nice feature of yours to check all the pbos.

**Comment by jonpas** [comment]
If you have a custom mission framework then pre-place the module on the map?

**Comment by Tachii** [comment]
Because it auto generates everything. Thats why i'm asking how can i create this module without adding it manually in the editor

**Comment by commy2** [comment]
It's not an API function. The way it works might change with the next AGM update. Using the function instead of the module is not supported.

**Comment by jonpas** [comment]
mission.sqm would look something like:
```
class Item0
{
  position[]={15443.095,-0.013707653,13670.494};
  class args
  {
    items=1;
    class Item0
    {
      value="2";
      parentCls="AGM_ModuleCheckPBOs";
      typeName="Action";
    };
  };
  id=79;
  side="LOGIC";
  vehicle="AGM_ModuleCheckPBOs";
  leader=1;
  lock="UNLOCKED";
  skill=0.60000002;
};
```

**Comment by Tachii** [comment]
Thanks for the answers

**Comment by Tachii** [comment]
Yeah it works if i add it to mission.sqm at generate a mission with it.

But i have a feature request now :)

Can you add an option, for unnecessary addons that are only server side only and must not be on the client side? 

Basically i kinda need an option, where i can add only server-side addons, that are not required from client to have. 

Something like ASRai for example?

**Comment by Tachii** [comment]
Btw even with module on the map it gives me next error:

```
1:51:57 Error in expression <t = _whitelist;

if (!isServer) then {
[_mode, _checkAll, _whitelist] spawn {
_m>
 1:51:57   Error position: <_mode, _checkAll, _whitelist] spawn {
_m>
 1:51:57   Error Undefined variable in expression: _mode
 1:51:57 File AGM_Core\functions\fn_moduleCheckPBOs.sqf, line 33
 1:51:57 [AGM]: Check-PBOs Module Initialized. Mode: scalar.
 1:51:57 Error in expression <ck-PBOs Module Initialized. Mode: %1.", _mode];
>
 1:51:57   Error position: <_mode];
>
 1:51:57   Error Undefined variable in expression: _mode
 1:51:57 File AGM_Core\functions\fn_moduleCheckPBOs.sqf, line 96
```

**Comment by commy2** [comment]
Try putting it into the exceptions array.

**Comment by Tachii** [comment]
Yeah, it helped, thanks.

Please make it an API function :)

**Comment by commy2** [comment]
maybe in future
