### ISSUE TITLE
Some modules not working after loading a save game

### ISSUE THREAD

**Issue by CombustingBats** [KoffeinFlummi/AGM#1982]
When loading a save game after restarting ArmA 3, some things like the self interaction menu, weapon resting and checking how much ammo is left in the magazine stop working.  I have tried using Moduload (http://www.armaholic.com/page.php?id=24616) to fix it, but it doesn't seem to work.  I saw that this was a problem in the past and it was supposedly fixed, but I'm still getting the bug now.

**Comment by commy2** [comment]
It has to be a savegame that was started using AGM.

**Comment by CombustingBats** [comment]
I have tried restarting save games and ArmA 3 multiple times, but it doesn't seem to change anything.

**Comment by commy2** [comment]
You have to start that mission with AGM and only then you can resume it with AGM aswell.

**Comment by CombustingBats** [comment]
I've started missions with AGM installed and working, and then when I resume that save game, it seems like the hotkeys aren't working, as I can still check how much ammo is in the magazine, but my character reloads as well.

**Comment by CombustingBats** [comment]
Starting a new game works fine, but after saving, closing ArmA 3 and reopening it, parts of AGM stop working.  This is not just an AGM problem; many mods also stop working after continuing save games, but most other mods have their own fixes, or moduload can reinitialize them.  I've searched old issues and this was a problem before, and it was supposedly fixed, but it still I'm still getting this problem.  What more information do you need to diagnose and hopefully fix the problem?

**Comment by commy2** [comment]
I'll look into it. Don't expect anything soon though.

**Comment by JCae2798** [comment]
This is weird.  I just started noticing this as well while playing the Whole Lotta Altis scenario.  I haven't been able to pin point exactly what is causing it, but not sure if its AGM Related as it ends up disabling my hotkeys on other MODs as well.  It may be a bug in 1.4x, but if you guys find a solution or the issue itself and root cause, i'd like to escalate to whoever would own it.  I'll keep trying to find a way to replicate...  This is in SP mode i am testing

**Comment by 5kyw4Lk3r** [comment]
yo sup guys,so I just tried the latest version of agm-v0.95.3 with the latest version of moduload v0.5.2 from arma3.de cuz armaholic links are littered with ads,so anyway all agm modules initialize like a charm,even other mods like drongostoolkit load up which they never did after a save...hope it works out for ya'll... MAKE ARMA NOT WAR..

**Comment by jonpas** [comment]
AGM has been discontinued for a new mod ACE3.

**Comment by 5kyw4Lk3r** [comment]
yeah but the last agm was bitchin, till ace 3 is out of beta it's a tad neccessary to have around if not to use modules in agm  ommited in ace 3...

**Comment by bux578** [comment]
Sorry to say, but we're not working anymore on AGM. Consider it dead and ACE3 being the pheonix  risen from its ashes.

**Comment by 5kyw4Lk3r** [comment]
well then I give my thanx to all who worked on agm ,and bow down to the Phoenix. ...

**Comment by bux578** [comment]
Thanks :) :arrow_forward:  https://github.com/acemod/ACE3
