### ISSUE TITLE
How can i get current temperature?

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#1983]
Is there a function that returns current temperature?\

**Comment by PabstMirror** [comment]
AGM_Wind_currentTemperature

**Comment by Tachii** [comment]
Thanks

**Comment by Tachii** [comment]
Doesn't seem to work:

```
hint str(AGM_Wind_currentTemperature);
```

Shows 0 on stratis;

**Comment by Tachii** [comment]
Why this returns false?
'''
If (agm_wind_currenttemperayure > 0) then {hint "true"} else { hint "flase"};
'''

**Comment by PabstMirror** [comment]
"temperayure"?

use:
```
If (AGM_Wind_currentTemperature > 0) then {hint "true"} else { hint "flase"};
```

**Comment by Tachii** [comment]
oh god, lol, thanks :D
