### ISSUE TITLE
Explosives detonation menu

### ISSUE THREAD

**Issue by LokstarValHallen** [KoffeinFlummi/AGM#1984]
It would be nice if the explosives detonation menu remain open after detonating. It would be much more convenient if detonating multiple charges.

**Comment by Blackswater** [comment]
or maybe mark multiply charges at the same time

**Comment by jonpas** [comment]
This would be a nice feature until chain/multiple discharges.

**Comment by commy2** [comment]
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/709
