### ISSUE TITLE
Remove ability to rest weapons on bushes?

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#1986]
Now you can rest your weapon on any bush, can you somehow disable it?

http://youtu.be/jCHPCuPxGG4

**Comment by PabstMirror** [comment]
Hmm.

I tried `lineIntersectsWith` and got "64084: b_ficusc1s_f.p3d", the problem is that typeOf on it is "" (empty string because no config entry), so I don't know how to tell if a object is a bush.

**Comment by Tachii** [comment]
Have you tried isKindOf "Bush" ?

**Comment by Tachii** [comment]
```_objects = lineIntersectsWith [eyePos player, aimPos player, player, player]; _bush = _objects select 1; if (_bush isKindOf "Bush") then { hint "true"} else {"false"};```

returns false...

**Comment by BaerMitUmlaut** [comment]
As he said there's no config entry for it, so that won't work. isKindOf checks for the classname/parent classes in the config.
