### ISSUE TITLE
agm_interaction Breaks lower weapon after  ArmA update 1.38 

### ISSUE THREAD

**Issue by jones140** [KoffeinFlummi/AGM#1988]
did a bit of testing and narrowed it down to agm_interaction 

u can no longer lower weapon after update have

**Comment by xPride** [comment]
I thick trouble also in change greenade mode (2xLeftCtrl coflict with LCtrl + G, u can see this in options) if u change lower weapon key to 2xRCtrl and press it while moving lower weapon is work! :D

**Comment by jones140** [comment]
Tested with ur code works like a charm good jon
