### ISSUE TITLE
Modifier Key Default setting conflicts with Lower Weapon

### ISSUE THREAD

**Issue by BryanBoru** [KoffeinFlummi/AGM#1992]
When using AGM with default keybindings, CTRL X2 will no longer lower weapon due to the Modifier Key also being set to CTRL,
reproduced by Running Arma 3 with AGM only, with default keybindings. Go in game and 2XCTRL to lower weapon.

I know this can be resolved by rebinding either binding, but since I have nothing to modify at that time, is there a way to only allow modifier key to matter when using an action that calls on the modifier key?
If not I may suggest an other default setting (i know they are starting to get scarce without having an A3 conflict)

**Comment by esteldunedain** [comment]
Yeah, we fixed that yesterday. We kept the key binds and removed the conflict by tweaking the code.

We expect to launch 0.95.2 with this and other little fixes in the next few days.

**Comment by commy2** [comment]
https://github.com/KoffeinFlummi/AGM/issues/1988

Fixed in dev.

**Comment by BryanBoru** [comment]
Excellent work once again guys. thanks
