### ISSUE TITLE
How does agm ballistics affect high caliber?

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#1996]
Does it affect it at all, especially rpg and at ammo?
And also what agm_bulletmass actually does, is it related to ragdoll?
Haven't found any info in the wiki

**Comment by Tachii** [comment]
Also I've found agm_bulletdispersion, how it differs from normal dispertion parameter?

**Comment by commy2** [comment]
agm_ballistics doesn't affect RPGs or tank guns at all. agm_wind applies to to them though.

agm_bulletmass is related to powder temperature and weapon overheating.
No Idea about agm_bulletdispersion.

**Comment by Tachii** [comment]
Thanks for the info. So this means if i'm making a custom at launchers addon and i want agm-compatibility in terms of wind deflection for rockets i don't have to add anything special to it?

**Comment by esteldunedain** [comment]
> Thanks for the info. So this means if i'm making a custom at launchers addon and i want agm-compatibility in terms of wind deflection for rockets i don't have to add anything special to it?

Yep

> agm_bulletdispersion.

Is for adding additional dispersion to particular rounds like the APDS (sabot rounds)(https://github.com/KoffeinFlummi/AGM/issues/924), .
