### ISSUE TITLE
jamming problem

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#1997]
Sometimes when my weapon gets jamed, it consumes all the magazines if I keep pressing R. Only thing that helps is dragging magazine from inventory slot to magazine slot.

if you won't be able to reproduce it I'll try to make a video tomorrow

**Comment by PabstMirror** [comment]
Is this stock A3 weapons or mod pack?

From what I understand on some mod weapons, if there isn't a proper animation, the gun won't reload but it will eat the mag.

Also what stance where you in?  ( check `animationState player`)

**Comment by Tachii** [comment]
It hppaned with mod weapons, haven't played with vanila ones for a while.

I'll make a video tomorrow

**Comment by gpgpgpgp** [comment]
This happens to me sometimes, and it definitely has something to do with bipods. No idea what cause it yet, but remove & reattaching a magazine via the inventory menu fix this relatively rare problem.

**Comment by PabstMirror** [comment]
Specific weapon classnames and animation states would help.

**Comment by commy2** [comment]
Known. It's  bug with the reloading state of the player BI introduced some version ago. And there is nothing we can do about it unfortunately. No point in fixing it, when they introduces resting themselves in Q1.

Also duplicate I think, but to lazy to find the old issue...
