### ISSUE TITLE
Slingloads can't be repaired

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#2000]
AGM 0.95.1, there is still no option to repair sling-load mechanism?

**Comment by commy2** [comment]
Sry, I don't quite understand. Is this meant as bug report? Because I can't remember that we ever added something like this.
Or is this a feature request? Then please elaborate on what you mean by "sling load mechanism".

**Comment by jonpas** [comment]
You can now repair all helicopter components except the sling-load mechanism/sling-loads/slings (whatever you want to call it). If you go into a helicopter and land hard enough your "SLNG" will turn orange/red. Currently there is no way to repair that with AGM's repair and when it's broken your slings are inoperable and the only way is to use Zeus to repair it or take another helicopter.

I guess it can be counted as both bug and feature request, however you deem it. I am not really sure how to explain this better.

**Comment by commy2** [comment]
Rgr

**Comment by jonpas** [comment]
Is it just config option for the interaction menu or must there be something else changed? I bet name of the part is similar, something like `HitSlings`.

**Comment by commy2** [comment]
```
[vehicle player] call agm_core_fnc_getHitpoints

["HitHull","HitFuel","HitAvionics","HitEngine1","HitEngine2","HitEngine","HitHRotor","HitVRotor","HitMissiles","HitRGlass","HitLGlass","HitEngine3","HitWinch","HitTransmission","HitGlass1","HitGlass2","HitGlass3","HitGlass4","HitGlass5","HitGlass6","HitLight","HitHydraulics","HitGear","HitHStabilizerL1","HitHStabilizerR1","HitVStabilizer1","HitTail","HitPitotTube","HitStaticPort","HitStarter1","HitStarter2","HitStarter3","HitTurret","HitGun"]
```

**Comment by commy2** [comment]
It's "HitWinch"

**Comment by jonpas** [comment]
Indeed, I'll write up the interaction menu config.

**Comment by commy2** [comment]
Done. Also added the hitpoint to the check vehicle function.

**Comment by jonpas** [comment]
:+1:
