### ISSUE TITLE
ATRQ repair broken

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#2001]
I am not positive this is AGM's bug, but I am not currently in position to test it otherwise and thought it would be better if I post and don't forget.

When you kill your anti-torque rotor and repair it using AGM's repair (obviously) then get back into it it all spins fine (but with a delay and starts spinning only when the helicopter is fully started and spun up) but it does not work. The strange thing is, it repairs for everyone else on the server (they can fly normally), but for local unit (yourself) it doesn't get repaired (keeps spinning if you take off). If you reconnect it's normally repaired as well.

Using Advanced Flight Model.

**Comment by commy2** [comment]
Sounds more like BI broke something. Try it with vanilla repair trucks. I don't own the DLC, so testing that is impossible for me.

**Comment by KoffeinFlummi** [comment]
> Sounds more like BI broke something. Try it with vanilla repair trucks. I don't own the DLC, so testing that is impossible for me.

No it isn't. Everyone can use the AFM.

**Comment by commy2** [comment]
Huh? I can't?

**Comment by jonpas** [comment]
You can use it, AFM is a feature, features are free, only content is paid (those 2 helicopters for Heli DLC), but features are still part of DLC. :grinning:
Basically, you can use all the featuers from the DLC (sling-loading, AFM, firing from vehicles).

**Comment by esteldunedain** [comment]
> Huh? I can't?

Obviously you can commy. Stop coding and play the actual game for a while (Configure -> Game -> Difficulty to turn on/off)

**Comment by commy2** [comment]
Not gonna fly a helicopter. I'm a panzergrenadier : /

**Comment by jonpas** [comment]
Haha, I'll try to reproduce it in a sensible way first, since so far I only managed to remember to try it in multiplayer.

**Comment by commy2** [comment]
So I made a LAN mission and spawned as engineer with toolkit right next to a initially damaged helicopter.

I repaired all hitpoints and everything seems to be ok. I obviously can't fly with rotorlib. How would I know if that AT rotor works or not?

**Comment by jonpas** [comment]
You would just go in and try to fly. You can use RotorLib with keyboard and mouse as well, at least for a test like this, just go to Options and enable Advanced Flight Model.

I know it happened to me twice so far on the Hellcat in Multiplayer. Trying to reproduce in single now with other helicopters.

**Comment by commy2** [comment]
Works for me. Can't repro.

**Comment by jonpas** [comment]
Just did some test and I could only reproduce it with a Hellcat from [NATO Hellcats](http://www.armaholic.com/page.php?id=24161) mod. Though that makes no sense as that mod inherits everything from AAF's Hellcat (I checked the config), but Vanilla one appears to be working fine.

I'll keep trying to reproduce this on others...

**Comment by commy2** [comment]
>that mod inherits everything from AAF's Hellcat

That actually means nothing if the config is set up incorrectly. Please also try if the same thing happens using vanilla repair trucks.

**Comment by jonpas** [comment]
Woop, just managed to reproduce with Vanilla AAF's Hellcat. And config looks correct, at least to me (and I did my own similar config for my Skycranes). Will try with repair trucks.

**Comment by jonpas** [comment]
Ok, the problem with vanilla repair trucks is that you can't repair if not enough stuff is damaged... so I can't reproduce it because I have to damage more than my Tail Rotor to be able to repair with a repair truck at all.

**Comment by commy2** [comment]
> you can't repair if not enough stuff is damaged

Thats not how they are supposed to work. Every minimal damage should be repairable by them. Maybe BIS did really mess it up? I mean not being able to repair something, unless you damage something else sounds like a bug.

**Comment by bux578** [comment]
Just tested it.

In Vanilla:

Damaging the ATRQ rotor of the MH9 and driving a repair HEMTT close to it repairs the ATRQ rotor. With or without AFM.

**Comment by bux578** [comment]
With AGM:

Damaging the ATRQ rotor of the MH9 and driving a repair HEMTT close to it DOESN'T repair the ATRQ rotor by itself. But allows everyone (?) to repair it when close by.

**Comment by jonpas** [comment]
>This does not happen in vanilla. Maybe the heli has more parts with the AFM that needs to be repaired?

I believe that is indeed true. Good job on the testing bux!

**Comment by commy2** [comment]
So it's probably related to this:
https://github.com/KoffeinFlummi/AGM/issues/2000

**Comment by commy2** [comment]
```
[vehicle player] call agm_core_fnc_getHitpoints

["HitHull","HitFuel","HitAvionics","HitEngine1","HitEngine2","HitEngine","HitHRotor","HitVRotor","HitMissiles","HitRGlass","HitLGlass","HitEngine3","HitWinch","HitTransmission","HitGlass1","HitGlass2","HitGlass3","HitGlass4","HitGlass5","HitGlass6","HitLight","HitHydraulics","HitGear","HitHStabilizerL1","HitHStabilizerR1","HitVStabilizer1","HitTail","HitPitotTube","HitStaticPort","HitStarter1","HitStarter2","HitStarter3","HitTurret","HitGun"]
```

**Comment by commy2** [comment]
Maybe it's not the AT rotor, but "HitVStabilizer1" ?

**Comment by commy2** [comment]
I think this is caused by those additional hitpoints when using rotorlib. Writing a work-around is imo not worth it considering the logistics rewrite.

\>\> https://github.com/KoffeinFlummi/AGM/issues/1937

**Comment by jonpas** [comment]
Sounds good.

**Comment by commy2** [comment]
Sucks that it won't be in 0.952, but it would really require to throw everything out the window whats currently there. Because there are so many hitpoints now they don't fit into the menu. I'll need to use the listbox for that. And somehow filter what the repairing client has as rotorlib settings plus sync that somehow to those who don't have it...

**Comment by jonpas** [comment]
Yeah I understand, tedious. It's not a big problem really, at least not for us as we use persistent reconnects, so if I repair it I can just hop back to lobby and back in and I'll be on exactly same position with same gear. The only thing will be that I'll forget it's a bug and fully take-off then spin out of control, haha.

**Comment by jonpas** [comment]
Today's dev-branch changelog:
> Fixed: Tail rotor destruction

http://forums.bistudio.com/showthread.php?149636-Development-Branch-Changelog&p=2866658&viewfull=1#post2866658

Possibly connected?
