### ISSUE TITLE
You cant lower your weapon with latest Arma Version

### ISSUE THREAD

**Issue by Meiestrix** [KoffeinFlummi/AGM#2002]
You cant lower your weapon with latest Arma Version.
Only when you remove the modifictor button and the show names button in AGM button config.

**Comment by Sk3y** [comment]
tested and confirmed

**Comment by esteldunedain** [comment]
Triplicated issue:
https://github.com/KoffeinFlummi/AGM/issues/1992
https://github.com/KoffeinFlummi/AGM/issues/1999

Already fixed two days ago. We'll release 0.95.2 with this and other small fixes in the next few days.

**Comment by commy2** [comment]
quadruplicated* bug report
