### ISSUE TITLE
Team Management

### ISSUE THREAD

**Issue by vgl217** [KoffeinFlummi/AGM#2005]
I realize that this mod is geared more towards multiplayer, but it would be nice to be able to use the scroll menu for commanding AI like in vanilla Arma 3. For example, I want to have my team switch to a new formation, or order a SITREP, but i cant because of the weapon key bindings... may i suggest being able to open the order menu with either f1, f2, f3, etc. or just ~, then with the commanding menu open, that would disable the weapon bindings. Great job on an even better mod!

**Comment by bux578** [comment]
Maybe disabling the weapon key bindings in the AGM options (press ESC, top left corner, 4th page (iirc)) would be a solution. You can't switch weapons with the number keys, but can command your AI.

**Comment by commy2** [comment]
If you still want to use the command menu, you can set those keys to ctrl + 1 etc. and still have the ai command menu. __I think__

**Comment by vgl217** [comment]
I missed that option before... thanks for the help
