### ISSUE TITLE
Performance Improvement?

### ISSUE THREAD

**Issue by Komodo1** [KoffeinFlummi/AGM#2009]
I noticed when watching the "setvariable" log that agm_isdiagnosed is pretty often set, even if I use the option to not force dialog.
I'm wondering if getting too often this variable sent to the server (even when never changed) might be a performance issue!

**Comment by commy2** [comment]
>might be a performance issue!

Do you experience any desync when threating others?
We are aware of the network behavior of `setVariable`. Obviously there is always room for improvement.

**Comment by Komodo1** [comment]
That's for sure, but I multiplied by 50 the number of "public" setVariables by activating AGM, that's why I'm offering quick and simply way to improve this, by not doing these setVariables when not needed.
Totally agreed, with whatever code we can build, you'll have room for improvements!

**Comment by Komodo1** [comment]
I meant "multiplied by 50 the number of general calls to setVariable". Impact will for sure depend on what's being broadcasted, and here we're talking about boolean for sure, not complex array.

**Comment by commy2** [comment]
So what about this? I don't see any easy way to improve this.

**Comment by Komodo1** [comment]
In our case we don't force diagnosis before healing, thus if not activated this would prevents from spamming setvariable in public mode.
this specific "agm_isdiagnosed" set is representing 45% of setVariables public occurrences in our setup (150k occurrences on 4h). For sure other setVariables cannot be avoided (blood, pain, ...), but "agm_isdiagnosed" represent 50% of all AGM setvariable occurrences.
That for sure has an impact on performances, but I can't quantify it for now.
Will test it during the coming weeks and keep you posted!

**Comment by esteldunedain** [comment]
@Komodo1, you're right, the amount of times agm_isdiagnosed gets synced can be hugely optimized and it will.

However, we are very curious on how did you realized this. What tool did you use to measure the amount of variables syncs? We would like to be able to that ourselves.

**Comment by Komodo1** [comment]
Simple isn't it? ;)
I used the setvariable.log with simple excel csv importe after using regular expressions to format the setVariable.log
It's pretty efficient tool when I need to know what's happening, and I use publicVariable with filters to know what's being request by clients to the server and to other clients to try finding other optimizations.

FYI, the "AGM_Core_fnc_callCustomEventHandlers" on "preventDeath" is called pretty often as well (monitoring "AGM_Core_remoteFnc" in publicVariable.log this time), even if I don't use preventDeath event.
This one would be a bit tricky to deactivate for everyone, thus I'll keep custom code here as I don't think it might be applicable to all AGM users.

Thanks for your replies, and thanks a lot for this great mod!

**Comment by esteldunedain** [comment]
@Komodo1, yes it was simple. I'm very interested on optimizing this kind of things, but I was not aware of setvariable.log. From what I gathered on line, it is generated by Battleye, but I couldn't yet find how.

Is that right? Can you point me some more pointers?

**Comment by esteldunedain** [comment]
@Komodo1, I been trying to get Battleye to generate those log files without success. Here's what I did:

1 - Turned on Battleye on the dedicated server server.cfg

`BattlEye = 1;`

2 - Created the `\Battleye\setvariable.txt` file on the server containing:

`3 "" `

Which according to [this](http://webcache.googleusercontent.com/search?q=cache:2kPRBtbON3AJ:opendayz.net/threads/a-guide-to-battleye-filters.21066/+&cd=6&hl=es-419&ct=clnk&gl=ar) should log all public setVariable both to the `setVariables.log` file and to the server console. 

However, nothing is written to the console and no extra file is created. Am I missing something?

**Comment by Komodo1** [comment]
Here is what we have in our setVariable:

1

That's all :)
