### ISSUE TITLE
Artillery Computer  

### ISSUE THREAD

**Issue by xPride** [KoffeinFlummi/AGM#2010]
Hi guys, look at http://www.armaholic.com/page.php?id=27995 - very good realization of ArtComp.
If the author agrees - this is a very welcome part of your project.

**Comment by Trigger81** [comment]
look at https://github.com/KoffeinFlummi/AGM/issues/1194

**Comment by commy2** [comment]
: )

Duplicate of https://github.com/KoffeinFlummi/AGM/issues/1194
