### ISSUE TITLE
Is there a way to lower hearing loss effect of a specific weapon?

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#2011]
Something parameter that i can add to the weapons config?

**Comment by BaerMitUmlaut** [comment]
CfgAmmo >> ammo type >> audibleFire
So not weapon but ammo specific, see:
https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Hearing/functions/fn_firedNear.sqf

**Comment by jonpas** [comment]
It's ammo config:
[`audibleFire`](https://community.bistudio.com/wiki/CfgAmmo_Config_Reference#audibleFire)

**Comment by Tachii** [comment]
Thanks

**Comment by jonpas** [comment]
No problems, good luck with it!
