### ISSUE TITLE
Number keys

### ISSUE THREAD

**Issue by runnybunny** [KoffeinFlummi/AGM#2017]
Seems like the number keys are now used for weapons. Not sure why since they're already used for commanding AI, and we can't re-bind those keys in-game. Even rebinding the AGM weapon switch keys do not allow us to command AI.

**Comment by jonpas** [comment]
Last page of AGM Options -  Disable command menu - uncheck it.

**Comment by PabstMirror** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9376747/5895963/782a213c-a4f2-11e4-8e68-0b7121462026.png)

Make sure to hit save.
