### ISSUE TITLE
While treating, the animations move you back a few inches every time

### ISSUE THREAD

**Issue by jj33** [KoffeinFlummi/AGM#2023]
Steps to reproduce:
1) kneel by patient
2) diagnose
3) treat wound
4) repeat as necessary

After each step, you will note you have moved backwards slightly, and actually can back yourself out of range after a lot of wounds being treated.

Plus if you start with your weapon on your back, you end up with it in your hands at the end of each animation. It would be better to sling your weapon at the start of diagnose, and only reset it back when you leave the treatment menu.

**Comment by commy2** [comment]
Yea. We are limited to the animations that BI put in the base game. Nothing we can do about that.
