### ISSUE TITLE
Big performance drop with nothing happening just from AGM

### ISSUE THREAD

**Issue by PaulKeeble** [KoffeinFlummi/AGM#2027]
What we did
- Added the AGM mod from play with six with no modules added or removed.
- Launch the game with just that mod
- Open the editor and place a nato unit in the main airport and a local town as a custom mission 

- Run the game with and without the mod running.

What we expected
That performance would be identical between the two tests (AGM enabled and not).

What actually happened
Performance in vanilla was 83 frames per second, and 60 with AGM. That is a sizeable reduction in performance just from starting the game with this mod.

Should hopefully be easy to verify, likely harder to track down and find the cause.

**Comment by esteldunedain** [comment]
Well, that's interesting. Maybe you could try gradually removing agm pbos to better pinpoint where's the overhead?

**Comment by Tachii** [comment]
Wow, if you manage that fps drop thing it would be huge, if it acutally exists. It would be nice of you could add reproduce mission, just to be sure if its agm fault, not anything else @PaulKeeble

**Comment by bux578** [comment]
I'll try to verify that ...

**Comment by JonBons** [comment]
So I got curious about this issue last night and started messing around and came up with a crazy idea that probably is a total waste of time but I figured I'd share it.

I wrote a powershell script with a dependency map of all AGM pbos and I utilized the -autotest param in Arma with a modified Arma3Mark mission which then pulls the avg fps from the last RPT log and it does this while adding more and more pbos from AGM (eventually I might make it test a single pbo w/ deps at a time) and at the end it outputs the avg fps from each test run.

It currently does not test the mission without any mods but it at least lets you run through a adding more and more of AGM and looking for any big dips (although you would need multiple runs to verify)

Powershell script: https://gist.github.com/JonBons/a08178c5e9ba0d44f571

Scripts and test mission (goes in A3 dir): https://dl.dropboxusercontent.com/u/1652088/Arma/A3_AGM_UnitTest.zip

**Comment by esteldunedain** [comment]
@JonBons, that's really interesting. I'll run this myself later, but until I can I'm curious about what numbers did you get. Could you paste them here please?

**Comment by PaulKeeble** [comment]
We are finding quite a large variance in the performance drop as we tried
to narrow down to an individual PBO. Today for example we have seen drops
of just 5 fps all the way up to the original 20 or so and there seems to be
no reason for the high variance. Vanilla doesn't seem to vary quite so much
and its still clear AGM is dropping performance in a completely empty
editor world (and presumably MP mission made from it) but its odd that the
performance difference varies so much.

**Comment by esteldunedain** [comment]
Well, I finished running @JonBons script in my rig. Made some small tweaks to the script, to avoid some errors and run without any modules first. The modified program is here: https://gist.github.com/esteldunedain/d414e9696624d1c2b532

So here are the results on my (humble) rig:

```
Disabled mod pbos
Testing without AGM
Test ran and got 55 FPS
Testing mod pbo:agm_core
Test ran and got 55 FPS
Testing mod pbo:agm_interaction
Test ran and got 54 FPS
Testing mod pbo:agm_ai
Test ran and got 55 FPS
Testing mod pbo:agm_aircraft
Test ran and got 54 FPS
Testing mod pbo:agm_armour
Test ran and got 56 FPS
Testing mod pbo:agm_attach
Test ran and got 56 FPS
Testing mod pbo:agm_backblast
Test ran and got 55 FPS
Testing mod pbo:agm_backpacks
Test ran and got 56 FPS
Testing mod pbo:agm_ballistics
Test ran and got 56 FPS
Testing mod pbo:agm_captives
Test ran and got 56 FPS
Testing mod pbo:agm_difficulties
Test ran and got 56 FPS
Testing mod pbo:agm_disposable
Test ran and got 56 FPS
Testing mod pbo:agm_explosives
Test ran and got 56 FPS
Testing mod pbo:agm_fastroping
Test ran and got 55 FPS
Testing mod pbo:agm_firecontrolsystem
Test ran and got 57 FPS
Testing mod pbo:agm_gforces
Test ran and got 55 FPS
Testing mod pbo:agm_goggles
Test ran and got 54 FPS
Testing mod pbo:agm_grenades
Test ran and got 55 FPS
Testing mod pbo:agm_hearing
Test ran and got 54 FPS
Testing mod pbo:agm_inventory
Test ran and got 55 FPS
Testing mod pbo:agm_logistics
Test ran and got 54 FPS
Testing mod pbo:agm_magazinerepack
Test ran and got 55 FPS
Testing mod pbo:agm_map
Test ran and got 55 FPS
Testing mod pbo:agm_markers
Test ran and got 54 FPS
Testing mod pbo:agm_movement
Test ran and got 54 FPS
Testing mod pbo:agm_nametags
Test ran and got 54 FPS
Testing mod pbo:agm_nightvision
Test ran and got 53 FPS
Testing mod pbo:agm_noradio
Test ran and got 54 FPS
Testing mod pbo:agm_overheating
Test ran and got 53 FPS
Testing mod pbo:agm_parachute
Test ran and got 53 FPS
Testing mod pbo:agm_ragdolls
Test ran and got 52 FPS
Testing mod pbo:agm_realisticnames
Test ran and got 53 FPS
Testing mod pbo:agm_recoil
Test ran and got 54 FPS
Testing mod pbo:agm_reload
Test ran and got 53 FPS
Testing mod pbo:agm_respawn
Test ran and got 53 FPS
Testing mod pbo:agm_resting
Test ran and got 54 FPS
Testing mod pbo:agm_safemode
Test ran and got 53 FPS
Testing mod pbo:agm_scopes
Test ran and got 53 FPS
Testing mod pbo:agm_smallarms
Test ran and got 54 FPS
Testing mod pbo:agm_switchunits
Test ran and got 54 FPS
Testing mod pbo:agm_thermals
Test ran and got 53 FPS
Testing mod pbo:agm_topdownattack
Test ran and got 53 FPS
Testing mod pbo:agm_vector
Test ran and got 54 FPS
Testing mod pbo:agm_vehicles
Test ran and got 52 FPS
Testing mod pbo:agm_weaponselect
Test ran and got 53 FPS
Testing mod pbo:agm_wind
Test ran and got 53 FPS
```

Obviously the signal is noisy, but that's probably related to other stuff happening on my machine during the test + thermal fluctuation + things that change in the simulation due to AGM (e.g. tanks that exploded don't after agm_armour).

All in all, I got only 2 fps of difference with all AGM modules loaded compared to the game with only CBA loaded.

The test is not perfect as there's probably no player.

**Comment by JonBons** [comment]
Agree'd, I finally got around to running the test and I saw the same sort of result.

I think a more demanding test (with player) will help exaggerate any hidden performance issues but I'm glad the script worked (it takes a while but it beats doing it manually.)

I'll probably be improving it sometime later to test performance issues with my community's modpack in terms of weapon/vehicle/etc perf hits with a better test mission.

**Comment by JonBons** [comment]
Alright here is version 2 with a much more intensive benchmark (has AI/Helos/Jets/Bombs/Explosions/etc)

https://dl.dropboxusercontent.com/u/1652088/Arma/A3_AGM_UnitTest_v2.zip

**Comment by Legolasindar** [comment]
I do a simple test, loading from the editor Altis with my soldier. I can only mesure to 60 FPS (my monitor no give more than 60).
With CBA+AGM = 55-60
Without addons = 60 or more.

**Comment by bux578** [comment]
> my monitor no give more than 60

disable VSYNC ?

**Comment by Legolasindar** [comment]
With V-SYNC DISABLED

With CBA+AGM = 53-71
Without addons = 60-82

My specs:

MB: Asus P8H67
CPU: Intel i7-2600 3,4 Ghz
Graphic: Nvidia Gigabyte GTX 970 WF3OC 4GB
RAM: 16 GB G.Skill

**Comment by Tachii** [comment]
Yep, same, i get something around 15fps drop with agm

**Comment by Tachii** [comment]
Video:

Fps with AGM: http://youtu.be/Dv2DpxcTODs

Fps without AGM: http://youtu.be/tVbVPTvJq8E

**Comment by Tachii** [comment]
That's a pretty big drop, with nothing happening at all. Just 1 unit

**Comment by esteldunedain** [comment]
Sorry guys, you are underestimating the amount of things AGM computes for the player, even if "nothing" is going on. You are seeing a big fps drop only because:

1 - You are running at 100~120 fps !!
2 - You are extremely cpu bound due to almost nothing being drawn (virtual reality with no additional units). So AGM scripts constitute a much-larger-than-normal proportion of everything going on on the frame.

That's far from normal usage condition, and hardly anything to worry about. 

That said, we are thinking on way to greatly improve AGM efficiency, but that will come latter down the line. Please be pacient about this on though.

**Comment by jonpas** [comment]
Patience young padawan... 

But I have to askyin what direction are you looking at?

**Comment by PaulKeeble** [comment]
You are taking about 3ms a frame when nothing is happen, which doesn't sound like much but its there all the time. The game has enough problems as is, this represents a big reduction in performance, at 30 fps its down to 27 because of AGM, at 45 its more like 40, so yes it shows up more at higher frame rates. The game is slow as is AGM doesn't need to make things worse. I don't know what happens to the timing under combat conditions but I suspect that the 3ms is growing and having a growing impact on the game. We can't accurately reproduce the performance problems we are seeing, this bug report was the start of a process to determine where the problems are coming from and the hope was you would investigate it and look into performance generally and the way it might grow under more strenuous conditions.

Obviously we need a scenario we can reproduce that shows you the issue for a wider problem, but right now here is a bug others have verified.

So I get it you don't think this matters, but it does to me or I wouldn't have raised it. So now you have closed my bug without fixing it. How I am meant to respond to that? Its not fixed so I should that close as either a can't fix or a won't fix or not a bug?  Because I don't agree its OK for 3 or more milliseconds to be completely dedicated to AGM when nothing is going on. The base game performs a lot better with recent patches but our game play hasn't seen a benefit. I am getting the distinct impression our problems lay entirely with AGMs performance and not just when standing around but during our games.

So since you have rejected the bug I need to raise this with the community so they know there is a problem with AGM right now. Since its not going to get fixed and the bug has been rejected without fix they also need to know that. BI is gearing up to blame mods for the performance problems and when the community isn't even willing to fix them, well then it gives BI all the ammunition it needs and it can just point to this bug report and say "see we told you its all the mods".

**Comment by commy2** [comment]
This is not a bug. When you test this in VA your FPS are entirely limited by the scripts you use, because there are no objects to render.

>BI is gearing up to blame mods for the performance problems and when the community isn't even willing to fix them, well then it gives BI all the ammunition it needs and it can just point to this bug report and say "see we told you its all the mods".

BI is not gearing up for anything. If you really believe that you have a very simplistic world view.

**Comment by esteldunedain** [comment]
As commy said. this is not a bug! AGM does a lot of calculations to achieve the things it does; man it has around 50.000 lines of code! 

Could it be optimized? Sure, and we are in fact working on it. It's just that we agreed measuring fps on single player when nothing is happening is not the correct way of measuring performance, so this ticket has no further use as-is. If any of you find concrete stuff to improve or at least a more correct way of measuring performance impact then you're welcome to open a separate issue. 


MP performance (the stuff we really care about) is related to other concepts, like the amount of scheduler threads spawned, the network traffic, etc, that are not measured at all in this test.

Of course if you think AGM performance is unacceptably bad based on this you always have the option not to use it. At the end of the day, we trade performance for features on all real time compturer applications.

**Comment by Tachii** [comment]
The lower overall fps the lower is the fps loss. And it dropes even if agm_core is launched, so maybe its because of some loops that use time related commands...

**Comment by CorruptedHeart** [comment]
FPS loss especially in the higher ranges does not give a full picture of [what is happening](https://books.google.co.za/books?id=F75bsvlmqQsC&lpg=PT364&ots=NAEwrqcjGt&dq=FPS%20inverse%20to%20frame%20time&pg=PT367#v=onepage&q&f=false).
