### ISSUE TITLE
Disable Team-Management module does not disable join group

### ISSUE THREAD

**Issue by captainblaffer** [KoffeinFlummi/AGM#2032]
Disable Team-Management module does not disable join group

How to reproduce:
1. Place module in editor: Interaction System - enable team management: No
2. Create mission with one AI and one player, blufor. different groups.
3. Join the AI's group using AGM interaction

**Comment by esteldunedain** [comment]
There you go.

**Comment by captainblaffer** [comment]
Thanks!
