### ISSUE TITLE
Binarizer "Stopped working" errors and PROJECTNAME

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#2035]
This started happening with today's Arma 3 Tools dev-branch (or so I am sure at least). Stopped working errors pops up randomly closer to the end of whole package binarization.

Second thing is PROJECTNAME doesn't support spaces and so "AGM Compatibility" uses `@agm_dev` instead of `@agm_compatibility_dev`. It's enough if in AGM Compatibility an underscore is added into the PROJECTNAME field, I just didn't want to spam the issues. I would fix it, but I have no idea how make the exe.

**Comment by commy2** [comment]
@KoffeinFlummi ?

**Comment by KoffeinFlummi** [comment]
No idea what's causing the crashes, although the dev-branch of the tools probably isn't helping; they're unstable enough as it is.

Fixed the underscore: https://github.com/KoffeinFlummi/AGM_Compatibility/commit/1635dde896a7de8fc0530536acd6c755d8fd1357

Will have to make the .exe once I'm home.

**Comment by jonpas** [comment]
Yeah, thanks!

**Comment by KoffeinFlummi** [comment]
Done: https://github.com/KoffeinFlummi/AGM_Compatibility/commit/7ff5cc287d1d9ada1ed90694c3801e7915bfd01d

**Comment by jonpas** [comment]
Thank you!
