### ISSUE TITLE
No_Radio Didn't download.

### ISSUE THREAD

**Issue by SnakexEyes** [KoffeinFlummi/AGM#2038]
I downloaded AGM from ArmaHolic and the pbo for No_Radio didn't download, just wondering i there is a place where I could download it from thanks.

**Comment by PabstMirror** [comment]
Just checked armaholicand both links for me contain agm_noradio.pbo.

Try downloading from: https://github.com/KoffeinFlummi/AGM/releases (green button for the zip)

**Comment by SnakexEyes** [comment]
cool, thanks for that, checking it now, I'll let you know if it worked.

**Comment by SnakexEyes** [comment]
@PabstMirror It worked, thanks a bunch.
