### ISSUE TITLE
AGM_Markers - scripting errors on HC

### ISSUE THREAD

**Issue by Astavinu** [KoffeinFlummi/AGM#2039]
first error accured after 16h mission runtime

 2:00:11 [AGM] Client: agm_core is Version 0.95.
22:08:29 Error in expression <
_config = (configfile >> "CfgMarkers") >> (_data select 0);
if (!isClass _confi>
22:08:29   Error position: <>> (_data select 0);
if (!isClass _confi>
22:08:29   Error >>: Typ Zahl, erwartet Zeichenfolge
22:08:29 File AGM_Markers\functions\fn_setMarkerNetwork.sqf, line 8
22:08:29 Error in expression <
_config = (configfile >> "CfgMarkers") >> (_data select 0);
if (!isClass _confi>
22:08:29   Error position: <>> (_data select 0);
if (!isClass _confi>
22:08:29   Error Allgemeiner Fehler in Ausdruck
22:08:29 File AGM_Markers\functions\fn_setMarkerNetwork.sqf, line 8

**Comment by PabstMirror** [comment]
I rewrote this function from taking an index, to taking a string to fix the problem with #1966.

"Typ Zahl, erwartet Zeichenfolge"

I think what happened is that someone with an older version of agm (anything before 0.952) connected.   When they place markers they still send numbers and cause script errors.

If you could get everyone to double check their mods.  Also, you may want to consider using the verify mods module from AGM.

**Comment by commy2** [comment]
Someone definitely had an old version. Probably 0.951

>If you could get everyone to double check their mods.

Won't work due to Flummi not using proper version __numbers__

**Comment by esteldunedain** [comment]
He beat me to it

**Comment by Astavinu** [comment]
Someone definitely had an old version. Probably 0.951

thx, i'll use the mods module to get this fixed :)

**Comment by esteldunedain** [comment]
@Astavinu, @commy2's point is that the mods module won't kick people with 0.95.1 in 0.95.2 server. You could properly set addon signatures to prevent that though

**Comment by jonpas** [comment]
> Won't work due to Flummi not using proper version numbers

What exactly do you mean? I guess not version things in CfgPatches, because they are correct.

**Comment by bux578** [comment]
> Won't work due to Flummi not using proper version **numbers**

![200](https://cloud.githubusercontent.com/assets/1235520/5954141/bac33d6e-a793-11e4-8eaa-d913f77b9c92.gif)


http://semver.org/

**Comment by jonpas** [comment]
Ah yes, that's important. -.-

Though the module compares version strings, so why wouldn't it work exactly?

**Comment by commy2** [comment]
Because it parses those Strings to NUMBER (via `parseBumber`) so it can judge whether something is newer or older (>, <).
0.95.1 and 0.95.2 get both parsed to 0.95, because actual numbers never have 2 dots. I told Flummi about this beforehand, but he didn't care. Semver is some sort of holy grail to IT guys.

**Comment by KoffeinFlummi** [comment]
To quote Wikipedia:

> Version numbers very quickly evolve from simple integers (1, 2, ...) to rational numbers (2.08, 2.09, 2.10) and then to non-numeric "numbers" such as 4:3.4.3-2. These complex version numbers are therefore **better treated as character strings**. Operating systems that include package management facilities (such as all non-trivial Linux or BSD distributions) will use a distribution-specific algorithm for comparing version numbers of different software packages. For example, the ordering algorithms of Red Hat and derived distributions differ to those of the Debian-like distributions.

In other words: commy writes shitty code that fails in the most basic of use cases and then tries to blame the specification.

**Comment by jonpas** [comment]
I see. :p
