### ISSUE TITLE
Dyanmic tunnel vision as result from percent blood lost. 

### ISSUE THREAD

**Issue by Ataraxic89** [KoffeinFlummi/AGM#2041]
Right now you go straight from clear "clear" vision (excluding the bleed effect) to unconscious with a bunch of black around the edge. 

Would it be possible so that when a player loses blood, but is still conscious and controllable that their vision should become blurry, they should get tunnel vision? Blackening around the edge of the screen that grows and culminates in the near total blackness of unconsciousness along with progressively dampened hearing.

Sorry if repeat of issue, haven't fully caught back up on all the open issues.

**Comment by esteldunedain** [comment]
Mmm, no, I don't think so. Currently, as you loose blood the colors deam similar to DayZ (toward grayscales). We like that effect more than bluring vision or tunneling.

**Comment by Ataraxic89** [comment]
While I don't mind the rejection of the idea

> Mmm, no, I don't think so.

Sounds rather passive aggressive. Did I offend you?  Sorry if so.

**Comment by jonpas** [comment]
I was discussed in another issue already, and decided against due to the reason esteldunedain mentioned.

**Comment by esteldunedain** [comment]
> Sounds rather passive aggressive. Did I offend you? Sorry if so.

No @Ataraxic89, sorry if I gave that impression. :cry:  I was not offended nor intended to sound agressive. Keep in mind english is not my native language so it's difficult to judge tone some times.
