### ISSUE TITLE
Intel from maps

### ISSUE THREAD

**Issue by DrunkIrishGuy** [KoffeinFlummi/AGM#2044]
Can we have a feature  where when we pick up an enemies map it shows all the markers that were marked in their side/group/vehicle chat? maybe have it work with F3 markers to? (Up until the point of their death) would be awesome and would make looting enemy bodies a bit more valuable

**Comment by commy2** [comment]
Markers are synched by the game. I don't think there is a way to access them. Even if there is a work around, I don't like the idea. Not worth it imo.

**Comment by bux578** [comment]
Nontheless thank you for yor feature request.


What about a "Copy Map" Interaction on bodies?

**Comment by commy2** [comment]
If you really wanna implement this, bux, feel free to reopen it. I'm not a final authority or anything.

**Comment by bux578** [comment]
:rose:

**Comment by DrunkIrishGuy** [comment]
Yes bux yes!!
