### ISSUE TITLE
Request to make helicopters less prone to exploding for no reason

### ISSUE THREAD

**Issue by AndrewKopczynski** [KoffeinFlummi/AGM#2045]
Hiya, I saw that cars don't explode anymore in AGM, and thought it was a really great change. I was hoping you could do something similar for helicopters.

Currently, if a helicopter flips upside down at 0km/h, it explodes. This is both annoying and not that fun. Helicopters sometimes roll when landing hard, and it's really silly to see a helicopter land, roll over, and then explode because it turned upside-down.

I don't know how hard this would be to implement, but I'd love to see it happen. It's a lot more fun/immersive to have to pull your buddies out from a bad helicopter rollover than it is to instantly die and stuff.

**Comment by PabstMirror** [comment]
#1840 - waiting on stuff from BIS to fix choppers

**Comment by AndrewKopczynski** [comment]
Thanks, wasn't aware there was an open topic for this.
