### ISSUE TITLE
adding logical items?

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#2047]
I don't fully understand how the script for adding logicial items to vehicles. Can someone explain where to put the script to?

**Comment by esteldunedain** [comment]
Welcome to the club!

Just kidding, it's a bit confusing. Logistical items are "real" items, so you have to create them using createVehicle before you can load them. Luckily there's a couple of functions to streamline that:

```sqf
// Create the object far from the map
_item = ['AGM_SpareWheel', [-1000, -1000, 100]] call AGM_Logistics_fnc_spawnObject;
// Load that object to _vehicle
[_vehicle, _item] call AGM_Logistics_fnc_initLoadedObject;
```

You can replace `'AGM_SpareWheel'` for the classname of any loadable object.

**Comment by jonpas** [comment]
This should explain it well enough: https://github.com/KoffeinFlummi/AGM/wiki/For-Mission-Makers#28-adding-logistic-items-to-vehicles

**Comment by kripto202** [comment]
so basically I have to put the spare tire on the map first and put the script into the vehicle init on what @esteldunedain said?

**Comment by esteldunedain** [comment]
> so basically I have to put the spare tire on the map first and put the script into the vehicle init on what @esteldunedain said?

No, the first line of the script I posted already creates the wheel on the map for you. The second loads it to the vehicle.

**Comment by kripto202** [comment]
and where do you place it? init or the vehicle init?

**Comment by esteldunedain** [comment]
Write this on the vehicle init:
```sqf
null = this spawn {
  waitUntil {!isNil "AGM_Logistics_loadedItemsDummy"};
  for "_i" from 0 to 3 do {
    _item = ['AGM_SpareWheel', [-1000, -1000, 100]] call AGM_Logistics_fnc_spawnObject;
    [_this, _item] call AGM_Logistics_fnc_initLoadedObject;
  };
  for "_i" from 0 to 5 do {
    _item = ['AGM_JerryCan', [-1000, -1000, 100]] call AGM_Logistics_fnc_spawnObject;
    [_this, _item] call AGM_Logistics_fnc_initLoadedObject;
  };
};
```

**Comment by kripto202** [comment]
its working now thanks @esteldunedain

**Comment by esteldunedain** [comment]
NP, you're welcome
