### ISSUE TITLE
add a module on default logical items inside vehicles

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#2048]
Is it possible where you can add a module where you can define how many spare tires, spare tracks, and jerry cans inside vehicles on mission start?

**Comment by esteldunedain** [comment]
No, I don't think so. Logistics will be rewriten, so this may change and there's no point on adding this now. Just create a script like this one:

https://github.com/KoffeinFlummi/AGM/wiki/For-Mission-Makers#28-adding-logistic-items-to-vehicles

And run it on the units you wants.
