### ISSUE TITLE
Titan Rockets inside of inventory turns into PCML when using VA

### ISSUE THREAD

**Issue by BARASOAP** [KoffeinFlummi/AGM#2049]
Upon using the Virtual Armory, any Titan rockets inside of the player's inventory are converted to PCML rockets.

**Comment by commy2** [comment]
Doesn't happen for me. Neither with the AA nor both AT Mini-Spike missiles.
Can you please elaborate what you are doing? One sentence is very brief for a bug report.

**Comment by BARASOAP** [comment]
Issue isn't one of AGM. Sorry.
