### ISSUE TITLE
Is AGM removing the Night vision goggles?

### ISSUE THREAD

**Issue by Ataraxic89** [KoffeinFlummi/AGM#2055]
I dont see this feature anywhere on the wiki but my only other mod is bCombat which I dont think it is doing it. 

Assuming it is AGM, how do I stop it? I see that if I initialize my unit with the gen3 (standard) one it still removes it but if I give him the gen4 it doesnt remove it. 

I like this feature overall, removing NV goggles from all the basic units. But it needs way more controllability.

Disregard if this somehow isnt coming from AGM.

**Comment by esteldunedain** [comment]
> I like this feature overall, removing NV goggles from all the basic units. But it needs way more controllability.

What do you mean with this? AGM shouldn't remove NVG under any condition.

**Comment by esteldunedain** [comment]
@Ataraxic89, I took a quick look at bCombat. I found it does try to remove NVGs under certain conditions, but only for types `NVGoggles`, `NVGoggles_OPFOR` and `NVGoggles_INDEP`. That's why our custom NVGs bahave different than those from the base game.

**Comment by Ataraxic89** [comment]
Thanks. I only did a quick ctrl-f for it on their page and didnt see it. Sorry.

**Comment by Ataraxic89** [comment]
Where did you see that it removes it? I still dont see it. I believe you, I just want to turn it off lol

**Comment by esteldunedain** [comment]
There's a function for removing them on line 887 of `lib/common.sqf` and it's called on line 834 of that same file

**Comment by Ataraxic89** [comment]
They added a line in the config file for it. I just set it to false. yay. Sorry for confusion :D
