### ISSUE TITLE
Add speed boost to the salt flat

### ISSUE THREAD

**Issue by Ataraxic89** [KoffeinFlummi/AGM#2063]
This is a feature request to, if possible, give the same speed boost you get on roads to the salt flats. 

I actually suggested this a couple years ago and a BIS person said they may do it but it seems they never did. 

I dont think it has any negative effect on gameplay, it is realistic (many land speed records are set on salt flats), and it means you can make custom race tracks on the salt flat. 

I know its a little different but it seems it would be a minor thing. But I dont know how that bonus works so maybe its beyond the scope of a mod.

**Comment by PabstMirror** [comment]
The salt flats are surface type "GdtDead", but any number of areas could use that same type, so it's a little iffy to modify them (other maps could be reusing the same surface).

Just for fun I tried modifying maxSpeedCoef, but it didn't have much effect.  I think the coefficent is only for decreasing speed (so range [0..1]).  Still default is 0.9, so bumping it up to 1 should do something.

Probably not an agm thing, but feel free to build and use:

```
class CfgPatches {
    class AGM_Sonic {
        units[] = {};
        weapons[] = {};
        requiredVersion = 0.60;
        requiredAddons[] = {AGM_Core};
        version = "0.95.2";
        versionStr = "0.95.2";
        versionAr[] = {0,95,2};
        author[] = {"commy2"};
        authorUrl = "https://github.com/PabstMirror";
    };
};
class CfgSurfaces {
    class Default;
    class GdtDead: Default {
        maxSpeedCoef = 3; //gotta go fast
    };
};
```

**Comment by commy2** [comment]
>author[] = {"commy2"};

**Comment by PabstMirror** [comment]
sorry just copied another config

**Comment by Ataraxic89** [comment]
Wait, so is it wont fix or a milestone? How can it be both lol

**Comment by commy2** [comment]
Who cares!

We won't include it in AGM, but the solution is right there if you want to add it on your own.
