### ISSUE TITLE
Is it not possible to wake up and treat yourself anymore?

### ISSUE THREAD

**Issue by Meiestrix** [KoffeinFlummi/AGM#2067]
Since 0.95 (not 100% sure)  we noticed in nearly all of our missions that it is not possible to wake up from unconsciousness and treat yourself anymore.
You always fall back unconscious after roughly 2 seconds.
We tried to lower the bleeding speed to 0.8 but even this does not help.

Does anyone else have this problem, or have you changed someting?

**Comment by kripto202** [comment]
its the pain that makes you fall unconscious and lack of blood.

**Comment by Meiestrix** [comment]
Yes, I know. but some versions ago ist was possible to treat yourself sometimes.
With the latest versions this never happened.

**Comment by KoffeinFlummi** [comment]
In v0.95 the bleeding speed was buffed quite a bit. If you want to go back to the old values you should try a bleeding speed of 0.5-0.6.
