### ISSUE TITLE
Multiple fast shoots is less effective than single shots

### ISSUE THREAD

**Issue by LongshotPhil** [KoffeinFlummi/AGM#2070]
So after some testing to find out my I could unload half a mag or more into an AI and not kill him, shooting him in the chest 5 meters away...

I believe that AGM is at fault. I first noticed that it would take large amounts of fire to kill an AI (or human) if using full auto or just "Double Tapping".  But when you single firing with a second break, you can kill them completely in 3-4 shots.

I then removed AGM completely and did it again. But this time in single or in full auto the AI (or Human) would die in 2-3 chest hits.

Anyone else having this problem, and if so any fixes?

**Comment by BaerMitUmlaut** [comment]
The bullet doesn't care if you fire full auto or semi auto, it only changes its dispersion as far as I know. Damage is defined in the ammo config and depends on where you hit, the targets body armor and how fast the bullet is travelling.

I'm not sure how you manage to not kill somebody after 15 shots to the chest from 5 meters - if they all hit. It might just be that you're not hitting them because AGM changes the rifles dispersion in AGM_Ballistics.

**Comment by LongshotPhil** [comment]
Well I would agree with you on that, but there are two things that are wrong.
First I do not use AGM_Ballistics, and second when i was first aware to the problem I thought that people where just missing their target too. But after some pretty lengthy testing, I can assure you that I hit 15 out of 15 shoots or 4 out of 4 (I promise i did not miss).

Also i did double check all my configs to make sure it was not on my end before posting this here.

So, I was think that it could be something in the AGM_Medical doing this. Because the first shot does impact and looks like it deal damage to human and AI alike, but it is the very next impact (as long as it was fired quickly) that does either little or no damage. And I got the impression that the medical addon needed time "to do its things", and it either did not detect the second rapid shot or it skips the first shot and moves to the last detected hit.

**Comment by kripto202** [comment]
video maybe?

**Comment by LongshotPhil** [comment]
Will do, stand by

**Comment by esteldunedain** [comment]
@LongshotPhil, I'm curious about what you changed in the server; can you elaborate? I've observed stuff similar  to this in the past too.

**Comment by jonpas** [comment]
Same here, would lovr to hear what you changed, always looking to improve our server performance.

**Comment by LongshotPhil** [comment]
I change the maximum message send and guaranteed to 512. Change the minimum Bandwidth to 1 meg and max to 2 gigs.
This increase the preformance on the server so that everyone can connect without desync issues.
I can go a little more in detail if you wish, just let me know.

**Comment by bux578** [comment]
>I can go a little more in detail if you wish, just let me know.

Yes, please.

**Comment by LongshotPhil** [comment]
Ok.

So if you see the server is not using bandwidth that it could use, try and increase the values "MaxMsgSend" and "MinBandwidth". This will increase the amount of data that the server can play with.

Here is my basic config file used by TADST (it is edited to save space):
MaxMsgSend = 512;
MaxSizeGuaranteed = 512;         (Bytes)
MaxSizeNonguaranteed = 256;   (Bytes)
MinBandwidth = 1048576;           (1024 kbit/s)
MaxBandwidth = 2097152000;    (2000 mbit/s)
MaxCustomFileSize = 1310720;  (160 kB)

Those values i currently run and support 30 members descent. (note the changes I made recently are applied and already have been tested to make sure, all players seen less "lag". Also the mentioned problem above was fixed)
Also I have "-enableHT" at the end of my parameters. Hyper-threading increases system performance when dealing with large amounts of players and when large amount of "things" are at hand (ie. Firefights, explosions, air support...). 

With all these things working together the average frames for a multi-player game is around 30+ (depending on their computer).

Needless to say, everything is working better for my server and group.
If you would like more information please message me on steam: LongshotPhil (http://steamcommunity.com/id/LongshotPhil/)

**Comment by jonpas** [comment]
Thank you for that! As for server fps, I suggest you give headless client a try, last month we were running it with every mission and observing fps it never dropped below 45 (except spawning with Zeus and similar), and that's with about 25-30 players and a ton of AI.

**Comment by LongshotPhil** [comment]
We do use headless client, but that depends on the scale of the mission(s).  I try not to use it so much, but have the mission makers place units in good places and have them create special objectives that do not require as much AI or scripts. Overall both work really well tho.

**Comment by jonpas** [comment]
Headless client really improves the reactions and makes AI much more "human" so to say, we use it in every mission now and it's great fun.

Thanks for all the config you posted, I will fiddle with it for sure!
