### ISSUE TITLE
AGM NVGs (Colors)

### ISSUE THREAD

**Issue by Feivel69** [KoffeinFlummi/AGM#2071]
Hi guys.

Do you plan to make the AGM NVGs available in at least two different colors per generation?
Since you use Vanilla-A3's NVGs as Generation-3 types (if I'm right), it's the one generation where we can choose all three colors (Black,Brown,Green), but Gen-1 is only available in black, Gen-2 only in green and Gen-4 + Wide are only available in brown.

Best regards.

**Comment by sagjangi** [comment]
There are some great NVG models out there. PVS-7s (AVInd_US), PSV-14s and 15s (RHS) and Task Force Apache has some as well that now of. The model would be a great way to differentiate NVG generation if anyone willing to contribute them.

**Comment by KoffeinFlummi** [comment]
I don't think any of us are really interested in doing that at the moment. Feel free to do that yourself and shoot us a pull request though.
