### ISSUE TITLE
Custom SelfInteraction Entries (Order)

### ISSUE THREAD

**Issue by Feivel69** [KoffeinFlummi/AGM#2072]
Hello.

Actually, this is a really low priority request.

If you add custom entries to AGM self interaction menu, they will move "Repack Magazines" upwards and also custom Entry-1 to Entry-3 will show up from bottom to top.

(Picture)
http://extrazoom.com/image-27575.html?heuln50x50

Maybe you want to fix "Repack Magazines" so it's always in the same spot (since it's a steady AGM option), maybe on position of custom Entry-1 (Picture) and have the custom entries go from top to bottom. Quasi just opposite order of how it is now. I don't know, it's just a feeling haha, maybe you did it how it is on purpose.

Best regards.

**Comment by jonpas** [comment]
Doing this by function or config? In config you have to set `priority` value accordingly, lower value means it displays later and vice-versa IIRC.

**Comment by Feivel69** [comment]
I am doing this inside a script with 

0 = 0 spawn { CHVDAGM = ["View Distance", {true}, {[] call CHVD_fnc_openDialog}, true] call AGM_Interaction_fnc_addInteractionSelf;};

I tried it now with using 'priority'-argument with numbers from 1 to 10, here are my results:

Picture:
http://extrazoom.com/image-27591.html?heuln50x50

What numbers do I have to use to hit "Custom Entry 1", "Custom Entry 2" and "Custom Entry 3"?

Regards.

**Comment by jonpas** [comment]
It's not based on actual numbers, but the order of them, so it totally matters what other entries' priority numbers are.

Priority can be any number, even negative, for example it can be 1, 2, 3, 4... or it can be 1.1, 1.2, 1.3...

**Comment by Feivel69** [comment]
Ah, I see.

-2 will place the first custom entry above "Repack magazines". That's good enough for me :)
But is it possible to have the first custom entry 3 positions above "Repack magazines" without using 2 more custom ones?
 
##########Self-treatment
#####First Custom Entry
##Empty
##Empty
#####Repack magazines

**Comment by jonpas** [comment]
You can make empty entries, but without any function attached to them (they will still be buttons but clicking on them won't do anything. I know that's possible with config implementation, but for the addInteractionSelf function I am not sure, best if you try it. ;)

**Comment by Feivel69** [comment]
I thought about it too, to make empty entries, but I think I will just stick with it now. I was bothered most by the "repack mags" entry being moved. Thanks a lot for quick help, much appreciated.

**Comment by jonpas** [comment]
No problems, happy to help. ;)
