### ISSUE TITLE
Reduce carry animation time?

### ISSUE THREAD

**Issue by sagjangi** [KoffeinFlummi/AGM#2073]
As it is now the animation to carry/load an unconscious soldier is very long. It doesn't take but a few second to load up a casualty and move out IRL. This would allow/make it worthwhile to move a casualty back to a CCP instead of always having medics move to the casualty.

**Comment by jonpas** [comment]
I believe that's due to unsuitable animations in the game, and as said before unless an animator is willing to donate to AGM, things like that won't be changed.

**Comment by sagjangi** [comment]
Is it possible to remove the animation entirely and just have the unconscious soldier move from the ground to the being carried state? Breaks immersion a little bit but not too bad. 

I don't know any computer black magic or I'd contribute for sure. Love this mod guys.

**Comment by bux578** [comment]
Drag the wounded to safety then start carry him.

I don't like the teleport option ...
