### ISSUE TITLE
Medic Menu order

### ISSUE THREAD

**Issue by BullHorn7** [KoffeinFlummi/AGM#2074]
At the moment using the medicine menu is confusing and takes too long to navigate.

The 'circle' has 10 buttons
Bottom middle should be Torso or Head. Right side of the 'circle' should be the right side of the body, left side for the left side of body.

Also Carry and Drag should be on opposite sides so that muscle memory can take place after a few uses and you'll instantly know to go either fully left/right for the action you want.

I realize the menu's buttons go in a clockwise fashion but if you can't fix it, you can probably just add dummy buttons that retrieve you into the same menu you were in.

**Comment by bux578** [comment]
Thanks for your contribution.

**Comment by bux578** [comment]
duplicate #1899
