### ISSUE TITLE
Chance to fail on bloodbags

### ISSUE THREAD

**Issue by OnkelDisMaster** [KoffeinFlummi/AGM#2076]
Bloodbags should have a chance to fail, if a non-medic tries to apply them. This could be combined with a probabiltiy in the module. A fail would mean, that no blood was given to the patient, and the item would be lost. This would be realistic, because a soldier is not trained to give a blood transfusion, but medics are. If a soldier has to give a transfusion anyways, there should be a chance to fail (for example the needle didnt hit the vein. As an alternative the allow-non-medic function should be separated in "allow-non-medic-bloodtransfusion", "allow-non-medic-epi" and "allow-non-medic-all"

**Comment by hopstar117** [comment]
An addition to this is the medic item selection system about what items medics can only use, would it be possible to have the module setup so that mission makers can choose whether players can use each individual medical item

**Comment by BaerMitUmlaut** [comment]
So if you don't hit the vein on the first try you accidentally the whole bloodbag?

**Comment by Illysp** [comment]
While this is interesting, you can't give blood bags to yourself. So medics have a percent chance to have blood wasted despite being able to "show" someone how to do it.

**Comment by OnkelDisMaster** [comment]
If you didnt notice that you missed a vein "the blood running in the patient the wrong way". That might sound strange, but its relatively hard to hit a vein without medical experience.

**Comment by KoffeinFlummi** [comment]
I feel like this is out of scope for AGM_Medical, so I wouldn't want to implement it. If someone else wants to, I would probably think about merging it.
