### ISSUE TITLE
Can't take out anything inside other player's backpack

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#2080]
I'm not sure it is something I'm not seeing but my group can never take anything out of another person's backpack. This is necessary if the medic or corpsman needs someone to take something out of his bag and help treating someone.

**Comment by commy2** [comment]
Yea, that never worked for me since alpha. You probably have a `removeUniform` + `addUniform` command anywhere in your mission (maybe loadout scripts, VA or anything similar)

http://feedback.arma3.com/view.php?id=19829
