### ISSUE TITLE
Check PBOs "Kick" option broken

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#2081]
If Check PBOs module is set to Kick, it doesn't kick, but displays a large red box with the conflicting mods. Was also reported on [BI forums](http://forums.bistudio.com/showthread.php?178253-Authentic-Gameplay-Modification&p=2876671&viewfull=1#post2876671).

**Comment by Tachii** [comment]
It would be great if AGM team will decide to move functionality of CheckPbo from module to function. :)

**Comment by BaerMitUmlaut** [comment]
@Tachii: You can already do that: `[0, true] call AGM_Core_fnc_checkPBOs;`

I think it doesn't work because according to the BI wiki, serverCommand must be executed from an UI event handler.

**Comment by Tachii** [comment]
@BaerMitUmlaut According to this it won't work
https://github.com/KoffeinFlummi/AGM/issues/1981

**Comment by commy2** [comment]
Yes. Thats not supported. Also you went slightly off topic Tachii ...

`serverCommand` does not have to be executed from somewhere specific. The limitation of AGM_Core_fnc_adminKick is that there has to be a admin loged in for it to work.

A better implementation would maybe be something like
`findDisplay 46 closeDisplay 0;`
to kick the player.

**Comment by jonpas** [comment]
So if I log in as admin and someone joins with incorrect mods, then they should get kicked? Because that did NOT happen, I was 100% logged in as I was monitoring server FPS, and there was another one that just joined telling me he has the screen, but he didn't get kicked.

**Comment by BaerMitUmlaut** [comment]
>**NOTE**: This command must be executed from UI event handler (ctrlAddEventHandler, displayAddEventHandler), such as *onButtonDown* or other User_Interface_Event_Handlers.

Src: https://community.bistudio.com/wiki/serverCommand

**Comment by commy2** [comment]
^ That's not true.

**Comment by commy2** [comment]
Did some testing and it turns out that `serverCommand` does not work on dedicated servers. I'll change it to the other method I mentioned.
