### ISSUE TITLE
[Feature Request] Crew Served Weaponry

### ISSUE THREAD

**Issue by Khaosmatic** [KoffeinFlummi/AGM#2082]
Hi,

Back on ACE in ARMA 2 I'm sure most people know of its CSW system that allowed some really cool gameplay to be created. Like being able to carry ammo for the MGs or making the Mortar actually something skillful (I never worked it out) and it is something I was disappointed at how ARMA 3 didn't have anything like that besides disassembling the weaponry.

I think I recall this idea being discussed about for AGM before but I cannot remember exactly whether or not it was and if it was closed as an idea. I never really got to be a part of weapons teams back in the ACE days whereas now I can be, just not to  the same level of fun.

Already (I think at least) we can drag static weapons and load them into vehicles but giving them ammo that must be reloaded and can be carried and making mortar gameplay interesting would be an amazing feature for AGM.

Sorry if this has been put up before.

**Comment by PabstMirror** [comment]
looks like this should be part of #1937 (Logistics rewrite)

**Comment by Khaosmatic** [comment]
Roger that.
