### ISSUE TITLE
be able to choose which side to get out of

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#2084]
Give people to choose which side to get out of via scroll wheel. This can be good when you have to get out on a certain side of the vehicle if there is an ambush or there is no place for someone to walk on. This can be limited for people only in passenger seats and only on vehicles where there is a side you can get out of.

**Comment by KoffeinFlummi** [comment]
No. Stuff like this is almost impossible to do properly while maintaining compatibility with all the vehicle mods out there.
