### ISSUE TITLE
All PIP fail after 0.95.1?

### ISSUE THREAD

**Issue by JinougaF** [KoffeinFlummi/AGM#2085]
http://imgur.com/Lsd5Aam,bSWm9fR

like this.

**Comment by PabstMirror** [comment]
I don't think AGM touches pip (I think they are part of the models)
Can you try with 0.95.2 (https://github.com/KoffeinFlummi/AGM/releases/download/v0.95.2/AGM_v0.95.2.zip).
And what is your PIP settings set to in video options?

**Comment by JinougaF** [comment]
I'm gonna close this,just confirm not a AGM fault.
