### ISSUE TITLE
Weapon Lowering

### ISSUE THREAD

**Issue by schnip** [KoffeinFlummi/AGM#2090]
Since I have started using AGM, I have found that double-tapping ctrl no longer lowers/raises my weapon. Is this intentional? Has this been rebound by AGM to something that I cannot find in the menu, or will I need to rebind that from the vanilla binding?

**Comment by PabstMirror** [comment]
Are you running 0.95.2 (https://github.com/KoffeinFlummi/AGM/releases/tag/v0.95.2)

Should have been fixed with #1988 (e2e9bb70824b7a319da5955ef92098c744435868)

**Comment by schnip** [comment]
Confirmed fixed, thanks for the quick reply, sorry for not running the latest version. (I have been using .95.2 off of Armaholic from a few days ago)
