### ISSUE TITLE
Ammo Box with increased capacity

### ISSUE THREAD

**Issue by Neodyn** [KoffeinFlummi/AGM#2091]
An special AGM ammobox with a higher capacity for Items.

**Comment by hopstar117** [comment]
My question would be why?? as in what purpose does this give and what gain does it serve?

**Comment by Neodyn** [comment]
Imho is it not possible to put the a long list of Items in a vanilla ammobox. You can use these boxes for logistics operartions e.g.

**Comment by AndrewKopczynski** [comment]
Even the giant Huron containers are limited to 64 items, this would be a welcome feature if it's something AGM can change.

**Comment by ThecMaster** [comment]
Why not just put in some more boxes when you make a mission? problem solved, I guess. 

When you say logistics operation do you then mean that you are going too move that box?

**Comment by Neodyn** [comment]
Yes i will move them e.g via slingload or HEMETT

**Comment by AndrewKopczynski** [comment]
@ThecMaster It's just very silly that an entire shipping container can only hold 64 magazines and nothing else (unless you want to force players to use the BIS arsenal and set unlimited quantities of items). And yeah we're talking about containers you would move from a base into the field of operation or whatever for your mission.

**Comment by ThecMaster** [comment]
I play with a clan and we use slingload for resupply, we have boxes with more than 64 items.  Not only BIS. Our problem are weight. Thou we don't use HEMETT at all. Only helis. We also use smaller boxes that we can drag and load them in to helis. 

Mabye this is a problem obit that I can't see that without thinking about weight.

**Comment by commy2** [comment]
Something like this already exists. Classname is AGM_Box_Misc. It can hold a basically unlimited amount of each item type and is only really limited by the load (sum of the item masses).

https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Core/config.cpp#L802-L816

Just use:
```
if (isServer) then {
  clearWeaponCargoGlobal this;
  clearMagazineCargoGlobal this;
  clearItemCargoGlobal this;
  clearBackpackCargoGlobal this;
};
```
in the init box before adding your stuff.
