### ISSUE TITLE
Change: no left hand - weapon IK in combat pace

### ISSUE THREAD

**Issue by commy2** [KoffeinFlummi/AGM#2095]
Reminder: https://github.com/KoffeinFlummi/AGM/commit/97f096d214a2c4b0adba1ce174fba7079bb445c1

**Comment by commy2** [comment]
Reopen for testing

**Comment by Tachii** [comment]
When you walk, left hands spins too much, works fine when running

**Comment by commy2** [comment]
Seems to work otherwise. The issue with the m249 is a result of their hand position on the weapon being very close to the body. The Arm is interpolated from hand to body by the game itself.
Unfortunately it's not possible to define which weapon should have the old, default position and which the new IK version.
