### ISSUE TITLE
Engine On hotkey breakes analogue throttle

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#2097]
I am not entirely sure this is AGM's fault, but it looks like it is. Tested on AGM 0.95.2.

If you go to a fixed-wing aircraft and turn on the engine via scroll-wheel, everything works as it should. If you turn it on via Engine On hotkey from AGM analogue throttle input is not recognized.

I also noticed that after turning on the engine with AGM's hotkey, leaving the aircraft and going back in turns it on automatically and many times you can't turn it off with Engine Off, neither AGM's hotkey nor scroll-wheel.

**Comment by jonpas** [comment]
After doing some more digging, even using scroll-wheel it happens... damn you Arma.

**Comment by commy2** [comment]
You should open a issue on BI's issue tracker. Unfortunately I can't test this, because I don't own an analogue throttle.
http://feedback.arma3.com/

**Comment by PabstMirror** [comment]
Try removing AGM_Vehicles.pbo and see if you still have issues.
