### ISSUE TITLE
Holstering weapon in an FFV Seat makes you stand up

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#2098]
When in any FFV (firing from vehicles) seat you can holster your weapon (AGM keying: 0) which makes you stand up. When taking the weapon back out you keep standing.

It would be just perfect but that I wouldn't want fixed if it would seat you back down, but you keep standing up and that makes it very unrealistic. While standing up and saluting while driving in the base is awesome, haha.

**Comment by PabstMirror** [comment]
This seems like it might be a little dangerous:
![untitled](https://cloud.githubusercontent.com/assets/9376747/6198473/60f8f5e8-b3c9-11e4-810a-805ecba3b744.jpg)

Reproduced in both hemmit, and little bird.  Get in with a long gun, and press 0.

**Comment by PabstMirror** [comment]
`stance player` is "STAND" from a FFV so AGM_Core_fnc_fixLoweredRifleAnimation was causing problems

**Comment by jonpas** [comment]
:+1:

**Comment by kripto202** [comment]
wondering why would you holster your weapon in the FFV seat?

**Comment by jonpas** [comment]
>When taking the weapon back out you keep standing.
