### ISSUE TITLE
Minor: Missing Scope-Adjustments

### ISSUE THREAD

**Issue by waerna** [KoffeinFlummi/AGM#2099]
I think there is a scope missing somewhere in AGM_scopes. It's the sniper-scope from rhs-mod:

http://doc.rhsmods.org/index.php/USAF_Attachments 
classname: rhsusf_acc_LEUPOLDMK4

it isn't configurable with your mildot-system but still with the vanilla +/- 100m increments. 
Since the gun is listed in your spotter-webapp i thought the scope should be in the same system.

**Comment by esteldunedain** [comment]
Thanks. For AGM compatibility with other mods check the AGM Compatibility Project: https://github.com/KoffeinFlummi/AGM_Compatibility

We have pbos there for RHS and other mods adding stuff like this, that we cannot include inside AGM itself. Scopes adjustment for that scope is included there.

Regards
