### ISSUE TITLE
allow people to pull up a 9-line handbook

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#2102]
There are people out there that uses a 9-line over the radio and some people still don't know the 9-line. It would be really interesting if you can pull up a small handbook that you can look at the 9-line, and maybe write down, for CAS, arty, medevac and any others if needed. This item can be like a map tools and be pulled up trough the equipment section.

**Comment by Trigger81** [comment]
Use this addon: http://www.armaholic.com/page.php?id=28180

...

**Comment by kripto202** [comment]
tried it already and it won't come up for me and I even changed the controls

**Comment by esteldunedain** [comment]
Guys, sorry, we won't be adding anything like this to AGM. In my opinion (which AFAIK is shared be the rest of the devs), everything your soldier need to have as notes (like these 9-liners, the range tables, etc) you should have on real paper sitting right next to your pc. No need to code UI to simulate paper when you can have the real deal!
