### ISSUE TITLE
AGM_AI breaks disableAI

### ISSUE THREAD

**Issue by rlex** [KoffeinFlummi/AGM#2105]
I have a mission (DUWS) which i want to use with AGM AI Tweaks, but that not possible
There is a stationary unit (officer) which needs to stay at base. Looks like this:
```
_group = createGroup west;
_hq = _group createUnit ["b_officer_f",(getmarkerpos str(blu_hq_markername)), [], 0, "FORM"];
sleep 0.2;
_hq setformdir 240;
sleep 1;
_hq disableAI "MOVE";
hq_blu1 = _hq;
```

That way it will not move no matter what.
However, with AGM AI he loves to run away from base (i'm not even know where he is going), so mission is basically failed.
Is that expected behavior?

**Comment by BaerMitUmlaut** [comment]
Are you sure this doesn't happen without AGM? `disableAI "MOVE"` shouldn't allow the AI from moving at all.

**Comment by rlex** [comment]
Yes. AI may go prone but it doesn't move away from FOB. Test PBO: https://lex.io/pub/SPMP_DUWS_M.altis.pbo

**Comment by PabstMirror** [comment]
There really isn't much in AGM_AI besides changing default skills and weapon firing settings.

You could try adding 

`_hq disableAI "FSM";` to disable the FSM, which I think is capable of issuing move orders.

**Comment by Cyruz143** [comment]
Might be ```courage``` adjustment that causes him to flee, if I'm making static units I tend to use this too ```_unit allowFleeing 0``` or as Pabst says, kill the whole FSM.

**Comment by rlex** [comment]
testing now with allowFleeing 0. Seems to be working.

**Comment by rlex** [comment]
Yep, that helped. Thanks.
