### ISSUE TITLE
AGM_isMedic doesn't work on vehicles anymore

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/AGM#2110]
Was this intentionally removed in favor of synchronizing the vehicle with a trigger? I would like to do `this setVariable ["AGM_isMedic, true];` to make a vehicle MEDEVAC vehicle, but it doesn't work. Since we are running Chronos (in-house persistence-logistics system, we can't really synchronize them in editor.

It is possible to synchronize the object with the module in it's init though, but I'd like to hear it's meant to be like that (and what other issues it could bring maybe doing it this way):
`MedSys_VarName synchronizeObjectsAdd [this];`

**Comment by esteldunedain** [comment]
It didn't change; looking at the code that should work flawlessly. 

```sqf
this setVariable ["AGM_isMedic", true, true];
```

When inside the vehicle, you can call this function to check everything is working as it should:

```sqf
[player] call AGM_Medical_fnc_isInMedicalVehicle;
```

Should return true if you are a passenger in a vehicle in which the variable has been set.

**Comment by KoffeinFlummi** [comment]
MEDEVAC vehicle != medical vehicle

Medical vehicles prevent bleeding while inside them, MEDEVAC vehicles allow treatment. To make a vehicle a MEDEVAC vehicle, add it to the missionNamespace array `AGM_Medical_MEDEVACVehicles`.

**Comment by esteldunedain** [comment]
> MEDEVAC vehicle != medical vehicle

> Medical vehicles prevent bleeding while inside them, MEDEVAC vehicles allow treatment. To make a vehicle a MEDEVAC vehicle, add it to the missionNamespace array AGM_Medical_MEDEVACVehicles.

Sorry, I mistaken both. Well, doing this is a bit trickier then. Something like this on the init box should work:

```sqf
this spawn {
    // Wait until the module is initialized
    waitUntil { missionNamespace getVariable ["AGM_Medical_Module", false] };
    // Add the vehicle to the list of MEDEVAC vehicles
    AGM_Medical_MEDEVACVehicles pushBack _this;
};
```

**Comment by jonpas** [comment]
So if I want to prevent bleeding inside vehicle I would setVarible "AGM_isMedic"? What's the default for them, do all vehicles prevent bleeding by default?

What about simply doing the following as in OP?
`MedSys_VarName synchronizeObjectsAdd [this];`

Thanks!

**Comment by esteldunedain** [comment]
> So if I want to prevent bleeding inside vehicle I would setVarible "AGM_isMedic"? 

Yes 

> What's the default for them, do all vehicles prevent bleeding by default?

No, none do by default

> What about simply doing the following as in OP?
> varName synchronizeObjectsAdd [this]; where varName is the name of the AGM Medical System module.

No, that doesn't work, unless you run it BEFORE activating the module. I wouldn't recommend it; the code above is more robust

**Comment by jonpas** [comment]
Awesome, thanks for the help!

**Comment by esteldunedain** [comment]
@jonpas, I did a couple of modification on the source code above; the former wouldn't work under some conditions.

**Comment by jonpas** [comment]
That's awesome, thanks a lot, you are great help!
