### ISSUE TITLE
AGM "Combat Deafness" does not work on CAF_AGGRESSORS

### ISSUE THREAD

**Issue by JohnnyDeeee** [KoffeinFlummi/AGM#2112]
Hi,

I love AGM, but i also love CAF_AGGRESSORS.. You and CAF_AGGRESSORS dont go along with eachother that well.. I can shoot with the CAF_AGGRESSORS weapons with my earplugs out and no high pitch sounds is created.. Is it able to fix this, or are there other weapon/unit mods i can try that DO work with AGM?

Thanks in advance, JohnDoe

**Comment by brainslush** [comment]
What weapon were you using? Not all weapons cause ear ringing.

**Comment by JohnnyDeeee** [comment]
M16 and M4

**Comment by brainslush** [comment]
Try it with heavier weapons since usually this callibar doesn't cause agm ear ringing to trigger

**Comment by JohnnyDeeee** [comment]
I feel so dumb.. So you are right, higher caliber weapons do work, but is there a way to configure this ear ringing for other weapons that dont have it right now..?

**Comment by esteldunedain** [comment]
@JohnnyDeeee, not all weapons produce ear ringing. In fact, only a few high caliber weapons do. This is by design, and I would encourage you not to change it. Anyway, in case you still want to modify some addon, the ringing depends on the `audibleFire` entry of the ammo used.

Regards
