### ISSUE TITLE
Using AGM event handlers to make a unit permanently unconcious?

### ISSUE THREAD

**Issue by AndrewKopczynski** [KoffeinFlummi/AGM#2113]
I was looking at using an AGM event handler to make a unit go unconscious as soon as they wake up, but I couldn't get the examples on the wiki's event handler page working from editor.

The wiki's example is this:
`My_wakeUp_EHID = [soldier1, "AGM_wokeUp", {hint format ["%1 just woke up from unconsciousness, name (_this select 0)]}] call AGM_Core_fnc_addCustomEventHandler;`

What I wanted to do was something like this:
`some_eventHandler_ID = [_this; "AGM_wokeUp", [_this, 999999] call AGM_Medical_fnc_knockOut] call AGM_Core_fnc_addCustomEventHandler;`

Sorry about all the event/function questions, I'm trying to get into Arma scripting.

**Comment by esteldunedain** [comment]
@AndrewKopczynski,

Tha should work, but the event is called `"wokeUp"`, without the AGM prefix. 

The wiki may say otherwise, but is wrong. Check https://github.com/KoffeinFlummi/AGM/issues/1618

**Comment by jonpas** [comment]
Ooh, everyone hates updating the wiki, eh. :grinning:

**Comment by AndrewKopczynski** [comment]
That works, thanks a bunch again!

Note for anyone Googling this and is a newbie like me: You probably want to remove the comments if you're using it in the Arma 3 editor.

**Comment by esteldunedain** [comment]
> You probably want to remove the comments if you're using it in the Arma 3 editor.

Exactly; I just put those to explain a bit better how everything works
