### ISSUE TITLE
Unable to load / unload into vehicles with AGM & XMedSys

### ISSUE THREAD

**Issue by Knight1981** [KoffeinFlummi/AGM#2114]
We are using AGM without the medical & hearing module because we are using XMedSys instead of this. It works great except one problem.

We are not able to load / unload unconscious people in and out of vehicles. I know that XMedSys has this feature and also AGM, but both mods together are not working here. We can't see the load / unload dialog :( That is a major problem because when a player is hit inside an vehicle we are not able to help him. He must respawn.

Hope you can fix this. Thank you so much!

**Comment by jonpas** [comment]
This is XMedSys' fault, the AGM Integration of XMedSys doesn't have this supported.

**Comment by Knight1981** [comment]
Hm okay, that is bad. XMedSys without AGM can load / unload people. Are you able to put this functionality into an extra pbo so we can remove the medical.pbo but still able to load / unload players like ammo boxes etc.?

**Comment by KoffeinFlummi** [comment]
> Hm okay, that is bad. XMedSys without AGM can load / unload people. Are you able to put this functionality into an extra pbo so we can remove the medical.pbo but still able to load / unload players like ammo boxes etc.?

That would be a lot of work for us. If XMS's dragging doesn't work, you should take it up with X39.

**Comment by jonpas** [comment]
I've raised it with him way back, he pushes some fixes but nothing came of it, I believe he is just busy with XMS2. Since them we moved to AGM Medical though. 

I suggest you post on XMS BI forum topic or his GitHub issue tracker: https://github.com/X39/XMedSys1
