### ISSUE TITLE
Overheating: Swap Barrel with BWMod

### ISSUE THREAD

**Issue by Knight1981** [KoffeinFlummi/AGM#2115]
Hey, I'm not sure if this issue already exists or not, I didn't found anything here.

Is it possible to swap the barrel for the maschineguns "MG3, MG4, MG5, MG36" from the Bundeswehr-Mod? 

Is there any possibility to configure / add those weapons so we can swap the barrel here as well?

Thanks a lot.

**Comment by brainslush** [comment]
http://bwmod.de/index.php/inhalt/download
or direct link
https://docs.google.com/uc?export=download&id=0B-LOD2ktZhvuMTFnUmUyNjRWVkU

**Comment by Knight1981** [comment]
No they didn't. :( It is not working with this file.

**Comment by brainslush** [comment]
I have a fixed version but I would have to ask KoffeinFlummi if I'm aloud to share it.

**Comment by Knight1981** [comment]
That would be great. Thank you. Maybe you could also share it to the BW-Mod guys so they can update the file on their page for the community.

**Comment by bux578** [comment]
You wouldn't belive it but @KoffeinFlummi is part of the bwmod team.

![rimshot](https://cloud.githubusercontent.com/assets/1235520/6264232/27e221be-b822-11e4-9374-7876c11597c8.gif)

**Comment by Knight1981** [comment]
Haha :D Sehr schön ;-)

**Comment by Knight1981** [comment]
Did you get a response? :)

**Comment by commy2** [comment]
Unrelated to AGM.
https://github.com/KoffeinFlummi/AGM_Compatibility
