### ISSUE TITLE
question : Check PBOs

### ISSUE THREAD

**Issue by havena** [KoffeinFlummi/AGM#2116]
Hi, a simple question, 

this module disables checking signatures by server cfg (verifySignatures = 2) or i need to set it to 0 ?

Best regards,
havena

**Comment by esteldunedain** [comment]
> this module disables checking signatures by server cfg?

No

> or i need to set it to 0 ?

No

The modules works independently from signatures, but it complements that system. CheckPBO ensures there are no *missing* pbos on clients, which the signature system does nothing about (you can connect without some required addon without the vanilla system kicking you out ). It also checks that pbo version match, which AFAIK is only usefull if you are not checking signatures on the server.

**Comment by jonpas** [comment]
> It also checks that pbo version match, which AFAIK is only usefull if you are not checking signatures on the server.

It's useful with signature check as well, most mods keep the same bikey across versions, so Check PBO complements that as well.
