### ISSUE TITLE
AGM_Armour (?) breaks score 

### ISSUE THREAD

**Issue by rlex** [KoffeinFlummi/AGM#2117]
Long story short: 
Spotted enemy (AI) T100. Fired titan AT rocket. After first rocket tank started to burn and exploded after short time. 
However, that kill is not counting against total score (both AI crew and tank kill is not counted).

**Comment by KoffeinFlummi** [comment]
This is unfixable unfortunately as there's no way of killing of a unit or vehicle by script and setting the "killer".
