### ISSUE TITLE
Map Tool Not Visible on Map

### ISSUE THREAD

**Issue by ozdeadmeat** [KoffeinFlummi/AGM#2119]
Hi,

Love your work with this mod. I have an issue that I can't share the lines I draw with the map tools in multiplayer missions. I am the only person who can see them. Are you intending on implementing something that will allow people to share 'overlays' they have drawn in multiplayer?

**Comment by PabstMirror** [comment]
Part of #1227 (Improve Map Funtionality (2))

Right now, lines are local only when drawing.  But grab a `AGM_MapTools` and you can copy lines from another player (just interact on him).

**Comment by ozdeadmeat** [comment]
Any idea why the tool doesn't show up on the map?

**Comment by ACyprus** [comment]
Once map tools are in your inventory, view your map and then use self
interaction to enable the tool. They'll appear bottom left so you may need
to adjust your visible area to see them.

**Comment by PabstMirror** [comment]
Open Map, Self Interact, Map Tools, Show Small Map Tools:

![untitled](https://cloud.githubusercontent.com/assets/9376747/6282951/ba5e5550-b8a2-11e4-983d-7a51b437467b.jpg)

**Comment by ozdeadmeat** [comment]
Awesome, thank you very much.
