### ISSUE TITLE
Undefined Variable AGM_Vector_settings in \AGM_Vector\functions\fn_tabAzimuthKey.sqf 

### ISSUE THREAD

**Issue by Benargeez** [KoffeinFlummi/AGM#2122]
AGM_Vector_settings is undefined and is only referenced in \AGM_Vector\functions\fn_tabAzimuthKey.sqf line 100.

AGM_Vector_settings is expected as a code.
\AGM_Vector\functions\fn_settings.sqf might need to be defined as function 

With this error present it is impossible to access the settings on the vector by pressing the azimuth key 5 times.

https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Vector/functions/fn_tabAzimuthKey.sqf

**Comment by PabstMirror** [comment]
AGM_VectorSettings is an array
But it is probably is supposed to be `AGM_Vector_fnc_settings`

I'm guessing this is why the vector never worked for me.

**Comment by Benargeez** [comment]
Yeah it looks like the functions used to be defined in the clientinit.sqf 
https://github.com/KoffeinFlummi/AGM/blob/8f74c8d6fbe130906a48cdc356760779c2d7385c/AGM_Vector/clientInit.sqf

now they are defined in config.cpp
https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Vector/config.cpp

Function variable names must have been lost in translation somewhere during the conversion
