### ISSUE TITLE
Bullet Hit Particles only visible within 1.2km

### ISSUE THREAD

**Issue by ozdeadmeat** [KoffeinFlummi/AGM#2129]
I was trying out the Vector and Kestrel tools for sniping yesterday with a friend. I noticed that after about 1.2km I could no longer see his land of shot (particle effect) when the round landed. Is this something that can be added by you guys?

**Comment by jonpas** [comment]
Increase your settings maybe? View distance?

I remember shooting over 2km a while ago and could see particle effects just fine.

**Comment by ozdeadmeat** [comment]
I have the view distance and Object distance set to 12km. I can see my particles just fine. I can not however see anyone elses beyond 1.2km.

**Comment by captainblaffer** [comment]
Bullet hit particles visibility depends on the graphics setting you set for... Particles ;)
Which value is it on for you?

**Comment by KoffeinFlummi** [comment]
Closing as there's nothing we can do about this.
