### ISSUE TITLE
Zeus placing air units in the air

### ISSUE THREAD

**Issue by rover66oyo** [KoffeinFlummi/AGM#2130]
When in zeus, I attempt to take an air unit which I have placed, and raise it's altitude (holding alt and drag unit) so it may automatically start flying. When I do this, it automatically teleports to the ground directly below it and takes some damage. I've tried this w/o AGM and it works fine.

**Comment by PabstMirror** [comment]
I couldn't reproduce, are you running any other mods?  If so try again with just CBA/AGM.

**Comment by esteldunedain** [comment]
I couldn't repro this either; tested with a bunch of different addons

**Comment by rover66oyo** [comment]
Turns out the LSD vehicles module is what did it

**Comment by bux578** [comment]
I really don't think that the LSD module could be the reason. All it does is just [`setObjectTexture`](https://community.bistudio.com/wiki/setObjectTexture).

**Comment by brainslush** [comment]
Also can't reproduce neither sp nor mp.

**Comment by kripto202** [comment]
I know what you are talking about its bis fault. Nothing that the agm team can do.

**Comment by KoffeinFlummi** [comment]
Yeah, I really don't think the LSD vehicles module is causing this...

**Comment by commy2** [comment]
Steps to reproduce?

**Comment by rover66oyo** [comment]
It's no longer an issue, it was a glitch with ARMA itself. Bohemia needs to fix this. And with the steps to reproduce, it's happens at random.

**Comment by commy2** [comment]
k
