### ISSUE TITLE
Why "\AGM_Movement\fatigue.sqf"; is commented inside the init file?

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#2133]
https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Movement/clientInit.sqf

Does this mean that it's not working now? And how stamina is processed then?

**Comment by ozdeadmeat** [comment]
I don't think they want people using it any more. I thought it was an awesome feature. I hope they replace it with something else soon.

**Comment by PabstMirror** [comment]
#1348

I think you can reactivate with putting this in init.sqf:
`null = 0 spawn compile preprocessFileLineNumbers "\AGM_Movement\fatigue.sqf";`
