### ISSUE TITLE
interaction possible after 25 seconds

### ISSUE THREAD

**Issue by Astavinu** [KoffeinFlummi/AGM#2135]
i wrote some script that spawns boxes the other day and i want to drag those boxes using AGM, which works fine basically. however i have to wait like 25 seconds after spawning a box to be able to call the interaction menu. is there any way i can get around this?

greetings

**Comment by esteldunedain** [comment]
Unfortunately, that's vanilla Arma behaviour. You cannot interact with anything your unit doesn't know about yet. Sometimes the units takes a long time before realizing there's a new object there; might depend on unit skill too, but i'm not sure.

To workaround that, you can "reveal" and object by right clicking while looking at it. That should reveal the box to your unit, hence allowing you to interact.
