### ISSUE TITLE
Issue: binding: ctrl and shift + numbers are being overruled by agm

### ISSUE THREAD

**Issue by kOepi123** [KoffeinFlummi/AGM#2136]
Hello,

tested version 0.95.2

since the last/the update before the last everything worked fine, but now I cannot use shift / ctrl + 3 to throw selected grenades.
I tested this without mods and with @CBA, @AGM.

maybe it would be easier to define a new AGM binding to throw the actual grenade.

Let me know how I can help you.

greetz

kOepi

**Comment by commy2** [comment]
No way to fix this really. It's the way BI handles the input of modifier keys now.
