### ISSUE TITLE
Auto drop used disposable tube from gear

### ISSUE THREAD

**Issue by Winter259** [KoffeinFlummi/AGM#2139]
Currently the process is:

Switch to disposable AT Launcher -> Aim -> Shoot -> Enter Gear -> Right click to drop.

Hopefully it wouldn't be too difficult to automate the last two steps, as it is done in A2.

**Comment by Cyruz143** [comment]
http://www.armaholic.com/page.php?id=19374

INKO did a disposable NLAW addon a long time ago that dropped the tube after use, might be good for reference.

**Comment by BaerMitUmlaut** [comment]
Duplicate: #2051
