### ISSUE TITLE
Leaning sideways prone, aiming down sights crosshair offset

### ISSUE THREAD

**Issue by captainblaffer** [KoffeinFlummi/AGM#2142]
How to reproduce:
1. Start a mission at night time with the player having: NVG, IR laser on weapon, weapon with optic.
2. Prone and lean sideways. Aim down sights. Aim at an up angle, e.g. aim on a tower.
3. Turn on IR laser.

Notice IR laser point does not match optic crosshair point. Bullets will fly to the IR laser point.
screenshot: http://i.imgur.com/JtP39cs.jpg 

AFAIK Aiming down sights while leaning sideways is something AGM added. Not possible in default arma.

**Comment by kripto202** [comment]
if you look closer, you are looking lower than you would normally would in the scope. Nothing is changed but the angle you are looking into the sight. There is nothing wrong here.

**Comment by captainblaffer** [comment]
ehm, things are very wrong here. The bullets do not go towards the point the crosshair is pointing

**Comment by kripto202** [comment]
they don't all the time because if you are fatigued or move, you can easily look at the crosshair at a different angle. It may look center to you, but at the end of the day, it matters where the barrel is facing.

**Comment by esteldunedain** [comment]
Well, in that pose the eye is not correctly aligned with sight. 

![image](https://cloud.githubusercontent.com/assets/7674951/6429321/803ddf28-bfa8-11e4-95f8-13f632258e9d.png)

That's an issue in A3 animations that we cannot fix (without legal access to the anims). However, this can happen IRL to; most sights only work if you correctly align your eyes to the sight axis.

But of course that doesn't apply to all sights! That's exactly what reflex and holo scopes are for. You don't need to align your eyes for them to work. In fact, this is correctly modeled in-game, so they work great even on that pose:

![image](https://cloud.githubusercontent.com/assets/7674951/6429345/4b215bc0-bfa9-11e4-9663-586035c07f59.png)

![image](https://cloud.githubusercontent.com/assets/7674951/6429347/61843496-bfa9-11e4-80b3-61617475fccb.png)

The bullets fly exactly toward those red dots.
