### ISSUE TITLE
All Zamak trucks have same model

### ISSUE THREAD

**Issue by Waffle-SS** [KoffeinFlummi/AGM#2153]
Something in AGM is causing all of the Zamak trucks (OPFOR and INDFOR) to have the transport covered model. This includes the logistics (fuel/ammo/repair) trucks, although they maintain the original secondary texture. The one thing that I know is that agm_vehicles is not causing it, I haven't been able to further narrow it down yet.

**Comment by esteldunedain** [comment]
That was already fixed today on https://github.com/KoffeinFlummi/AGM/commit/cb9a18dcd815aa4a376707af03a8f7fff298c459
