### ISSUE TITLE
question: Should there be a hotfix?

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#2154]
after reading a couple reports, I noticed that these are some pretty big reports and I am wondering if there is or should there be a hotfix? It's always annoying when arma updates, they break all kinds of mods.

**Comment by kripto202** [comment]
the reports #2151 and #2152

**Comment by esteldunedain** [comment]
Yeah, https://github.com/KoffeinFlummi/AGM/issues/2151 and #2153 will probably force us to release a hotfix. #2152, on the other hand, needs to be fixed by BIS

**Comment by kripto202** [comment]
I hope that this hotfix isn't going to take a long time like the last hotfix

**Comment by jonpas** [comment]
Well everyone is voluntarily working on AGM, so asking for it to be fast won't help.

**Comment by commy2** [comment]
http://forums.bistudio.com/showthread.php?178253-Authentic-Gameplay-Modification&p=2894699&viewfull=1#post2894699
