### ISSUE TITLE
Switch weapons while moving

### ISSUE THREAD

**Issue by Blackswater** [KoffeinFlummi/AGM#2155]
hey guys, i dont know if somebody asked it before but there is an addon where you can switch weapons while moving. my question is, if you could add it to the agm mod. 

this is the addon: 
http://www.armaholic.com/page.php?id=21561

and he even post the source code on github:

https://github.com/Tenga/Arma-3-weapon-switch-on-the-move

**Comment by BaerMitUmlaut** [comment]
Duplicate: #62

**Comment by bux578** [comment]
But thank you for your contribution!!! :rose:
