### ISSUE TITLE
remove hotkey

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#2157]
I'm sure there are some hotkeys that some people doesn't like to use and would like to remove them. Possibly have the ability to remove the hotkey by pressing escape on your keyboard.

**Comment by PabstMirror** [comment]
You can delete hotkeys by pressing the None button in the AGM Options menu:

![untitled](https://cloud.githubusercontent.com/assets/9376747/6512624/df95f538-c33a-11e4-9b2b-063423d4fa80.jpg)

**Comment by kripto202** [comment]
didn't see that
