### ISSUE TITLE
Hand flare flickering on ground

### ISSUE THREAD

**Issue by Waffle-SS** [KoffeinFlummi/AGM#2158]
Currently the hand-flares flickers the lens flare effect when they're on the ground. I don't know if this was intended, since it doesn't strobe in the air, but honestly its just painful to look at.

**Comment by bux578** [comment]
You probably mean this: https://www.youtube.com/watch?v=oOU9NRK2bIg

**Comment by Waffle-SS** [comment]
Here's a quick video: https://db.tt/VjO2BcTd

If I may suggest, create the light source for the flare through script, this way to can freeze it once the flare object reaches the ground.

**Comment by bux578** [comment]
Related / possible duplicate: #1374

**Comment by commy2** [comment]
Yup. Dup of #1374. Reason is a combination of the way Arma 3 handles light and handgranades rotating by themselves.
