### ISSUE TITLE
AGM_Medical limited MaxUnconsciusnessTime

### ISSUE THREAD

**Issue by alef** [KoffeinFlummi/AGM#2160]
Accordint to this formula:
 * https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Medical/functions/fn_knockOut.sqf#L108
the wakeup can't happen longer than ~5 minutes when `_duration` is not given, which seems default for all `fn_handleDamage`.

`fn_wakeUp` seems to resets the unconsciouness timer, so if `MaxUnconsciusnessTime` is longer than those ~5 minutes, you'll never die. I've used a 10 minutes `MaxUnconsciusnessTime` in mission, and that's what did happen.

**Comment by esteldunedain** [comment]
You're absoutely right. It depends on your playstyle, but you would probably prefer to deactivate that automatic wake up chance.To do that just set the following variable on each player unit:

```sqf
this setVariable ["AGM_Medical_AutomaticWakeup", false]
```
