### ISSUE TITLE
Second Forward Wheels Repairing. Check in RHS...

### ISSUE THREAD

**Issue by gzhegow** [KoffeinFlummi/AGM#2170]
In RHS mod we have 8-wheeled BTR80.
With AGM mod we can repair Forward wheels, backward wheels and SECOND backward wheels.
The forward second wheels cant be repaired at all.

But in GAZ-66 vehicle we have 6 wheels, but really have 4 wheels. Maybe it RHS issue. But with AGM we can detach Backward wheels, and vehicle can run in good state....

I have bad English, I will try to translate through Google Translate.

1) RHS BTR80 has 8 wheels. We can repair a first front, rear and rear first second (middle). In this case, we can repair the second front wheels. In the RHS BTR80 has been finalized and the 2 wheels we can supply directly from the cockpit. However Gaz66 has all 4 wheels, with its rear implemented as a second forward and we can not repair them all. However, we can remove 2 invisible wheel, as described in paragraph 2.

2) RHS Gaz66 has six wheels, as seen in practice 4. We can remove two wheels using AGM, wherein at Gaz66 all remain the same four wheels. Nevertheless, they are involved in the movement and to remove when the fifth wheel, then despite the fact that it is not present in the model - the machine will go bad. If you remove the then six wheels - the car as if nothing had happened to go to the 4 wheels.

**Comment by commy2** [comment]
Same as https://github.com/KoffeinFlummi/AGM/issues/1622
