### ISSUE TITLE
PO-30 Orca (Black & White) Spontanous Explosion After Repair (AFM)

### ISSUE THREAD

**Issue by NicoHarg** [KoffeinFlummi/AGM#2173]
To reproduce:
1) Place a PO-30 Orca (Black & White).
2) Damage it heavily.
3) Repair and refuel.
4) With AFM enabled, start the engine.

If you're at step 4 and the rotors start spinning, reset everything and try again. It sometimes happens, I can't figure out under which circumstances. The engine should be spooling up, but the instruments remain dark and the rotor stationary.

5) Wait a few seconds then exit the helicopter.
6) The rotor should start spinning, wait a few seconds then enter the helicopter again.
7) Wait a few more seconds and you should explode.

Here's a video: https://www.youtube.com/watch?v=YCgP0_BnCI8
It doesn't seem to happen with the AH-9, I haven't tested with any other helicopters though.

**Comment by commy2** [comment]
This has nothing to do with repairs or anything else in AGM. Helicopters just randomly explode when taking of in this game since Alpha.

http://feedback.arma3.com/view.php?id=9311

**Comment by NicoHarg** [comment]
Except it's not that because this is reproducible under certain circumstances and only with AFM and AGM enabled.

**Comment by commy2** [comment]
I think you are right.

Duplicate of https://github.com/KoffeinFlummi/AGM/issues/2001
