### ISSUE TITLE
Adding Ai config elements to a configurable module

### ISSUE THREAD

**Issue by serjames** [KoffeinFlummi/AGM#2175]
I'd like if possible to be able to 

A) Completely disable AGM_ai from within the Editor - i.e. by Placing / or not placing an "AGM_AI" module.

B)  Have the ability to fine tune this i.e. adjust the settings ourselves from within the mission editor module.

Is it even doable ?

**Comment by ACCtomeek** [comment]
I think it's not because AGM_AI is a config.cpp file which is loaded at the game start and can't be further modified.
