### ISSUE TITLE
Is there a way to add wind deflection for a projectile? 

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#2176]
For example for custom at launcher? I want to make ammo for the AT launcher that is affected by the wind as well.

**Comment by esteldunedain** [comment]
Rockets and missiles are already affected by wind

**Comment by Tachii** [comment]
The vanila ones maybe, but if I wanna add custom ammo what parametr should I add?

**Comment by esteldunedain** [comment]
No custom parameters are needed. This works automatically

**Comment by Tachii** [comment]
Good, but what if i want to increase the effect?

**Comment by esteldunedain** [comment]
There's currently no way to tweak the strength, and we won't be adding one any time soon
