### ISSUE TITLE
Goggles enhancement

### ISSUE THREAD

**Issue by antoblushadow** [KoffeinFlummi/AGM#2178]
I noticed that all the glasses make the "orange effects" but some should not because have the transparent lens ( for example the  tactical glasses ). Can you please make the effect only in the goggles with colored lens like the aviator? And finally I want to propose to add a kind of HUD in the tactical glasses and in the combat visor.

**Comment by esteldunedain** [comment]
> make the "orange effects" but some should not because have the transparent lens ( for example the tactical glasses )

The color an intensity of the effect is configured on goggle by goggle basis. It should be correct for all vanilla glasses. May be wrong for mods though.

> And finally I want to propose to add a kind of HUD in the tactical glasses and in the combat visor.

No way; we don't do futuristic stuff

**Comment by antoblushadow** [comment]
Thanks for the answer, but how can I edit the color and intensity of the glasses?

**Comment by esteldunedain** [comment]
You have to either edit AGM, add to your mod config or write a compatibility pbo. The parameters a like this:
https://github.com/KoffeinFlummi/AGM/blob/master/AGM_Goggles/config.cpp#L22-L201

**Comment by antoblushadow** [comment]
Thank you so much for the answer, I will make my compatibility mod.
