### ISSUE TITLE
Remaster the Artillery system?

### ISSUE THREAD

**Issue by gpgpgpgp** [KoffeinFlummi/AGM#2187]
Just did some work on Coding's artillery system. Loved his work because it made most use of vanilla systems like making good use of the default "artillery screen display" & "gun elevation/slow gun elevation" (pageUp/down & shift+pageUp/Down), and makes shooting artillery a much interesting & skillful thing to do (for example calculating solutions & aiming manually), and it is not too hard (as once ACE does). You can still easily hit your target with no problem if you're doing things right.

The pbos are now at a working state, and it modifies "rscWeaponRangeArtillery" & "rscWeaponRangeArtilleryAuto" a bit to give more visible bearing info, changes most default "hint" to "AGM_Core_fnc_displayTextStructured", adds the ability to double click on the map display of artillery computer to designate target coordinates, and does some changes in Coding's UI for easies uses. The scripts are still at an ugly state, but they're working fine without script errors & known issues. Just a state of early prototype to see if this is the thing we want. :P

Mount BOTH pbos & Interaction with yourself when inside a mortar or any vanilla artillery weapon and click "Artillery Computer". Here's the download link.

Link: http://www.mediafire.com/download/ghbg6rh2s74w7w0/agm_artillery_test_pbos.zip

Important Note: Haven't asked Coding for permissions yet. DO NOT make use of the pbo & scripts of CODI_ArtilleryComputer.pbo anywhere else except for TEST REASONS. (you're free to make use of AGM_artillery.pbo if you want, but it's fairly useless without the former one)

Not that important Note: Let me know if I left any Chinese in the strings. :P

Also: If feeling lacking knowledge of vanilla Artillery display, a quick reference table.
"TRV" Time (of impact?)
"ELV" Current Gun Elevation
"REL" Needed Gun Elevation (according to calculations)

**Comment by bux578** [comment]
Feel free to do a pull request once you're finished and the code is in an acceptable state.
Here's a link to the Coding Guidelines: https://github.com/KoffeinFlummi/AGM/wiki/Coding-Guidelines

ATM we're pretty occupied and won't be able to test that ourselves anytime soon. Maybe a video of the functionality would be helpful.

**Comment by commy2** [comment]
https://github.com/KoffeinFlummi/AGM/issues/1194

**Comment by gpgpgpgp** [comment]
Roger. Just got a bit over-excited. Will try to polish it when my summer holiday comes.

**Comment by commy2** [comment]
Closed as dup.
