### ISSUE TITLE
Helicopter Exploding upon entering.

### ISSUE THREAD

**Issue by MattMarchy** [KoffeinFlummi/AGM#2207]
Some helicopters tend to explode when you enter the pilot seat. Can provide video if necessary.

**Comment by PabstMirror** [comment]
AGM is no longer under development:
http://forums.bistudio.com/showthread.php?190433-ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE

I think it's a know ARMA issue, one possible solution is to just shoot the chopper with a pistol once.
