### ISSUE TITLE
Earplugs dont lower the noise

### ISSUE THREAD

**Issue by ch33ch** [KoffeinFlummi/AGM#2215]
hi, the Earplugs dont lower the noise, how can that be changed?  Would be great inside Choppers ;-)

Also, the color of Vehicles (Offroad) changed by AGM. How can i undo that?

And would it be possible to get an AI Engineer to repair vehicles, when a spare wheel is in front of him, or  an Repair Truck nearby?

Thanks, cheers :D

**Comment by PabstMirror** [comment]
AGM is no longer updated, please try ACE:
https://github.com/acemod/ACE3
