### ISSUE TITLE
[latitude] and [longitude] not working

### ISSUE THREAD

**Issue by tombalcaen** [KoffeinFlummi/AGM#2216]
Hi, I am trying to show a "agm-marker" or my "agm-map". So far everything worked great. Until I got my data from firebase with a "FirebaseObjectObservable". 

This is where I Get my data from firebase DB.
![screen shot 2017-07-05 at 09 36 32](https://user-images.githubusercontent.com/29797792/27854066-9af69592-6165-11e7-9133-30d4f73ad2d4.png)

This is how I try to show it. Notice that when I display the data in an input, it works fine.

![screen shot 2017-07-05 at 09 37 10](https://user-images.githubusercontent.com/29797792/27854105-c0a5b20a-6165-11e7-8e0f-af8deb90f8e8.png)

Thanks :)

**Comment by bux** [comment]
You took a wrong turn somewhere, son.

**Comment by tombalcaen** [comment]
Sorry.

**Comment by commy2** [comment]
xD
