### ISSUE TITLE
Can't open the AGM options 

### ISSUE THREAD

**Issue by Marko333444** [KoffeinFlummi/AGM#2218]
Hi , 
I have an issue with agm. I have the latest version of CBA, AGM seems to be working fine but i can't open the AGM options. When i click on esc and i can see the AGM options in left corner, but when i click it , it sends me back to the game. Can someone please help me to fix this ? i will be very thankful because i really like this mod. Thank you.

**Comment by bux** [comment]
Please check the readme:

⚠ THIS MOD IS DISCONTINUED. PLEASE MOVE TO [ACE3](https://github.com/acemod/ACE3)
