### ISSUE TITLE
Add AGM to Steam Workshop

### ISSUE THREAD

**Issue by bux578** [KoffeinFlummi/AGM#483]
As 1.24 went live yesterday, it's now relatively easy for the majority of players to subscribe to addons and to actually play them without fiddling with programs like PlayWithSix (or similar) or Arma launch params. (Might need to wait for CBA_A3 though)

**Comment by nic547** [comment]
soon ...
http://forums.bistudio.com/showthread.php?149636-Development-Branch-Changelog&p=2909362&viewfull=1#post2909362
