### ISSUE TITLE
Wearing EarPlugs at mission start?

### ISSUE THREAD

**Issue by Feivel69** [KoffeinFlummi/AGM#504]
In ACE there was the possibility to let players wear their earplugs from the start of a mission with using

[player, 'ACE_EarPlugs'] execFSM '\x\ace\addons\sys_goggles\use_earplug.fsm';

in the init/init.sqf.

Is it possible with AGM too and if so how would I do it?

Thank you!

**Comment by Feivel69** [comment]
Sorry for reviving the topic but did you guys rewrite this segment? Seems like the command line doesn't work anymore.

**Comment by esteldunedain** [comment]
Yeah, sorry.

Try:
`null = this spawn {sleep 1; if (local _this) then {_this setVariable ["AGM_hasEarPlugsIn", true, true];};`

**Comment by Feivel69** [comment]
Thanks for quick response.

First one doesn't work for me, the second one does.

**Comment by esteldunedain** [comment]
> First one doesn't work for me, the second one does.

It had a missing curly brace.

**Comment by Feivel69** [comment]
Roger, everything's fine again ;)
