### ISSUE TITLE
"No entry [...] AllowNonMedics/Values[...]"

### ISSUE THREAD

**Issue by ghost** [KoffeinFlummi/AGM#620]
The title says it.

Every time I run my editor, trying to create a mission, I will be prompted with this message:
http://i330.photobucket.com/albums/l419/ferox113/arma32014-07-3019-25-21-79.png

This error displays when running the mission on a server, as well.

I have tried re downloading and installing, as well as turning off the "AllowNonMedics" function, by choosing "no", in the module-settings, in the editor.

I have not yet figured out, where the issue is; and how I can resolve it -hence why I am going to the root of the mod.

Do you know what is going wrong, and perhaps how to correct it?

Thanks!

**Comment by commy2** [comment]
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/480
