### ISSUE TITLE
Logistics: Offer Player Choices When Replacing Wheel

### ISSUE THREAD

**Issue by KoffeinFlummi** [KoffeinFlummi/AGM#657]
- [ ] Player should be able to choose the wheel to use.
- [ ] Wheels should be coloured based on their damage.
- [x] Unable to replace rear wheels on Zamak (#1449)
- [ ] Location of rear and middle wheel of 6-wheel APC is wrong (#1622)

--------------------
- [ ] Wheel names are not localized on the select wheel menu
- [ ] Automatic configuration of wheel slots for all car/trucks?

**Comment by Drezzo** [comment]
Found 2 others:
APC
The RHS_BTR family ( can't remove or replace the second front wheels)
Armoured
The RHS BM-21 (can't remove or replace the rear wheels)

**Comment by commy2** [comment]
Nothing we can do about third party addon vehicles.

**Comment by commy2** [comment]
\>\>https://github.com/KoffeinFlummi/AGM/issues/1937
