### ISSUE TITLE
Make using Mine Detector more realistic / fun

### ISSUE THREAD

**Issue by bux578** [KoffeinFlummi/AGM#735]
The mine detector works like a magic device and insta spots every mine in quite a big radius. Add proximity detector sounds like beep that increases volume or kind of a electric buzzing.

EOD player still shouts "Mine detected" and a red triangle is placed around the mine, even in higher difficulty levels.

**Comment by Tachii** [comment]
New version:

https://www.youtube.com/watch?v=XN4Sc-HrxMA

**Comment by bux578** [comment]
> This video contains content from Base79 Music 2 (Base79/21), who has blocked it in your country on copyright grounds.

Us poor germans

**Comment by esteldunedain** [comment]
It isn't available for me either

**Comment by Tachii** [comment]
Dam, sry guys. I'll reupload it later :)

**Comment by Tachii** [comment]
https://dl.dropboxusercontent.com/u/110028032/mine_detector.rar

**Comment by Tachii** [comment]
I think video should be available now

**Comment by Tachii** [comment]
Feel free to include it in AGM if you want. http://forums.bistudio.com/showthread.php?187595-Mine-Detector&p=2856461&viewfull=1#post2856461

You can modify it and do whatever you want with it :)
