### ISSUE TITLE
Cable tied prisoner shouldn't be able to transmit message on radio

### ISSUE THREAD

**Issue by bux** [KoffeinFlummi/AGM#809]
**Arma3:** 1.24
**Mods:** CBA_A3, AGM_dev, mcc_sandbox, TaskForceRadio
**AGM_dev from:** 2014-08-10T16:35:13.342Z
**Tested on:** dedicated server
**Zeus enabled:** No
**Modules:** No module

A prisoner should not be able to use his TaskForceRadio radio. (probably the same with ACRE?)

**Comment by Hees** [comment]
If it is possible to take items from the prisoner, be sure to take his radio. But if you forget to take it, the prisoner will be able to use his radio, if so equipped.

**Comment by commy2** [comment]
Please don't revieve months old issues.
