### ISSUE TITLE
Wire Cutter Item

### ISSUE THREAD

**Issue by Ezaco** [KoffeinFlummi/AGM#945]
Not sure if this is planned or not (I searched but didn't see anything), but rather than using a toolkit to cut fences a re-usable wire cutter item should be made. I know ACE made this a launcher/backpack item, but that shouldn't be necessary. Even the larger cutters could just be hauled around and strapped to a backpack.

**Comment by commy2** [comment]
\>\> https://github.com/KoffeinFlummi/AGM/issues/1937
